### ISSUE TITLE
Adding AngularFire2 to the advanced Seed

### ISSUE THREAD

**Issue by OscarAgreda** [NathanWalker/angular-seed-advanced#100]
One of the best things about seed is the fact that is so easy to start with, just a few steps to follow and boom there it is.

I have been evangelizing about angular2 and nativeScript using this seed in some meetups groups; and I have noticed that after the initials steps everything after seems very hard for most people, as expected obviously, because everything is new.  TypeScript, Angular2, nativescript and electron are unknown to most developers.
Thus, sometimes i move away from the seed for a while, and perform some AngularFire2 coding, then most people find it very easy.

for example
**David East** on this demo [(https://www.youtube.com/watch?v=oLG5TXLeuHQ)]
creates a chat application in less than 40 lines of code that does dynamic querying.

What do you think about adding some of that AngularFire2 magic to the **Advanced Seed**, to drastically reduce the complexity and to get people going really easy and very fast? Then after they can choose to move to a more advanced databases or other way of storing the data. In our time pretty much every app store data somewhere.

**Comment by aaweb** [comment]
I would be very much in favor of that! :)

I'm currently using AngularFire2 with this seed (waiting for the [update to Firebase SDK 3](https://github.com/angular/angularfire2/issues/180)). Before it can be fully integrated to this project though, I think we'd need NativeScript support. Have a look at the request I filed with them:
https://github.com/angular/angularfire2/issues/110

Meanwhile, I'm using this plug-in on the Native Script side:
https://github.com/KallynGowdy/nativescript-plugin-firebase

**Comment by NathanWalker** [comment]
@OscarAgreda I love your ideas and enthusiasm :)
Because having a specific backend integration on master branch would limit some other uses which may use a different backend, I wouldn't be interested in integrating `AngularFire2` on master, however on a branch would be awesome.

@aaweb NativeScript integration works and if you'd be interested in helping with a PR to a branch here, please let me know. If you submit a PR, you can target this branch:
https://github.com/NathanWalker/angular2-seed-advanced/tree/angularfire2

**Comment by aaweb** [comment]
@NathanWalker: By "NativeScript integration works", you mean someone has gotten AF2 working with NativeScript? If so, is there an example somewhere you could point me to? I got AF2 working on the web side of things with the seed, but still need to figure out the NativeScript end.

**Comment by NathanWalker** [comment]
@aaweb Working implementation here:
https://github.com/NativeScript/sample-Groceries/tree/angular-firebase
This commit has the details:
https://github.com/NativeScript/sample-Groceries/commit/2e441059038b3d74806665d22f2110d09f1fe010
Then for Android, this can be followed:
https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/39

**Comment by aaweb** [comment]
@NathanWalker I saw your wiki page about integrating firebase. Very helpful and pretty much the way I've done it previously. Now that angularfire2 is on SDK3, I hope they'll also think about NativeScript support.

**Comment by NathanWalker** [comment]
Yes @aaweb I'm not 100% clear of the changes in angularfire2 and whether this https://github.com/EddyVerbruggen/nativescript-plugin-firebase could work with it? 

But there is definitely a detailed step by step on the wiki here for this: https://github.com/NathanWalker/angular2-seed-advanced/wiki/How-to-integrate-Firebase-across-all-platforms-(web-nativescript-desktop)

**Comment by flobo79** [comment]
Any progress on this? Thx.

**Comment by abnerh69** [comment]
Hi NathanWalker, I really appreciate your contributions.  Following you last comment, about https://github.com/NathanWalker/angular2-seed-advanced/wiki/How-to-integrate-Firebase-across-all-platforms-(web-nativescript-desktop), I got lost trying... and got web exception: Uncaught (in promise): Error: No provider for DatabaseService! 
Is it possible you share some complete sample added to https://github.com/NathanWalker/angular2-seed-advanced/wiki/How-to-integrate-Firebase-across-all-platforms-(web-nativescript-desktop) ?

Thank you

**Comment by LaKrue** [comment]
Hi, I'm facing the same web exception as @abnerh69: "No provider for DatabaseService!"
Did anyone solve this yet?

**Comment by NathanWalker** [comment]
@abnerh69 @LaKrue just updated wiki tonight to match latest changes on master as of tonight.
No provider message indicates it's not added to an NgModule likely, can you share your project repos where you were trying and I could see if something jumps out?

**Comment by jsatka** [comment]
I'm facing the same "No provider for DatabaseService!" exception after following the wiki guide for integrating Firebase across all platforms. @NathanWalker sharing the project repo where it happens, in case that is helpful.

**Comment by jlooper** [comment]
If you are looking for a full cross-platform example of using this seed with Firebase for web and NativeScript, you can use PocketRave as an example: http://github.com/jlooper/pocketrave. It needs some updating but may help. I've been tinkering with AngularFire2 the past few days and it's not a full implementation of all the functionality of Firebase (for example, file upload doesn't seem to be supported) so I wound up using just the plain firebase implementation for the web as per the Firebase docs on my newer project. Just a caveat on AngularFire.

**Comment by sionfletcher** [comment]
Seeing the same error having followed the firebase Wiki - ""No provider for DatabaseService!". Did anyone find a solution?
