### ISSUE TITLE
LiveReload css detected by BrowserSync but not visible on page until manual refresh

### ISSUE THREAD

**Issue by amirtoole** [NathanWalker/angular-seed-advanced#101]
CSS changes are detected (moved to dist folder) and BrowserSync is notifying that *.css has been injected, however no updates appear in page.

I've temporarily had to tweak the setting in https://github.com/NathanWalker/angular2-seed-advanced/blob/8544b8c2e17d2de42fcde47278f18f414af7868d/tools/utils/seed/code_change_tools.ts#L48

Will dig deeper as to the cause unless someone has a simple solution.

**Comment by aaweb** [comment]
I'm also seeing this problem. I'm using Sass (scss) files according to the guide in the parent project:

https://github.com/mgechev/angular2-seed/wiki/Add-Sass-support

**Comment by amirtoole** [comment]
Closer to a solution: seems like only main.css is being pushed to browser, regardless of which file was modified. Any css file modification triggers the following in browser sync WS frame

```
42/browser-sync,["file:reload",{"ext":"css","path":"*.css","basename":"*.css","type":"inject","log":true}]
```

which triggers fetching main.css (even if a different file was modified):

```
http://localhost:5555/dist/dev/css/main.css?1464556759343=&rel=1464556914500
```

@aaweb I too am using sass however this bug is independent of that (testing with latest master of this repo).

**Comment by NathanWalker** [comment]
Seems like this was reported in the parent seed...
https://github.com/mgechev/angular2-seed/issues/925
https://github.com/mgechev/angular2-seed/issues/804

**Comment by joshwiens** [comment]
@hellofornow @NathanWalker - I'll take this one, realistic E.T.A will be Friday afternoon.

**Comment by NathanWalker** [comment]
@d3viant0ne was this still pending?

**Comment by joshwiens** [comment]
@NathanWalker It was waiting on the whole decoupling thing. I have some maintenance work to do on the Material2 fork planned for Friday post work. I'll stick this back on the docket and fix it upstream.

**Comment by joshwiens** [comment]
@NathanWalker @hellofornow - This has already been fixed [upstream](48da317b00fff173264e2947d468e2d3be5f4dca) and the change is already in #master 

https://github.com/NathanWalker/angular2-seed-advanced/blob/master/tools/utils/seed/code_change_tools.ts#L44-L51

Though I would have probably just removed the code as opposed to commenting it out, this issue no longer exists. CSS changes are detected / refresh as expected.

**Comment by joshwiens** [comment]
@hellofornow - can you please verify this is no longer an issue for you and if so, close it. Thanks :)

**Comment by amirtoole** [comment]
Ya; will close this as the feature is (unfortunately) unavailable.

**Comment by joshwiens** [comment]
It works just fine, what's the issue?

**Comment by amirtoole** [comment]
BrowserSync supports hot loading css changes (without a page refresh). From the parent seed it seems that feature won't be supported.

**Comment by joshwiens** [comment]
Ah, I misunderstood what it is you were talking about.

@NathanWalker isn't against deviating from the parent seed when it makes sense. I can certainly see valid use cases for wanting to inject css changes and iirc, it's doable in the seed it would just take a bit of work.

It's up to Nathan.

**Comment by NathanWalker** [comment]
Hot loading CSS makes a lot of sense to me for this seed. I can't recall why it's not supported in parent seed but I'd be open to enabling if here if no side effects. 

Out til Tuesday, check back then.
