### ISSUE TITLE
Adding external node fs dependency

### ISSUE THREAD

**Issue by friksa** [NathanWalker/angular-seed-advanced#102]
I am trying to use node fs inside the electron app, but not having any success.  I followed these instructions:
https://github.com/mgechev/angular2-seed/wiki/Add-external-dependency

```
npm --save install fs

Add this to the constructor of tools/config/project.config.ts
(<any>this.SYSTEM_CONFIG_DEV.paths)['fs'] = `${this.APP_BASE}node_modules/fs/index`;
```

But when I run the app with "npm run start.livesync.desktop", I get the following error in the console.

```
GET file:///Users/friksa/dev-sp/gp6/dist/dev/node_modules/nodelibs/fs.js net::ERR_FILE_NOT_FOUND

Error: Error: XHR error loading file:///Users/friksa/dev-sp/gp6/dist/dev/node_modules/nodelibs/fs.js(…) "Report this error at https://github.com/NathanWalker/angular2-seed-advanced/issues"
```

I am trying to wrap my head around the whole build system so that I can document it for this project.  I am even willing to pay for help as I am not making any progress and I may have to switch to another seed project where I have no issues importing external dependencies, but it is not using system.js

Thanks for any help!

**Comment by NathanWalker** [comment]
@friksa you can chat with me here (@walkerrunpdx): https://t.co/uExEluDrmO

Developing for multiple platforms from the same codebase requires understanding of a number of things, which is why this seed is `advanced`.

You cannot use the node `fs` module on the web therefore you would not configure it with systemjs.
Furthermore it can only be accessed in the `main.desktop.ts` file which electron uses to bootstrap the app.

**Comment by NathanJGaul** [comment]
Was there any may around this just for desktop builds? Trying to use `child_process` myself.

**Comment by friksa** [comment]
try this:

```
cd src/client
npm --save install fs
#### do not npm install it at the top level as it will cause an issue

cd ../..
```

Now edit tools/config/project.config.ts and add this to the constructor:

```
    if (this.TARGET_DESKTOP) {
      (<any>this.SYSTEM_CONFIG_DEV.paths)['fs'] = `${this.APP_BASE}node_modules/fs/index`;
    }
```

**Comment by Kaffiend** [comment]
actually in the scope of a pure electron app, imho, this is just a limitation of SystemJs. with webpack and some plugins, you can use native modules, rather easily. the folks over at zone are working on patching the mongo calls, to fix the change detection you just have to manually run the callbacks through zone atm. but it can be done.
```
import { Injectable } from '@angular/core';
import { IDbSetting, IWorkspaceConfig } from '../models/interfaces/index';

import { MongoClient, MongoError, Db } from 'mongodb';
import * as electron from 'electron';
import * as path from 'path';
import { readFileSync, writeFileSync } from 'fs';

@Injectable()
export class WorkstationConfigService {

    mongo: MongoClient;
    userDataPath: string = (electron.app || electron.remote.app).getPath('userData');
    dbSettings: IDbSetting = <IDbSetting>{};
    dbConn: boolean = false;
    workstationConfig: IWorkspaceConfig;
    //Add Defaults later.

    constructor() { 
        this.mongo = new MongoClient();
        this.userDataPath = path.join(this.userDataPath, 'workstation.json');
        this.workstationConfig = this.parseUserData(this.userDataPath);
    }
```
