### ISSUE TITLE
npm run start.ios fails with tns: command not found error

### ISSUE THREAD

**Issue by joeblew99** [NathanWalker/angular-seed-advanced#103]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

On this Env:
Mac OSX
node -v v6.0.0
npm -v 3.8.6

Clean install from nothing
npm install -g nativescript
npm install -g typescript
# install the project's dependencies

npm install
# watches your files and uses livereload by default

npm start

_What steps should we try in your demo to see the problem?_

npm run start.ios

**Current behavior**

```
x-MacBook-Pro:angular2-seed-advanced apple$ npm run start.ios

> angular2-seed-advanced@0.0.0 start.ios /Users/apple/workspace/go/src/bitbucket.org/gedw99/Psycho/code/angular2-seed-advanced
> cd nativescript && tns emulate ios

sh: tns: command not found

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/apple/.nvm/versions/node/v6.0.0/bin/node" "/Users/apple/.nvm/versions/node/v6.0.0/bin/npm" "run" "start.ios"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angular2-seed-advanced@0.0.0 start.ios: `cd nativescript && tns emulate ios`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angular2-seed-advanced@0.0.0 start.ios script 'cd nativescript && tns emulate ios'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed-advanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd nativescript && tns emulate ios
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed-advanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed-advanced
npm ERR! There is likely additional logging output above.
```

**Expected/desired behavior**

Should load ios sim

**Other information**

**Comment by joeblew99** [comment]
It might be related to this:
https://github.com/NativeScript/nativescript-cli/issues/1191

**Comment by NathanWalker** [comment]
Sounds like this is unrelated to the seed and more related to your environment, I'm going to close this, but if you find a solution to your environment, you may post back here.

**Comment by joeblew99** [comment]
Is there a docker image ?
