### ISSUE TITLE
{N} build creates .js & .js.map files inside src/client

### ISSUE THREAD

**Issue by fourctv** [NathanWalker/angular-seed-advanced#107]
I know that the `nativescript/src/client` folder is a symlink into `src/client`, but that causes a side effect of creating `.js` & `.js.map` files inside my development tree whenever I build/start {N}. 

Those files are supposedly created inside `nativescript` folder, but the symlink causes that side effect.

Is there a workaround to avoid that? or maybe a `cleanup` script that would get rid of those files at some point?

**Comment by fourctv** [comment]
for now, I've added a new file `/tools/tasks/project/clean.all.src.js.ts`:

```
import * as chalk from 'chalk';
import { lstatSync, readdirSync } from 'fs';
import * as util from 'gulp-util';
import * as rimraf from 'rimraf';
import { join } from 'path';

import { APP_SRC } from '../../config';

/**
 * Executes the build process, deleting all JavaScript and Source Map files (which were transpiled from the TypeScript sources) with in
 * the `src/client` directory.
 */
export = (done: any) => {
  deleteAndWalk(APP_SRC);
  done();
};

/**
 * Recursively walks along the given path and deletes all JavaScript files.
 * @param {any} path - The path to walk and clean.
 */
function walk(path: any) {
  let files = readdirSync(path);
  for (let i = 0; i < files.length; i += 1) {
    let curPath = join(path, files[i]);
    if (lstatSync(curPath).isDirectory()) { // recurse
      deleteAndWalk(curPath);
    }
  }
}

/**
 * Deletes the JavaScript file with the given path.
 * @param {any} path - The path of the JavaScript file to be deleted.
 */
function deleteAndWalk(path: any) {
  try {
    rimraf.sync(join(path, '*.js'));
    util.log('Deleted', chalk.yellow(`${path}/*.js`));
    rimraf.sync(join(path, '*.js.map'));
    util.log('Deleted', chalk.yellow(`${path}/*.js.map`));
 } catch (e) {
    util.log('Error while deleting', chalk.yellow(`${path}/*.js`), e);
  }
  walk(path);
}
```

**Comment by amirtoole** [comment]
You could achieve this with the following command (make sure you execute it in the appropriate path!):

```
find . -name "*.js*" -type f -delete
```

It will delete all .js and .js.\* files

**Comment by NathanWalker** [comment]
@fourctv @hellofornow I like both of your options! If either wants to submit a PR that would add either strategy as an `npm` script in `package.json` would be great.

I always ignore `*.js` and `*.map` files throughout VS Code so they are never in my way but I'm sure if it bothers you guys, it certainly will to someone else 👍

**Comment by NathanWalker** [comment]
@fourctv provided a task for this, on master now with this:
https://github.com/NathanWalker/angular2-seed-advanced/pull/125

**Comment by JavascriptMick** [comment]
@hellofornow note that ".js*" also deletes .json files which I don't think was your intent.  Also, very dangerous command line.
