### ISSUE TITLE
Discussion: Why use ngrx/store instead of Redux?

### ISSUE THREAD

**Issue by mpetkov** [NathanWalker/angular-seed-advanced#110]
Redux is extremely popular and currently has over 19,000 stars on github.  So why did you guys decide to use the less popular ngrx/store instead of Redux for state management?

**Comment by NathanWalker** [comment]
Redux is really just a philosophy of state management which is behind `ngrx/store` and provides a nice api when used in conjunction with Angular. You can use either, the principles are the same.

**Comment by NathanWalker** [comment]
I could open this up for discussion here but it's really best left to discuss on `ngrx/store` repo where discussion has already taken place. As mentioned there, some of the `Redux` (TM) toolilng is tied to `React` which is another reason `ngrx/store` is better suited here.
