### ISSUE TITLE
styleUrls and nativescript

### ISSUE THREAD

**Issue by arnaudvalle** [NathanWalker/angular-seed-advanced#111]
I just came across a small issue while trying to style some components using Nativescript. It seems like the DecoratorUtils is getting rid of the styleUrls metadata for native:

```
if (metadata.styleUrls && CoreConfigService.IS_MOBILE_NATIVE()) {
      // {N} doesn't support all css properties, therefore remove styleUrls to be safe
      delete metadata.styleUrls;
}
```

which means you can't add custom component-specific styles out of the box?

While I understand why you're doing this (because of the limited css support), I think it's maybe a bit extreme to remove it all? That basically means that for nativescript, you'd need to have all your css in app.css (which is a bit painful to maintain I would have thought?) or, of course you can just get rid of that statement...

Just wondering if somebody has some alternative or what your general thoughts are really...

**Comment by NathanWalker** [comment]
We could bring this back. The biggest issue is that when unsupported css is used, it can break the {N} app entirely. For instance `:host` is not supported by NativeScript currently.

Thoughts are welcome if we should just allow this to be left up to the developer to figure out?
Basically it would boil down to developers needing to put only `web` only css properties in their global css file and keep their component styling to cross platform css styles only.

**Comment by NathanWalker** [comment]
@arnaudvalle Turns out latest NativeScript does not have issue with the styles. The `styleUrls` are no longer stripped on latest master and you can use them now, thanks for bringing this up 👍

**Comment by arnaudvalle** [comment]
nice one @NathanWalker - thanks for looking into this
