### ISSUE TITLE
fs, child_process, ect. on desktop builds

### ISSUE THREAD

**Issue by NathanJGaul** [NathanWalker/angular-seed-advanced#113]
In reply to issue #102 was there anyway to get around to using desktop specific node libraries on desktop builds, such as fs or child_process? Thanks for your help!

**Comment by friksa** [comment]
try this:

```
cd src/client
npm --save install fs
#### do not npm install it at the top level as it will cause an issue

cd ../..
```

Now edit tools/config/project.config.ts and add this to the constructor:

```
    if (this.TARGET_DESKTOP) {
      (<any>this.SYSTEM_CONFIG_DEV.paths)['fs'] = `${this.APP_BASE}node_modules/fs/index`;
    }
```

start electron client

**Comment by NathanJGaul** [comment]
Thanks for the help @friksa! Been trying to figure this out all week.

**Comment by NathanWalker** [comment]
Let's add this to a Wiki page @friksa, thank you for this.
If you wanted to help create a markdown page, I can add it in.

**Comment by friksa** [comment]
@NathanWalker have you made changes to the MarkDown file I sent you?  if not, I can add this to it.  Otherwise, send me the latest version and I will update it.  You're welcome @Infining

**Comment by NathanJGaul** [comment]
Found an easy way to load core Node modules without npm installing them directly to `src/client` via [stackoverflow](http://stackoverflow.com/questions/36546860/require-nodejs-child-process-with-typescript-systemjs-and-electron). For the `fs` module it works fine as you can install it with npm as explained above, but for some reason `child_process` was not in the npm registry.

In `index.html` add

```
<script>
System.config({
  map: {
    'child_process': '@node/child_process'
  }
});
</script>
```

under `<% if (TARGET_DESKTOP) { %>`. Now I can `import {spawn} from 'child_process`, etc. in my desktop build.

**Comment by friksa** [comment]
Awesome!  Thanks for sharing!

**Comment by friksa** [comment]
I have not tried it yet, but I bet this works in tools/config/project.config.ts (without the npm install)

```
    if (this.TARGET_DESKTOP) {
      (<any>this.SYSTEM_CONFIG.paths)['fs'] = `@node/fs`;
    }
```

I think it is a good idea _not_ to change index.html if you can.
