### ISSUE TITLE
BaseComponent Template rendering issue when  using an observer service

### ISSUE THREAD

**Issue by gomesNazareth** [NathanWalker/angular-seed-advanced#115]
I noticed that when I use the baseComponent. The template renders before the observer service completes and I cannot display the data in the template.But how ever when i changed the BaseComponent to Component every thing works fine.

**Comment by NathanWalker** [comment]
Solve on Slack...

**Comment by ringodotnl** [comment]
Same problem with last pull. Doesn't seemed to be solved.
