### ISSUE TITLE
Use ChangeDetectionStrategy.Default instead

### ISSUE THREAD

**Issue by friksa** [NathanWalker/angular-seed-advanced#116]
app/frameworks/core.framework/decorators/util.ts sets the default change detection strategy to:
**ChangeDetectionStrategy.OnPush**

Specifying it as **ChangeDetectionStrategy.Default** in each components seems to work... however when integrating 3rd party components, I have seen issues where the UI is not always updating as expected.

When changing util.ts to use **ChangeDetectionStrategy.Default** instead, all the update problems go away.

It seems to make sense for the project to use **ChangeDetectionStrategy.Default** as the default and **ChangeDetectionStrategy.OnPush** by exception where needed.

Or am I missing something?

Thanks!

**Comment by NathanWalker** [comment]
Definitely curious to hear other thoughts here. Indeed, defaulting to `OnPush` does require some understanding of 1 way data flows and immutability so some service architecture won't work well with `OnPush`, but this seed is `advanced` for a reason so assumes some understanding of certain concepts.

I'll leave this open for discussion. I'm open to defaulting to `Default` if others find that better and they can dial to `OnPush` for better performance in their own apps on their own time?

**Comment by friksa** [comment]
Sounds good.

Advanced people will be smart enough to change it to onPush where new users will more easily ease into this project.  Advanced does not have to mean complex :)

I wasted a few days on this issue.  Even though I had a good grasp of the Angular2 concepts, this configuration option made it behave different than most of the documentation and examples out there.  Now that I know it, it is not a problem for myself anymore, but would love others to have a good first experience with this project.

Worst case, it needs to be well documented and configurable in project.config.ts file IMO.

**Comment by NathanJGaul** [comment]
I have also been dealing with this for the past few days and it has helped me better understand Angular 2 while adapting to the seed's default. I do agree with @friksa though, configuration in project.config.ts allows for easy control over the project and it would be nice to include the desired default change detection strategy in there.

**Comment by JonnyBGod** [comment]
I like the documentation way.

Default to good practices and explain how to solve common problems, this way we help less experienced developers to learn and try to keep up, if they don't have the time or need we document a simple way to turn it off.

**Comment by NathanWalker** [comment]
I have added a special note in the README about this and provided instructions on how to turn it off 👍

**Comment by NathanWalker** [comment]
https://github.com/NathanWalker/angular2-seed-advanced#change-detection-onpush-note

**Comment by yagobski** [comment]
I spent 3 days to found the solution. Please update the documentation.
