### ISSUE TITLE
Getting exception while loading main.css

### ISSUE THREAD

**Issue by vivek-chowdhury** [NathanWalker/angular-seed-advanced#120]
Hi Nathan,

I am getting exception in console window while running debug build in windows platform please find the below error:

file:///E:/Electron-Seed/dist/dev/dist/dev/css/main.css?1465388122660 
Failed to load resource: net::ERR_FILE_NOT_FOUND
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
Uncaught Error: connect ECONNREFUSED 127.0.0.1:30080
Uncaught Error: socket hang up

I guess during injecting main.css somehow it is embedding 'dev/dist' twice in the path. So, I am unable to fetching global style from main.css.

Please suggest

**Comment by joshwiens** [comment]
> This is specific to your project as this issue does not exist in angular2-seed-advanced#master.

**To your problem**
You are duplicating `DEV_DEST` somewhere in your config.

If you modified the `seed.config.ts` or `seed-advanced.config.ts` don't. Use the `project.config.ts` and override specific settings.

If you made your changes in `project.config.ts` than that is where you want to start looking and through to the `build.html_css.ts` where main.css is injected.

The seed tools are debuggable, if you can't run down the problem read the wiki on debugging the tools in the parent angular2-seed and step through the code until you find the problem.
