### ISSUE TITLE
Getting exception while loading main.css

### ISSUE THREAD

**Issue by vivek-chowdhury** [NathanWalker/angular-seed-advanced#121]
Hi,

This issue is continuation of my previous bug (i.e.  Getting exception while loading main.css #120). As suggested by Joshua Wiens I have cloned fresh copy of angular2-seed-advanced and commented below mentioned piece of code in main.desktop.ts to activate developer tool in exe.

menu = Menu.buildFromTemplate(template);
mainWindow.setMenu(menu);

When I ran angular2-seed-advanced debug build using 'npm run start.desktop.windows' got same exception which I have reported in the above mentioned bug earlier.

file:///E:/Electron-Seed/dist/dev/dist/dev/css/main.css?1465388122660 
Failed to load resource: net::ERR_FILE_NOT_FOUND
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
Uncaught Error: connect ECONNREFUSED 127.0.0.1:30080
Uncaught Error: socket hang up

So that means reported bug is not project specific and I request you to please guide me on this.

**Comment by igonzalezespi** [comment]
Getting same error in Windows 7.
I think the problem is the function `transformPath` in the file `tools/tasks/seed/build.index.dev.ts`.
It is searching for "dist/dev" while in Windows is "dist\dev", so it doesn't get removed.

I did this workaround:

```
if (path.indexOf('dist/dev') > -1 || path.indexOf('dist\\dev') > -1) {
  path = path.replace(/(dist\/dev\/)|(dist\\dev\\)/g, '');
}
```

Is this an error?

**Comment by NathanWalker** [comment]
@ivannugo if the above works for you, mind submitting a PR to fix for Windows users?
