### ISSUE TITLE
assets/js files not injected into web client production build

### ISSUE THREAD

**Issue by friksa** [NathanWalker/angular-seed-advanced#122]
The legacy JS files added to src/client/assets/js are not injected into the production web client when using:
npm run build.prod

tools/config/project.config.ts constructor

```
this.APP_ASSETS.push(
  { src: `${this.ASSETS_SRC}/js/Sortable.js`, inject: true, vendor: false }
);
```

Works fine in development web client and desktop client (both production and development versions).  However, when the js is minified and combined, these JS files are not included in the list.

I looked at tools/tasks/seed/build.js.prod.ts and tried to add it to gulp.src, but no luck:

```
let result = gulp.src([join(TMP_DIR, BOOTSTRAP_DIR, ASSETS_SRC+'/js/*.js', '**', '*.html')]);
```

**Comment by friksa** [comment]
Any ideas here?  Is there a way to put bounties on issues like these that are not important to anyone else?

**Comment by NathanWalker** [comment]
Hi @friksa take a look at the parent seed Wiki https://github.com/mgechev/angular2-seed/wiki, you can find some answers there 👍

**Comment by friksa** [comment]
I have been through all the examples there.  Everything runs fine during development for all client types.

Even the production builds for the electron client is good.  The only issue is with the production build for the web client.
