### ISSUE TITLE
Need a way to detect a development build vs release build

### ISSUE THREAD

**Issue by friksa** [NathanWalker/angular-seed-advanced#123]
You can use CoreConfigService.IS_WEB(), etc to detect the platform, but there is no way to detect (as far as I can tell) whether you are running a development or release build.  This is important since different URLs are used for accessing resources during development vs released version of the application.

**Comment by friksa** [comment]
You can use "process.env.NODE_ENV === 'development';" to do this detection on the desktop client, but not sure how to do it with the web client.

**Comment by NathanWalker** [comment]
You can see an example of how to do this in your TS files here:
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/src/client/main.web.ts#L22

**Comment by friksa** [comment]
perfect - thanks
