### ISSUE TITLE
Inconsistent electron version numbers

### ISSUE THREAD

**Issue by friksa** [NathanWalker/angular-seed-advanced#124]
When you install a certain version of electron in package.json, it is inconsistent with these 3 files:
- tools/tasks/project/desktop.package/linux.ts
- tools/tasks/project/desktop.package/mac.ts
- tools/tasks/project/desktop.package/windows.ts

Not sure if there is a better way to keep things in sync, but at least it should be documented that the version number should be updated in multiple places.

**Comment by kbrandwijk** [comment]
You could require package.json in the ts files and read the version number from the dependency that's in there, but that would also mean removing any prefixes (like ^ or ~).

**Comment by NathanWalker** [comment]
Feel free to continue discussion here, just closing to cleanup outstanding issues.
