### ISSUE TITLE
build.prod fails on Windows 8

### ISSUE THREAD

**Issue by amirtoole** [NathanWalker/angular-seed-advanced#126]
Our internal CI is on Windows 8, and is unable to execute the task build.bundles.app due to trying to look for main.web.ts in in "node_modules".

```
[18:44:41] 'build.bundles.app' errored after 932 ms
[18:44:41] Error on fetch for dist\tmp\main.web.js at file:///C:/JenkinsSlave/amir-playground/angular2-seed-advanced/node_modules/dist\tmp\main.web.js
        Error: ENOENT: no such file or directory, open 'C:\JenkinsSlave\amir-pla                             yground\angular2-seed-advanced\node_modules\dist\tmp\main.web.js'
    at Error (native)
[18:44:41] 'build.prod' errored after 14 s
[18:44:41] Error in plugin 'run-sequence(build.bundles.app)'
Message:
```

Can confirm this is **not** happening on Windows 10; not sure if this will ever affect anyone else.

Ran the task with latest master to confirm it wasn't anything we've modified in our project.

**Comment by amirtoole** [comment]
I should have looked in parent seed project.
They're aware of it:
https://github.com/mgechev/angular2-seed/issues/975

**Comment by zeeshanjan82** [comment]
I think this issue is fixed in parent seed project and not in this advanced seed, how can we replicate the fix here.

**Comment by NathanWalker** [comment]
@hellofornow and @zeeshanjan82 latest upstream parent has been merged in. Please try pulling master and try this. If it fixes, please close this issue 👍

**Comment by amirtoole** [comment]
Can confirm it is fixed. Thanks a lot!
