### ISSUE TITLE
What about printing or reporting ?

### ISSUE THREAD

**Issue by OscarAgreda** [NathanWalker/angular-seed-advanced#127]
Most,  if not all Enterprise Application will eventually require some type of **report** or **pdf**.
There are many "server side" packages out there to do that as well as lots and lots of commercial (paid) components for that reason. 

Somehow that “server dependency"  reporting feels ancient and old-fashioned, as if does not belong to the new “front end power” of angular.

2 weeks ago I i was able to 

-create a PDF from our data.
-nicely display the PDF on the UI, in our case is inside an Angular Material Tab.
-email it.
-print it.
      All done on the front-end, works fine for web as well as on the mobile native apps.

using the following 3 libraries:

[https://github.com/bpampuch/pdfmake](https://github.com/bpampuch/pdfmake)
[https://github.com/sayanee/angularjs-pdf](https://github.com/sayanee/angularjs-pdf)
[https://github.com/mozilla/pdf.js](https://github.com/mozilla/pdf.js)

@NathanWalker , Do you think that incorporating printing/reporting this way, will be of value to the advanced seed?

**Comment by NathanWalker** [comment]
Definitely on a branch @OscarAgreda, very nice. If you have the project up on GitHub anywhere or can share with me, I can help extrapolate the details onto a branch here.

**Comment by OscarAgreda** [comment]
Sounds like a plan, I'll do that .

**Comment by NathanWalker** [comment]
I'm going to close this @OscarAgreda but feel free to submit a PR to this branch: https://github.com/NathanWalker/angular2-seed-advanced/tree/pdf-reports if you'd like 👍
