### ISSUE TITLE
Getting started question

### ISSUE THREAD

**Issue by jwhits** [NathanWalker/angular-seed-advanced#129]
First of let me say this project is awesome! exactly what I have been looking for.

I have downloaded, setup and got the sample app running as per the instructions. I am just a bit lost as to where I start adding my app code so it has minimal impact on future merging of your upstream seed code.

In this instructions you say.

> 1. Create a new framework for your application in src/client/app/frameworks to build your codebase out. Say your app is called AwesomeApp, then create awesomeapp.framework and start building out all your components and services in there. Create other frameworks as you see fit to organise.

So I should create my app under frameworks in a folder called awesomeapp.framework, do I then also create an app.component.ts in there and change src/client/main.web.ts to reference my new src/client/app/frameworks/awesomeapp.framework/app.component.ts instead of src/client/app/components/app/app.component.ts?

I presumably then I can delete src/client/app/components folder and the app.framework folder? Which will probably return when I do the an upstream pull? and I will get a conflict on src/client/main.web.ts?

Sorry for all the questions just not 100% sure where the sample app starts and stops. May I suggest that you make this a little clearer? could have sampleapp.framework. Or if its depended on the upstream angular2-seed maybe a branch that shows clearly how to put your own app code in, for example a simple to do app. I think with all the work you have already done, this would make it super simple for people to get started.

**Comment by NathanWalker** [comment]
Thank you.

> So I should create my app under frameworks in a folder called awesomeapp.framework, do I then also create an app.component.ts in there and change src/client/main.web.ts to reference my new src/client/app/frameworks/awesomeapp.framework/app.component.ts instead of src/client/app/components/app/app.component.ts?

This is a general recommendation and I would do this, however it's totally up to you on your components leading to next question...

> I presumably then I can delete src/client/app/components folder and the app.framework folder?

Yes on `components` folder, you can remove that and just build your own set. Removing `app.framework` is up to you as well. If you don't need it, remove it.

> Which will probably return when I do the an upstream pull?

It would only return if changes to that folder had been made (upstream) subsequent to the time you downloaded the repo and followed the git setup instructions. This is farely low to happen with app.framework but more frequent with `components` folder. In either case, handling any conflicts there should not be too bad and they settle out over time.

> and I will get a conflict on src/client/main.web.ts?

Again conflicts shouldn't be too bad if you followed the instructions here: https://github.com/NathanWalker/angular2-seed-advanced#how-best-to-use-for-your-project

Agreed, I will look into creating a `sampleapp.framework` as a starting place on a branch maybe, some good thoughts, thanks. Please close if this answers for you ^

**Comment by jwhits** [comment]
Thanks for clearing things up so quickly!

**Comment by spicemix** [comment]
You might sprinkle comments through the code like

`// TODO ng2seed Add your additional Providers here...`

Which would 
1. give us IDE TODO highlighting to quickly see a checklist
2. let us filter it from our own TODOs with `ng2seed`
3. guide us in context what you intend us to do with the seed code
4. let us follow where you moved things in new pulls based on the help text of the comment
5. show us the extents of the included sample app code we can go ahead and delete

BTW let me also emphasize how insanely awesome this project is...
