### ISSUE TITLE
Upgrade Angular2-seed to rc.2 and new Routes

### ISSUE THREAD

**Issue by rodolfocop** [NathanWalker/angular-seed-advanced#130]
No description provided.

**Comment by joshwiens** [comment]
1.) These changes currently come from the parent seed.

2.) Last time I looked, the new router & {N} don't play well together. The new router also isn't in a usable state so i'm doubting this will be happening anytime in the near future.

//cc @NathanWalker

**Comment by rodolfocop** [comment]
Hi @d3viant0ne 
I'll be waiting for the parent seed updating, so you can upgrade my design also.
On the routes i'm really curious to see how this change may affect the project in which I participate.

Thanks man!

**Comment by joshwiens** [comment]
The parent seed is in the middle of a major refactoring project mgechev/angular2-seed#959 I wouldn't expect rc2 to land until after that hits master though you are welcome to ask there.

As far as the new router goes, outside of the fact it doesn't work with {N} right now ( NativeScript folks are waiting on breaking changes planned for the new router ) and a bit of personal experience, the new router is a bit hard to work with, very "happy path only" with little to no documentation.

The path I have chosen for my professional projects after a bit of tinkering is to simply wait until it's stable. New router took a few semantic changes to get working until I got into more complex child / dynamic routes where it kind of fell on it's ass.

If you want to try that yourself, the parent seed is running on the new router not router-deprecated which should provide a reasonably easy to follow roadmap for the change. That said, per the angular team, breaking changes are coming so it may turn into a gigantic time sink should you chose to go with the new router.

**Comment by NathanWalker** [comment]
Master has rc.3 and new router `3.0.0-alpha.7` now 👍

**Comment by rodolfocop** [comment]
Thanks, I will update now!
