### ISSUE TITLE
Creating new services without using ngrx store framework doesn't keep DOM updated

### ISSUE THREAD

**Issue by jovermier** [NathanWalker/angular-seed-advanced#131]
This simple polling service (used for IoT sensors) will not work with this project. It will receive the XHR but the DOM will not update.

Remove the ".txt" file extension from the files attached:
[blank.component.html.txt](https://github.com/NathanWalker/angular2-seed-advanced/files/319277/blank.component.html.txt)
[blank.component.ts.txt](https://github.com/NathanWalker/angular2-seed-advanced/files/319279/blank.component.ts.txt)
[Search.ts.txt](https://github.com/NathanWalker/angular2-seed-advanced/files/319281/Search.ts.txt)

Issue #116 may be related to this.

**Comment by NathanWalker** [comment]
@jovermier instead do this:

blank.component.ts:
```
@BaseComponent({
  moduleId: module.id,
  selector: 'sd-blank',
  providers: [NamesService],
  templateUrl: 'blank.component.html',
  styleUrls: ['blank.component.css']
})
export class BlankComponent {

  constructor(public namesService:NamesService) {

  }

}
```

blank.component.html:
```
<div *ngFor="let name of namesService.GetNames() | async">
  {{name}}
</div>
```

Please close if solves for you.

**Comment by NathanWalker** [comment]
Do this instead:

```
import {BehaviorSubject} from "rxjs/BehaviorSubject";

@BaseComponent({
  moduleId: module.id,
  selector: 'sd-blank',
  providers: [NamesService],
  templateUrl: 'blank.component.html',
  styleUrls: ['blank.component.css']
})
export class BlankComponent implements OnInit {
  public results$: BehaviorSubject<Array<any>> = new BehaviorSubject([]);
  subscriber:any;

  constructor(private namesService:NamesService) {

    this.subscriber = Observable.interval(1000)
      .flatMap(() => this.namesService.GetNames())
      .subscribe((results) => {
        this.results$.next([...results]);
      });

  }

  ngOnInit(){ }

  ngOnDestroy() {
    this.subscriber.unsubscribe();
  }

}
```

blank.component.html:

```
<div *ngFor="let name of results$ | async">
  {{name}}
</div>
```

Please close if fixes for you.

**Comment by jovermier** [comment]
That works under some circumstances. If the blank component is using the top level app routing it works. If there is nested routing then it requires you to navigate away then return to the component for it to start displaying the values. Example:

Routing:

--Home (url /)
--Blank (url /blank) <- WORKS, EVEN WHEN RELOADING THE PAGE
--Sensors (url /sensors/)
-----Blank (url /sensors/blank) <- DOES NOT WORK FIRST TIME NAVIGATED TO PAGE OR IF YOU RELOAD THE PAGE
-----Another Page (url /sensors/page)

Now if I were to add "changeDetection: ChangeDetectionStrategy.Default" on the sensors component which is a RouteComponent it will properly update the DOM when displaying /sensors/blank even if the page is reloaded.

**Comment by NathanWalker** [comment]
This could be related to deprecated router. The seed will be updated to v3 router in next couple weeks and it's possible that may fix the issue you describe above. I'll keep this open until that time.

**Comment by NathanWalker** [comment]
@jovermier latest master uses the new router now and I would be curious to hear if you could update (merge latest upstream in) and try your issue again. Let me know if it clears for you and please close this issue if so.

**Comment by NathanWalker** [comment]
closing due to nonresponse.
