### ISSUE TITLE
Adding depency but remove it from system-builder

### ISSUE THREAD

**Issue by haukka** [NathanWalker/angular-seed-advanced#135]

**Comment by NathanWalker** [comment]
Hi @haukka if you could provide a little more details here would help. Which lib are you trying to integrate? You can modify the systemjs-builder in your own `project.config.ts` file and use this as a guide on how to do that for various libs: https://github.com/NathanWalker/angular2-seed-advanced/blob/master/tools/config/seed-advanced.config.ts#L63-L69

Please close if this is no longer an issue for you or if the above gets you going in the right direction 👍

**Comment by haukka** [comment]
Hi @NathanWalker,
I was trying to add wijmo(http://wijmo.com/) to the angular-seed-advanced just for trying, understand the core system of your seed and have a basic boilerplate but also to learn angular2 by practicing.
You can find the test I made here : https://github.com/haukka/angular2_seed_advanced_wijmo_ng2-admin_bootstrap  (I let the repertory node_modules because I put a wijmo repertory into it and it is necessary in order to launch wijmo).
I tried to modify the systemjs-builder in the project.config.ts file but the dev part is working and the prod part is making a lot of errors due to this implementation.
Thank you in advance.

**Comment by NathanWalker** [comment]
@haukka I'm going to close this since wijmo likely has there own package structure but you would want to find others who have integrated it with systemjs and apply those same principles here.
Also try with latest seed since some good fixes have gone in since the time you experimented.
