### ISSUE TITLE
Generator for this Seed-Advanced (Proposal)

### ISSUE THREAD

**Issue by jvitor83** [NathanWalker/angular-seed-advanced#137]
What about a (CLI) yeoman generator based on this seed-advanced?

I think about a proposal with something like:

> **new project**
1. Input your project's name
2. Input the necessary tecnology (web and/or electron and/or nativescript/reactnative and/or ionic2/cordova and/or angular universal...)
3. Some libs included (bootstrap or material or jquery)
4. Configurations (sass or less)
5. Authentication (oauth2 or openid connect)?

_Another commands:_

> **new component** 
> **new router** 
> **new service** 

_Btw, i think this will be only possible when the refactoring ( [https://github.com/mgechev/angular2-seed/pull/959](https://github.com/mgechev/angular2-seed/pull/959) ) is done and get here._

I think that to get there we will need another repository with a fork from this one, that where the template will be, and another one where the generator itself will be hosted.
- Generator Template Repository (seed-advanced fork customized like templates)
- Generator Repository (where will be the generator code itself)

And to make possible to the generator repository use the template repository we could use git's submodule. That will make it easier to keep the generator up to date to the seed (by merging).

Any thoughts?

**Comment by joshwiens** [comment]
I would think with the CLI coming, the best plan here is to wait which is what was decided in the parent seed in regards to the same topic.

Also, unless someone picks up the refactoring, it's not going to happen. Nathan & I spent a weekend on the decoupling and decided the added complexity ( and systemjs annoyances ) to make it happen simply wasn't worth the marginal benefits of decoupling the app from the tools.

**Comment by NathanWalker** [comment]
I'm going to loop in Victor Sosa @peoplewareDo who just created yeoman generators for some of my other seed projects. I would be curious to hear your thoughts here Victor?

@d3viant0ne  Regardless of where the CLI is going, it wouldn't provide specifics for this seed so this may still be valuable to explore.

**Comment by joshwiens** [comment]
@nathanwalker I was thinking about the wrong feature, It was the offline comp. that was "blocking" the generator when I brought it up in the parent seed a few months back. I'll see if I can dig up the original issue.

**Comment by joshwiens** [comment]
The original issue was created after looking at AngularClass's es6 starter that has a slick generator

**Comment by NathanWalker** [comment]
@victorsosa Do you have any spare cycles to potentially consider including a generator for this seed in addition to the others that you recently created (which are awesome btw)?

**Comment by victorsosa** [comment]
@NathanWalker Yes, I will start working on it.
@jvitor83 nice spec description, I will try to do the requirements. You can check https://github.com/peoplewareDo/generator-nativescript-plugin in the meantime. I let me know anything else. We already have the Yeoman generator for plugin ;)

**Comment by victorsosa** [comment]
@NathanWalker I will have to create a new generator for this, because the orginal generator-nativescript-plugin was intent for create nativescript plugins and this project is not a plugin. Also I think I need to wait for the refactor too, right? the one that you mention earlier in this issue.

**Comment by NathanWalker** [comment]
@victorsosa awesome thank you! The refactor is actually complete now so things are ready 👍

**Comment by victorsosa** [comment]
Need a little help, yeoman generator based on this seed-advanced will have some questions,
this three are the base of this project:

is web app <- false - will omit the file main.web.ts 
is electron <- false - will omit the file main.desktop.ts
is nativescript <- false - the generator will omit the nativescript folder 

The boolean value will set or unset the folder or files, please confirm that those are the correct files or folders; Is that enough? or should we consider other changes?

Another question is which project will be the default one; because the user shouldn't be able to say no to every platform, should be one platform by default like NativeScript or Electron.

**Comment by NathanWalker** [comment]
Yes above is all correct. Web should always be the default so if no to web, and no to others, it would default to create a web only setup. Thanks again for this 👍

**Comment by victorsosa** [comment]
great, so the web is the only one by default. The others are optional.

**Comment by victorsosa** [comment]
Task 3: Some libs included <- are those libraries optional or required? also those libs are going to be included using npm, right?

**Comment by NathanWalker** [comment]
@victorsosa RE: Task 3 - You could provide an _option_ to install those with the seed but it's not required. Most 3rd party lib integration outside of whats provided here out of the box should probably be left to user to integrate. Always use npm, yes.

**Comment by victorsosa** [comment]
@NathanWalker Please check out https://github.com/peoplewareDo/generator-ng2-seed-advanced and let me know; still under development.

**Comment by victorsosa** [comment]
I am working in the task 4: Sass or less, using the info in https://github.com/NathanWalker/angular2-seed-advanced/issues/182.

**Comment by NathanWalker** [comment]
Thanks @victorsosa no rush, a generator is certainly a luxurious thing and your starting generator is looking awesome; your work is excellent. 👍

**Comment by victorsosa** [comment]
@NathanWalker  Addition of simple component, router, and service subgenerators; Now it create those using subgenerators

**Comment by victorsosa** [comment]
Only this tasks need to be done:
3.Some libs included (bootstrap or material or jquery)
4.Configurations (sass or less)
5.Authentication (oauth2 or openid connect)?

**Comment by NathanWalker** [comment]
@victorsosa thank you so much for all your effort, really excellent work. I have added a link to your amazing generator on the Wiki here: https://github.com/NathanWalker/angular-seed-advanced/wiki

**Comment by victorsosa** [comment]
@NathanWalker you welcome
