### ISSUE TITLE
Using ngrx/router

### ISSUE THREAD

**Issue by zeeshanjan82** [NathanWalker/angular-seed-advanced#138]
Any reasons the seed uses angular2 router instead of ngrx/router even though it uses ngrx/store. I was trying to replace angular2 router with ngrx/router but got some issue with missing provider for Analytics Service. Would you recommend using angular2 router instead of ngrx/router for any new project which is build on top of this seed. Also ngrx/router provides some cool features like guards is there any replace for that in angular2 router.

**Comment by spicemix** [comment]
It's still up in the air whether NG2/Router 3.0 is going to fully replace ngrx/router...

ngrx/router#147

**Comment by NathanWalker** [comment]
Thanks @zeeshanjan82 and @spicemix indeed we will stick with ng2 router here since it is shaping up and will eventually replace ngrx/router.

I'm having a good experience so far with ng2 new v3 router that's in the seed.
