### ISSUE TITLE
Question about "Best to use"

### ISSUE THREAD

**Issue by andresguibarra** [NathanWalker/angular-seed-advanced#139]
Hi!

First, sorry if it's not the place to post a question but I didn't find the correct one.

In the section "How best to use for your project" says: 
1. Create a new framework for your application in src/client/app/frameworks to build your codebase out. Say your app is called AwesomeApp, then create awesomeapp.framework and start building out all your components and services in there. Create other frameworks as you see fit to organize.

I did all the steps until this one. I don't know how to start my project based on the framework I added.

Regards

**Comment by NathanWalker** [comment]
Hi @yanqui92 fair question. The `How best to use` guideline is really just a suggested guideline so you are free to do whatever suits your project, but if using the suggestion for instance you could have:

`src/client/app/frameworks/awesomeapp.framework/index.ts` which would export all your components and services like so:

```
// components
export * from './components/home/home.component';
export * from './components/contact/contact.component';

// services
export * from './services/awesome.service';
// etc.
```

Then your other files can reference that. So for example, your `src/client/main.web.ts` file could bootstrap your home component (for instance) like so:

```
import {HomeComponent} from './app/frameworks/awesomeapp.framework/';
...
bootstrap(HomeComponent, BOOTSTRAP_PROVIDERS)
.catch((err:any) => console.error(err));
```

And using services would work much the same way throughout your project. That answer things for you?
