### ISSUE TITLE
Changing name of seed project

### ISSUE THREAD

**Issue by st-clair-clarke** [NathanWalker/angular-seed-advanced#14]
In 'How best to use for your project' I see 'Create a new framework for your application in src/frameworks to build your codebase out. Say your app is called AwesomeApp, then create awesomeapp.framework and start building out all your components and services in there. Create other frameworks as you see fit to organize.'

The name of this project is 'angular2-seed-advanced'.How do I change the name of the project to AwesomeApp and still retain the ability to update from your repo when future changes are made. Is there a special way to do this? Or I should just use the name of AwesomeApp in the framework identification?
I use Webstorm for my app development. Is there anything I have do do in Webstorm to allow it to compile the .ts files to the build.dev directory etc.

Thanks

**Comment by NathanWalker** [comment]
Hi @st-clair-clarke thanks for your question.
- You can rename the folder that you downloaded of the zip of the seed to your project
- Change to your project name here: https://github.com/NathanWalker/angular2-seed-advanced/blob/master/package.json#L2
- Change to your project desc here: https://github.com/NathanWalker/angular2-seed-advanced/blob/master/package.json#L4
- Change to your project repo here: https://github.com/NathanWalker/angular2-seed-advanced/blob/master/package.json#L6
- Change this to you: https://github.com/NathanWalker/angular2-seed-advanced/blob/master/package.json#L32-L37
- Change to you: https://github.com/NathanWalker/angular2-seed-advanced/blob/master/LICENSE#L3-L4
- Change to your repo: https://github.com/NathanWalker/angular2-seed-advanced/blob/master/.travis.yml#L16
- Change to your token: https://github.com/NathanWalker/angular2-seed-advanced/blob/master/.travis.yml#L29
- Change to your token (appveyor): https://github.com/NathanWalker/angular2-seed-advanced/blob/master/appveyor.yml#L13
- Change `README` completely.

Those are the main changes. Then build out your `AwesomeApp.framework` in `frameworks`.

Then when merging upstream updates:

```
git fetch upstream
git merge upstream/master
```

Then resolve conflicts. Given those changes they will be farely minimal. You will always have a conflict with `README` (just replace with your readme everytime to resolve conflict). And generally will have conflicts in `package.json` but they should be easy to resolve.

Regarding `Webstorm` and compiling .ts files. This seed uses the build from it's parent https://github.com/mgechev/angular2-seed, you might ask that question there. Or rather, it's webstorm specific, maybe on their IDE forum?

Cheers!
