### ISSUE TITLE
Does the UI need to be in Html or NativeScript syntax

### ISSUE THREAD

**Issue by OscarAgreda** [NathanWalker/angular-seed-advanced#142]
I spent the weekend learning some more angular 2, typescript and NativeScript, I especially liked this course:
[https://app.pluralsight.com/library/courses/nativescript-cross-platform-native-mobile-apps/table-of-contents](https://app.pluralsight.com/library/courses/nativescript-cross-platform-native-mobile-apps/table-of-contents)
after watching the course as an ex-Silverlight developer, i quickly realized how easy and fast (very important in software development) will be to get me and my team into NativeScript .

I also came to the conclusion that we definitely need 2 different UI Layouts, one for the NativeScript and another one for the web app. So the web does not sacrifice anything for NativeScript and vice-versa.

This presentation from TJ VanToll, gave me some light 
[https://www.youtube.com/watch?v=Y2F5cHQuaIc](https://www.youtube.com/watch?v=Y2F5cHQuaIc)

nevertheless NativeScript magic is the answer
[https://www.youtube.com/watch?v=T2wAb6UX8zo](https://www.youtube.com/watch?v=T2wAb6UX8zo)

@NathanWalker you are definitely brilliant, by the way.

Now I see a clear path emerging:
for the Web UI is to implement Material Design 2 [https://github.com/angular/material2](https://github.com/angular/material2)
and User Interface Widgets for NativeScript [https://docs.nativescript.org/ui/ui-views](https://docs.nativescript.org/ui/ui-views)

I think the Advanced Angular Seed shout start with angular magic. 
instead of having the html pages, i think we should have 3 in html and 3 for native script , since day zero.

**Comment by NathanWalker** [comment]
@OscarAgreda Thanks again. 

I'm not sure I follow what you mean by: " i think we should have 3 in html and 3 for native script"?

Right now, there's an html file for each component (ie, here: https://github.com/NathanWalker/angular2-seed-advanced/blob/master/src/client/app/components/app/app.component.html)
And a `.tns.html` for each component (ie here: https://github.com/NathanWalker/angular2-seed-advanced/blob/master/src/client/app/components/app/app.component.tns.html)

**Comment by OscarAgreda** [comment]
right, yes.  we have that .   sorry i wasn't clear on my question  :(

1- you have something there similar to NativeScript magic that does the Template Switching (templateUrl and styleUrls)

2-does the seed also has something that helps with the routing  switching , i see the files, could you explain how that is accomplished . because as one app becomes big , is very important to have a clear path about the  routing mechanism. :)

*by switching i mean that the app will sense if it is running on the web or natively on a device .

but, then i was thinking about it,  
and you don't think the idea of creating 2 views (one for NativeScript and one for the web) could turn off some users ? . We ll know that maintaining 2 different things (ui, mvvm, service) that do the same is very difficult on the long run.

 with NativeScript the native APIs are available out of the box that is a lot of power on our hands. no need to use Andoid Studio or Xcode. that is so awesome. will be nice just to create one view in Native Script and translate or render html code from it .

or, we could go the other way, somehow the web Html5 views gets translated into NativeScript view .. the advantage of this is that we could use Angular Material Design 2 and lots of CSS (like one called Fuse for example) to quickly create a beautiful app.

that is why i was wondering what will be the best possible option to avoid creating 2 different Layouts views and only have one , kind of getting closer to only have just one codebase even for the ui. I know there will be sacrifices one way or another. from my perspective i think is better to let NativeScript win and the have the web view to come out of NativeScript .

**Comment by NathanWalker** [comment]
At the moment having 2 files is the best way to go (1 for web, 1 for nativescript). There is some exploratory work taking place here: https://github.com/NathanWalker/nativescript-angular-web-components ....that may pave a path to get to what you are referring to above.
