### ISSUE TITLE
When adding component manually and making changes, the component breaks until I call npm start again.

### ISSUE THREAD

**Issue by Bohmaster** [NathanWalker/angular-seed-advanced#144]
First of all, thank you very much for building this repository. It's great to get up running quickly.

I wanted to add a new component (say Adverts) and I've copied the same structure of the others components(app, home, about) but only with the ts, html, tns.html and css files

When I run "npm start" it's all working just fine. Until I make a change inside the adverts folder (app/components/adverts). Then I get this error after livereload has detected file changes.

`platform-browser.umd.js:2311 EXCEPTION: Error: Uncaught (in promise): Error: Cannot match any routes: 'adverts'`

If I shutdown the server and start it again with "npm start" the changes I've made take effect until the next change. If I make a change in the default components folder (like home.component.ts) livereload works fine and no error is thrown.

So I suppose it has to be something related to how I added my new custom component.

Is there a specific way of adding new components? All the extra files in default components like "spec" and "js.map" were added manually? Do I need to explicity
tell somewhere about my component to see my changes in runtime?

Cheers, from Argentina.

**Comment by vyakymenko** [comment]
@Bohmaster , error in your routes. Your file don't have dependencies with 'router'. Look in your routes.
It's not a seed issue.

**Comment by igonzalezespi** [comment]
I have similar errors.
Do you have the compiled `.js` and `.js.map` in the same directory as de `.ts` one?
If so, delete it and run `npm start` again. Now the changes work fine for me.
`npm start` should take the /dist/dev directory, but maybe is it taking the compiled one in the project directory after livereload and not after `npm start`?

**Comment by Bohmaster** [comment]
@vyakymenko My routes are fine because they work great (all it's working fine). It break only when I make a change in some of the files in my custom component folder (adverts). If I run npm start again after the change, it works fine again. 

@ivannugo In my component folder I have this (added manually):

app/components/adverts

```
> adverts.component.ts
> adverts.routes.ts
> adverts.component.html
> adverts.component.tns.html
> adverts.component.css

```

The defaults components (such as 'home') has some test-spec and  .js.map files that I don't know where are they coming from (were they added manually? or with some kind of command?).

I only have trouble when I change some file in my custom component folder while npm start watches for changes. If I change some file in the default components folder (like app, home, about) nothing breaks, so I think it has to do with my custom component (adverts).

It's really painful to restart the server every time I make a change.

**Comment by joshwiens** [comment]
@Bohmaster - In this particular case, if it's public link the repo.

If it's private, do us a favor and create a fork ( or just push master into a new repo ) and add the **minimal custom code to reproduce the issue you are having**.

I'm happy to take a look at it but trying to run down whatever this is be it a router issue, advanced-seed issue or lord knows what else without having code we can dig into locally isn't going to be a viable option.

**Comment by Bohmaster** [comment]
@d3viant0ne Of course. I've uploaded my repo.

Here is the custom 'adverts' component:

https://github.com/Bohmaster/angular2-nativescript-redux/tree/master/src/client/app/components/adverts

If I run 'npm start' it works perfectly. Until I make a change in some of these files (only in this component, if I make a change in the default repo components it doesn't break)

Thanks again!

**Comment by Bohmaster** [comment]
@d3viant0ne @NathanWalker any clues? It's all working great but I have to run "npm start" for every single change. It should be something very simple. But I'm new to Angular2-Nativescript-Typescript!

**Comment by vyakymenko** [comment]
@Bohmaster , I will try to look for your code today.

**Comment by Bohmaster** [comment]
@vyakymenko Thank you very much! I've added just one extra component based in the structure of the others.

**Comment by Bohmaster** [comment]
Fixed! I've reinstalled everything from ground up and now It work's great!
