### ISSUE TITLE
LangSwitcherComponent  - i18n bug language switch does not work immediately [Seed Issue]

### ISSUE THREAD

**Issue by Goldflow** [NathanWalker/angular-seed-advanced#145]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_
1. Select another language in the language component. (e.g. spanish)
2. Observe no changes
3. Select again another language in the language component
4. Change back to the first language you changed to (e.g. spanish)
5. Observe now translation is applied

**Current behavior**

does not change language immediately (though it updated in the state) - however after selecting another language & the preferred language again, the language is changed

**Expected/desired behavior**

when selecting other language: updated the language immediately

**Other information**

this is in the blanco, unmodified Angular2 Seed Advanced repository

**Comment by Goldflow** [comment]
related to this apparently: https://github.com/NathanWalker/angular2-seed-advanced/pull/141

**Comment by NathanWalker** [comment]
Just pushed up a nice workaround for this... working on master now 👍
