### ISSUE TITLE
Can't install @ngrx/devtools

### ISSUE THREAD

**Issue by Bohmaster** [NathanWalker/angular-seed-advanced#146]
Command:

> npm install @ngrx/devtools --save-dev

Result:

```
├── UNMET PEER DEPENDENCY @angular/common@2.0.0-rc.3
├── UNMET PEER DEPENDENCY @angular/compiler@2.0.0-rc.3
├── UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.3
├── UNMET PEER DEPENDENCY @angular/http@2.0.0-rc.3
├── @ngrx/devtools@1.4.0 
└── UNMET PEER DEPENDENCY @ngrx/store@2.0.1

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN optional Skipping failed optional dependency /gulp-watch/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN ng2-translate@2.1.0 requires a peer of @angular/common@2.0.0-rc.1 but none was installed.
npm WARN ng2-translate@2.1.0 requires a peer of @angular/compiler@2.0.0-rc.1 but none was installed.
npm WARN ng2-translate@2.1.0 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
npm WARN ng2-translate@2.1.0 requires a peer of @angular/http@2.0.0-rc.1 but none was installed.
npm WARN @ngrx/devtools@1.4.0 requires a peer of @ngrx/store@^1.5.0 but none was installed.
```

**Comment by NathanWalker** [comment]
I believe this is normal. It should have actually installed it still no?

**Comment by pocmanu** [comment]
On their github, they say that devtools are not yet compatible with ngrx/store v2.0, which is the version used in the project. Maybe is there a link ?

**Comment by NathanWalker** [comment]
Ah I see, yes I believe you could link against Mike's github repo which contains the refactor to work with v2: https://github.com/mikeryan52/devtools/tree/v2

**Comment by joshwiens** [comment]
@pocmanu I use Mike's version via github personally and it works. Give me a shout here on on slack if you have trouble with it.

**Comment by Bohmaster** [comment]
Should I clone https://github.com/MikeRyan52/devtools.git directly and do npm install after it? Or do I need to put some git flag to access /tree/v2?

**Comment by pocmanu** [comment]
@d3viant0ne I'm still just playing with the seed right now, trying to learn ngrx & redux, I don't really need the devtools right now, I don't have much time to dev, but thanks for the help offer (and all the great work you're doing all :))

**Comment by NathanWalker** [comment]
https://github.com/ngrx/store-devtools are now updated 👍  and you can use them via npm.
