### ISSUE TITLE
import 'application-settings' error

### ISSUE THREAD

**Issue by Bohmaster** [NathanWalker/angular-seed-advanced#147]
I'm trying to store authentication data in the storage:

```
import {Injectable} from '@angular/core';
import {Http, Response} from '@angular/http'
import {Observable} from 'rxjs/Observable';
import {HttpService} from '../../core.framework/index'

import {Store, ActionReducer, Action} from '@ngrx/store';

import * as applicationSettings from 'application-settings'
```

Component logic:

```
@Injectable()
export class AuthService {
  constructor(private store: Store<any>,
              private http: HttpService) {
    console.log('STORAGE', applicationSettings);                
  }  

  login(credentials: any) : void {
    this.http.post('http://104.131.113.114:3004/api/usuarios/login', credentials)
      .subscribe((results: any) => {
        console.log('user service', results);
        this.store.dispatch({
            type: AUTH_ACTIONS.LOGIN,
            payload: results
        });

        applicationSettings.setString('userId', results.userId);
        applicationSettings.setString('token', results.id)

      });
  }

}

```

I'm getting this error:

> http://localhost:5555/node_modules/application-settings/package.json Failed to load resource: the server responded with a status of 404 (Not Found)
> localhost/:123 Error: Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/application-settings/package.json(…) "Report this error at https://github.com/NathanWalker/angular2-seed-advanced/issues"(anonymous function) @ localhost/:123
> http://localhost:5555/node_modules/application-settings/package.json Failed to load resource: the server responded with a status of 404 (Not Found)

I'm calling it correctly? Or the path is wrong? I couldn't find any example but requiring it like this.

**Comment by Bohmaster** [comment]
I've found the 'application-settings' module inside nativescript/node_modules folder. 

In the package.json is this:

```
{
    "name" : "application-settings",
    "main" : "application-settings.js",
    "nativescript": {}
}
```

But there is no "application-settings.js" file inside the folder.

There is "application-settings.ios/android.js" and "application-settings-common.js" that I suspect is the one I'm looking for.

**Comment by m-abs** [comment]
"application-settings" is for nativescript-only, it's sort of their version of localStorage.

You need to create your own storage-service that wraps localStorage on web and application-settings on nativescript.

We're using angular2-localstorage and have wrapped application-settings to provide the localStorage-api on nativescript.
See: https://github.com/marcj/angular2-localstorage/issues/48

**Comment by NathanWalker** [comment]
Thanks for helping answer @m-abs, yes @Bohmaster you would want to do something similar.
