### ISSUE TITLE
start.livesync.android "Unable to sync files. Error is: EISDIR: illegal operation on a directory, read"

### ISSUE THREAD

**Issue by Bohmaster** [NathanWalker/angular-seed-advanced#148]
Now that I've managed to fix livereload sync in the webside,  I get this error everytime I make a change in android environment. When the emulator is running (npm run start.livesync.android) it works just fine, but when some file has changed, I get this error:

> "Unable to sync files. Error is: EISDIR: illegal operation on a directory, read"

The changes are mirrored both in "/dist" and "/assets/app" (android platform) folders.

I've tried genymotion and Android Studio VDM's and I have had the same problem.

I could run --log trace for more details.

REPOSITORY:
https://github.com/Bohmaster/nativescript-ng2

**Comment by m-abs** [comment]
I'm having the same issue, but it looks like a known bug in nativescript-cli:
https://github.com/NativeScript/nativescript-cli/issues/1810

**Comment by Bohmaster** [comment]
@m-abs I looked at it but it was closed and didn't see any clear solution. I hope we find one soon because is the only cause why I'm blocked from developing with nativescript and angular2.

Do you know any workaround to develop to android until this is resolved?

**Comment by m-abs** [comment]
The only workaround I've is to run "npm run start.livesync.android" manually after each change.
It works okay fast, but not as fast as it would have been if livesync had worked.

**Comment by Bohmaster** [comment]
@m-abs Do you know can I get full description of my console.logs to access object properties running the emulator?

**Comment by Bohmaster** [comment]
I've cleaned the repository and noticed that it only breaks when I change a ".ts" file. If I change htm/tns.html it works fine until I touch some ".ts" files. After that even "tns.html" files break.

I noticed that when I edit ".ts" files the build/refresh cycle runs twice.

So to be clear:

1) After a fresh reinstall all works fine if I change .html or .tns.hmtl files
2) If a change a ".ts" file I get the EISDIR error
3) If a change again some ".tns.html" file I get the ESIDIR error too

@NathanWalker is this a repository bug or more related to nativescript-cli?

**Comment by m-abs** [comment]
If you want the properties on an object, you could use Object.keys(varname1), but it'll only give you the objects own enumerable properties, not functions on the prototype/class.

I noticed the same thing with .ts-files, updating nativescript/app/app.css also doesn't work for me but tns.html does.
I'm pretty sure it's a problem with the way nativescript and typescript-integration handles livesync and not something to do with the seed-project.

**Comment by Bohmaster** [comment]
What I'll try is to run both web and mobile server to log in the browser my ts's "console.log()" so I can get full access to objects while running android at the same time.

I hope we get some insight soon about the livesync. I have an old computer and the build time in comparison to the livesync is enormous.

**Comment by m-abs** [comment]
> What I'll try is to run both web and mobile server to log in the browser my ts's "console.log()" so I can get full access to objects while running android at the same time.

Are you looking for a way to debug nativescript interactively? See: https://docs.nativescript.org/runtimes/android/debug/debug-cli#detach-the-debugger

> I hope we get some insight soon about the livesync. I have an old computer and the build time in comparison to the livesync is enormous.
> Can't you just run start.livesync.android manually after each change? It's what I do and it works fine for me.
> It will update your app on the phone but it's not a full build, so it should be pretty quick.

**Comment by Bohmaster** [comment]
I'll take a look at the debugger. Thanks!

> Can't you just run start.livesync.android manually after each change? It's what I do and it works fine for me.
> It will update your app on the phone but it's not a full build, so it should be pretty quick.

When you say "phone" do you mean physical or virtual?

**Comment by m-abs** [comment]
> When you say "phone" do you mean physical or virtual?

Virtual, but I don't think it make much of a difference.

**Comment by Bohmaster** [comment]
It takes about 20 seconds at least. Is it normal? Or my PC is very old?

q9650 @3.0ghz
DDR2 4gb 800mhz
SSD 240gb

**Comment by m-abs** [comment]
I think it's about the same for me. A full build\* takes 5+ minutes, so 20 seconds isn't too bad.

I know it isn't perfect, but even if livesync worked right you wouldn't be instantaneous sync. 
If I just update a tns.html it still takes about 5-10 seconds to reload the app with the changes on my setup.

*) By full build I mean from scratch, if the app hasn't been built and deployed to the phone/emulator before

**Comment by Bohmaster** [comment]
I'm very used to instant change reflection in the browser. I think I'll
need to get used to this until we get a response from nativescript.

Are you new to Angular2/Typescript/NativesSCript/Redux?

2016-07-02 19:41 GMT-03:00 Morten Sjøgren notifications@github.com:

> I think it's about the same for me. A full build takes 5+ minutes, so 20
> seconds isn't too bad.
> 
> I know it isn't perfect, but even if livesync worked right you wouldn't be
> instantaneous sync.
> If I just update a tns.html it still takes about 5-10 seconds to reload
> the app with the changes on my setup.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/NathanWalker/angular2-seed-advanced/issues/148#issuecomment-230125480,
> or mute the thread
> https://github.com/notifications/unsubscribe/AI1ZyWK1NtqZ-4ltJsEhPuLPna1ou_K8ks5qRukVgaJpZM4JDnqh
> .

## 

La capacidad para pensar diferente es más importante que la información
obtenida.

**Comment by m-abs** [comment]
> I'm very used to instant change reflection in the browser. I think I'll need to get used to this until we get a response from nativescript.

Yeah, me too. I can work with the way it is right now, but I'd love for it to be better.
I hope the new release of nativescript solves the problem, but we haven't had time to upgrade yet.

> Are you new to Angular2/Typescript/NativesSCript/Redux?

Yes, I am new to all of them
But I've been working with JavaScript for years and started using ES6-features as soon as I could in NodeJS, upgraded to typescript in the spring.
I've some experience in Angular 1.x but almost non in mobile development.
You?

**Comment by Bohmaster** [comment]
New to all. I'm from Argentina (24 years old) and I have not had finished highschool. I've learned all by my self and I don't have much work experience. 

I've used Angular 1, and Loopback(strongloop) for a year now (Before that I've played with php, python) and I'm really interested in Angular 2(with redux), typescript, nativescript and Reactive programming with Loopback (with ES6) in the backend.

If you like we could share some code to build and learn together!

**Comment by Bohmaster** [comment]
I leave here all the process with --log trace.

[log.txt](https://github.com/NathanWalker/angular2-seed-advanced/files/344920/log.txt)

I've noticed this:

```
Project successfully prepared
AfterHookName for command prepare is after-prepare
spawn: C:\Users\voidhmaster\AppData\Local\Android\android-sdk\platform-tools\adb "-s" "192.168.155.101:5555" "shell" "ls" "-l" "/data/local/tmp"
Result when throw error is false:
{ stdout: 'drwxrwxrwx root     root              2016-07-03 02:29 com.yourdomain.appname\r\r\n',
  stderr: '',
  exitCode: 0 }
spawn: C:\Users\voidhmaster\AppData\Local\Android\android-sdk\platform-tools\adb "-s" "192.168.155.101:5555" "shell" "rm" "-rf" "/data/local/tmp/com.yourdomain.appname/fullsync" "/data/local/tmp/com.yourdomain.appname/sync" "/data/local/tmp/com.yourdomain.appname/removedsync"
Result when throw error is false:
{ stdout: '', stderr: '', exitCode: 0 }
```

I get this a lot of times just before I get the EISDIR error

**Comment by Bohmaster** [comment]
@jwuliger

**Comment by Bohmaster** [comment]
I've created this https://github.com/NativeScript/nativescript-cli/issues/1900 in the official nativescript-cli issue board.

**Comment by m-abs** [comment]
@NathanWalker 
I noticed on my machine that "tns livesync android --watch --log trace" failed on this:

``` bash
spawn: /home/mabs/tools/android/android-sdk-linux/platform-tools/adb "-s" "emulator-5554" "shell" "chmod" "0777" "/data/local/tmp/dk.nota.lyt3/sync/assets"
Result when throw error is false:
{ stdout: 'chmod: /data/local/tmp/dk.nota.lyt3/sync/assets: No such file or directory\r\n',
  stderr: '',
  exitCode: 0 }
Unable to sync files. Error is: EISDIR: illegal operation on a directory, read
```

"nativescript/app/assets" and "nativescript/app/app" are both symlinks, so I tried to mount-bind them instead of using symlinks, that seems to have solved the problem.

I'm using Linux, so I doubt this workaround will help @Bohmaster on his Windows PC.

**Comment by Bohmaster** [comment]
@m-abs I'm going to install ubuntu in a partition. 

Can you explain me in detail what "mount-bind" is and how to do it?

Great news!

**Comment by m-abs** [comment]
@Bohmaster
Mount-bind\* mounts a folder on top of another folder. It has the advantage over symlinks that it will be treated as a real folder, the disadvantage is that it requires root and isn't persistent.

This is what I did**:

``` bash
cd path/to/project
rmdir -v nativescript/app/app nativescript/app/assets
sudo mount -o bind src/client/app  nativescript/app/app
sudo mount -o bind src/client/assets nativescript/app/assets
```

You'll have to run the two mount commands after reboot, unlike a symlink mounts like these won't survive reboot.

_) I call it mount-bind because of the "-o bind"-option to the mount command
*_) Minor update it's rmdir not rm as I wrote originally

**Comment by Bohmaster** [comment]
I've followed those steps and I'm getting this:

> Unable to sync files. Error is: ENOENT: no such file or directory, stat '/home/voidhmaster/Desktop/angular2-seed-advanced/nativescript/platforms/android/src/main/assets/app/app/components/about/about.component.js.map'

I've noticed that there is no ".js.map" files in the "android/src/assets/app" folders. Do I need to mount this folder to? 

@m-abs

**Comment by Bohmaster** [comment]
@m-abs Did you see this? https://github.com/NathanWalker/angular2-seed-advanced/issues/148#issuecomment-230359934

**Comment by m-abs** [comment]
Sorry, I thought I had replied earlier today,

No, you shouldn't mount that path. Everything under `platform` is where nativescript builds your project to put on devices/emulators.

I don't know why yours complain about missing js.map-files, I don't see that here.

**Comment by Bohmaster** [comment]
I'll try to install everything from scratch!

Is everything working fine now in your environment?

2016-07-06 20:07 GMT-03:00 Morten Sjøgren notifications@github.com:

> Sorry, I thought I had replied earlier today,
> 
> No, you shouldn't mount that path. Everything under platform is where
> nativescript builds your project to put on devices/emulators.
> 
> I don't know why yours complain about missing js.map-files, I don't see
> that here.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/NathanWalker/angular2-seed-advanced/issues/148#issuecomment-230934216,
> or mute the thread
> https://github.com/notifications/unsubscribe/AI1ZyeUIaVu9qvLkiyCoK4DEhSYw0PXvks5qTDU9gaJpZM4JDnqh
> .

## 

La capacidad para pensar diferente es más importante que la información
obtenida.

**Comment by NathanWalker** [comment]
Closing as this is related to {N} runtime issue which is being tracked: https://github.com/NativeScript/nativescript-cli/issues/1900
