### ISSUE TITLE
Symbolic link is not present after clone>npm install. 

### ISSUE THREAD

**Issue by Bohmaster** [NathanWalker/angular-seed-advanced#150]
I have to make the symlink manually. I don't know if this could bring any trouble.

I have two clones. One with the symlink (manually) and other recently cloned without it. If I run "npm run start.livesync.android" inside the folder of the new cloned repo, in the emulator the app showing is the one I have in another folder.

**Comment by m-abs** [comment]
Have you updated the nativescript.id in nativescript/package.json?

**Comment by Bohmaster** [comment]
It says "com.yourdomain.appname". What should it say?

**Comment by m-abs** [comment]
Think it as a domain name written from behind.
Our app is called LYT3 (translates to "Listen 3") and the company we work for is called Nota and we're in Denmark (nota.dk), so our app-id is dk.nota.lyt3

**Comment by NathanWalker** [comment]
Closing due to non-standard usage.
