### ISSUE TITLE
How do I set actionBarHidden?

### ISSUE THREAD

**Issue by m-abs** [NathanWalker/angular-seed-advanced#155]
With NativeScript we can hide the ActionBar with the page-attribute actionBarHidden=true, in nativescript-angular we have to use:

``` typescript
import {Page} from "ui/page";

@Component({
// ...
})
class MyComponent {
  constructor(page: Page) {
    page.actionBarHidden = true;
  }
}
```

But that won't work on web or electron, since we won't be able to import "ui/page" from nativescript on web.
What's the best way to do this?

**Comment by NathanWalker** [comment]
There's actually a custom root component for the {N} app here:
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/nativescript/app/pages/app/app.component.ts

You can inject `Page` there.

There's some other ways you could go if you need to inject `Page` in other components or other services: a) use an `OpaqueToken` which could be provided for in either platform, using `ui/page` for {N} app, and an empty object for web, b) use a service would could also be provided for in both platforms.

Angular 2 provides a multitude of ways to handle this sort of thing :)

**Comment by m-abs** [comment]
Thanks for you reply.
I think I need to use a service, since the nativescript-angular router injects the Page-object.

**Comment by m-abs** [comment]
I've just added a PR for this: https://github.com/NathanWalker/angular2-seed-advanced/pull/247
