### ISSUE TITLE
Data storage for login/token information

### ISSUE THREAD

**Issue by getmetorajesh** [NathanWalker/angular-seed-advanced#156]
In the current seed there doesn't seem any way to store data? I tried using cookies(`angular2-cookie`) for web and `application-settings` for mobile, but it seems like it can't co-exist(imported) in the same component. 

eg:

```
var appSettings = require('application-settings');
var cookieService = require('angular2-cookie/core');
```

Since Typescript doesn't support conditional imports there seems to be no way of storing data in the app or cookies.

**Comment by Bohmaster** [comment]
Maybe this could be useful. I'm going to try it in a few days.

https://github.com/NathanWalker/angular2-seed-advanced/issues/147#issuecomment-229944545

**Comment by getmetorajesh** [comment]
Interesting, I tried similar thing. A `StorageService.ts` file with a condition to load `application-settings` or  `cookieService`. 

```
if(CoreConfigService.IS_MOBILE_NATIVE()) {
    var appSettings = require('application-settings');
} else {
    var cookieService = require('angular2-cookie/core');
}
```

But unfortunately it doesn't work. It still tries to load the `application-settings.ts` on the web.

**Comment by Bohmaster** [comment]
Let me know how it goes!

**Comment by m-abs** [comment]
We use angular2-localstorage\* to store our auth-token and have wrapped application-settings to make an localStorage-like api.
See: https://github.com/marcj/angular2-localstorage/issues/48
It's not too pretty putting things in global-scope like that, but it works.

Inspired by https://github.com/auth0-blog/angular2-authentication-sample/
We've create a LoginComponent and an auth.guard.

``` typescript
import {Injectable} from '@angular/core';
import {Router, CanActivate} from '@angular/router';
import {BackendService} from './services/backend.service';

@Injectable()
export class AuthGuard implements CanActivate {
  constructor(
    private router: Router,
    private backend: BackendService
  ) {}

  canActivate() {
    if (this.backend.AUTH_TOKEN) {
      return true;
    }

    this.router.navigate(['/login']);
    return false;
  }
}
```

In our _componentname_.routes.ts-files we've added the canActivate-property:

``` typescript
import {RouterConfig} from '@angular/router';

import {SomeComponent} from './some.component';
import {AuthGuard} from '../../frameworks/our.framework/auth.guard';

export const SomeRoutes: RouterConfig = [
  {
    path: '',
    component: SomeComponent,
    canActivate: [AuthGuard],
  },
  {
    path: 'some',
    component: SomeComponent,
    canActivate: [AuthGuard],
  },
];
```

In our LoginComponent we redirect to the our main-page on ngOnInit if the user is already logged in.

*) Because angular2-localstorage doesn't update the stored value on every object instance that uses the value, our BackendService which manages our auth-token is used as a singleton.

```
const OUR_PROVIDER = [
  provide(BackendService, { useClass: BackendService, useExisting: true })
];
```

**Comment by getmetorajesh** [comment]
thanks @m-abs, I ended up with something similar, a common interface `IStorageService` injected in the constructor. In the `app.ts` I passed in `MobileStorage` class and in the `main.web.ts` I used the `WebStorage` class 

```
// main.web.ts
bootstrap(AppComponent,[{provide: globalStorageService, {useClass: WebStorage} }])  

// app.ts
bootstrap(AppComponent,[{provide: globalStorageService, {useClass: MobileStorage} }])  

// where globalStorageService is an opaque token
export let globalStorageService = new Token("IStorageService"); 

//AppComponent   
export class AppComponent {
  constructor(@Inject(globalStorageService) _storage:IStorageService){}
}

```

**Comment by luchillo17** [comment]
@NathanWalker You seem to have lots of experience with `Angular` and `NativeScript`, have you used `@ngrx/store` & `@ngrx/db` ever for `Redux` and offline persistence?

I'm trying to find a way to persist `Redux` state in a way that works with both `Web` & `NativeScript`, do you know how would that work?
