### ISSUE TITLE
SASS Support?

### ISSUE THREAD

**Issue by gvillo** [NathanWalker/angular-seed-advanced#157]
Is there a chance to include sass in this project? how can i help you?

**Comment by vyakymenko** [comment]
@gvillo , yeah , just configure in your _project.config.ts_. More details in parent seed https://github.com/mgechev/angular2-seed/wiki/Enabling-SASS-support

**Comment by vyakymenko** [comment]
I think issue can be closed .

**Comment by NathanWalker** [comment]
Thanks @vyakymenko yes @gvillo you will want to follow that guide.

**Comment by gvillo** [comment]
thanks guys!
