### ISSUE TITLE
add core-decorators?

### ISSUE THREAD

**Issue by phra** [NathanWalker/angular-seed-advanced#167]
hi,

what do you think about adding [core-decorators](https://github.com/jayphelps/core-decorators.js) to this project?

**Comment by m-abs** [comment]
Can core-decorators be used along with ng2's decorators or replace them?

**Comment by phra** [comment]
i think that they can be used along with native decorators. they are just stage-1 esnext decorators. here the [proposal](https://github.com/wycats/javascript-decorators) about them.
in fact without babel or typescript decorators cannot be used.

**Comment by NathanWalker** [comment]
These look awesome 👍  If you wanted to try to integrate on a forked branch to determine if they work alright, I would be interested in possibly merging a PR. The only hesitation I have on something like this is obviously it would be somewhat redundant with `lodash` integration currently. Not entirely but would have some overlap. The other con is most people would not be familiar with these so is somewhat of a preference type of thing at this point until they become part of the native browser spec.

**Comment by phra** [comment]
ok, i'll fork to see what happens and i'll let you know. :+1: 

ps: [actually](https://github.com/cht8687/You-Dont-Need-Lodash-Underscore) i'm not a lodash fan, i prefer vanilla ecmascript/esnext.

**Comment by NathanWalker** [comment]
Closing for later experimentation.
