### ISSUE TITLE
radio is not checked?

### ISSUE THREAD

**Issue by ruanzy** [NathanWalker/angular-seed-advanced#170]
`import {Component} from '@angular/core';

@Component({
    templateUrl: 'assets/setting.html'
})
export class Setting{

```
lang:string = 'cn';
constructor(){

}
```

}`

`<input type="radio" name="lang" id="lang1" value="cn" [(ngModel)]="lang">`
`<input type="radio" name="lang" id="lang2" value="en" [(ngModel)]="lang">`

**Comment by NathanWalker** [comment]
Closing due to reported issue pointing to nothing that would help lead to an understanding of the issue.
