### ISSUE TITLE
spawn gradle.bat NOENT

### ISSUE THREAD

**Issue by lynsei** [NathanWalker/angular-seed-advanced#172]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

Running on win10 x64, with android studio functioning on Android Platform 22 with a functional emulator.  The emulator launches, but after building out the typescript stuff, the nativescript process keeps failing.  I upgraded to nativescript 2.1.1 (and also tried 2.0x) to no avail (updating the package.json file in the nativescript dir).   Everything works and tns-doctor has no errors.... except when I'm running from your gulp processes:

Upon running "npm run start.android" I'm seeing the following error:

The depedency located at D:\Ang-rebase\coolblr\ngs2\se2\nativescript\node_modules\node-inspector\node_modules\ws with version  0.4.32 will be replaced with dependency located at D:\Ang-rebase\coolblr\ngs2\se2\nativescript\node_modules\ws with version 0.7.1
Processing node_modules failed. Error: spawn gradle.bat ENOENT
Sending exception report (press Ctrl+C to stop).....

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "start.android"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angular2-seed-advanced@0.0.0 start.android: `cd nativescript && tns emulate android`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the angular2-seed-advanced@0.0.0 start.android script 'cd nativescript && tns emulate android'. npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed-advanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd nativescript && tns emulate android
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed-advanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed-advanced
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\se2\npm-debug.log

Active code page: 65001

**Expected/desired behavior**

I'v tried using nvm to switch out the nodejs versions.  So far tested on:
5.11.0 
6.3.0 (64x)

**Other information**

**Comment by lynsei** [comment]
This might help:

:processF0DebugManifest
:processF0DebugResources FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':processF0DebugResources'.
  
  > Error: more than one library with package name 'com.tns.android_runtime'
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 51.237 secs
Command D:\Ang-rebase\coolblr\ngs2\se2\nativescript\platforms\android\gradlew.bat failed with exit code 1

**Comment by lynsei** [comment]
OK an update.... I had run node js 5.12.0 x32 and I got it to finish the build process.... I had to clean everything first.   However, once it emulates I'm getting this from npm run start.livesync.android:

JS: ERROR CONTEXT:
JS: [object Object]
JS:
JS: undefined
JS: EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in /data/data/com.yourdomain.appname/files/app/app/components/app/app.component.tns.html:2:2
JS: ORIGINAL EXCEPTION: TypeError: Cannot read property 'take' of undefined
JS: ORIGINAL STACKTRACE:
JS: TypeError: Cannot read property 'take' of undefined
JS:     at SafeSubscriber._next (/data/data/com.yourdomain.appname/files/app/app/frameworks/i18n/services/multilingual.service.js:59:55)
JS:     at SafeSubscriber.__tryOrUnsub (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:225:16)
JS:     at SafeSubscriber.next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:174:22) JS:     at Subscriber._next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:124:26)
JS:     at Subscriber.next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:88:18)
JS:     at DistinctUntilChangedSubscriber._next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/operator/distinctUntilChanged.js:72:30)
JS:     at DistinctUntilChangedSubscriber.Subscriber.next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:88:18)
JS:     at MapSubscriber._next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/operator/map.js:82:26)

JS:     at MapSubscriber.Subscriber.next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:88:18)
JS:     at Store.Subject._finalNext (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subject.js:128:30)

**Comment by lynsei** [comment]
ok maybe it's something with this code or it's not pulling the language files or something:

```
store.select('i18n').subscribe((state: MultilingualStateI) => {
  // update ng2-translate which will cause translations to occur wherever the TranslatePipe is used in the view
  if (this.translate.getLangs() && (this.translate.getLangs().indexOf(state.lang) > -1)) {
    this.translate.use(state.lang);
  } else {

    this.translate.reloadLang(state.lang).take(1).subscribe(() => {
      setTimeout(() => this.translate.use(state.lang), 1000);
    });
  }
});
```

**Comment by deanpeterson** [comment]
I am getting the same error on a Mac Pro with Nexus_5_API_23 emulator. I have attached a screenshot.
![screen shot 2016-07-21 at 12 46 35 pm](https://cloud.githubusercontent.com/assets/1156788/17032901/2c2043d4-4f41-11e6-92f5-7ec78e7fd5fe.png)

**Comment by deanpeterson** [comment]
here is more of the stack trace in the terminal

```
JS: [object Object] ; Zone: angular ; Task: Promise.then ; Value: EXCEPTION: Error in /data/data/com.yourdomain.appname/files/app/app/components/app/app.component.tns.html:2:2
JS: ORIGINAL EXCEPTION: TypeError: Cannot read property 'take' of undefined
JS: ORIGINAL STACKTRACE:
JS: TypeError: Cannot read property 'take' of undefined
JS:     at SafeSubscriber._next (/data/data/com.yourdomain.appname/files/app/app/frameworks/i18n/services/multilingual.service.js:59:55)
JS:     at SafeSubscriber.__tryOrUnsub (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:225:16)
JS:     at SafeSubscriber.next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:174:22)
JS:     at Subscriber._next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:124:26)
JS:     at Subscriber.next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:88:18)
JS:     at DistinctUntilChangedSubscriber._next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/operator/distinctUntilChanged.js:72:30)
JS:     at DistinctUntilChangedSubscriber.Subscriber.next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:88:18)
JS:     at MapSubscriber._next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/operator/map.js:82:26)
JS:     at MapSubscriber.Subscriber.next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:88:18)
JS:     at Store.Subject._finalNext (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subject.js:128:30)
JS: ERROR CONTEXT:
JS: [object Object]
JS: Error: Uncaught (in promise): EXCEPTION: Error in /data/data/com.yourdomain.appname/files/app/app/components/app/app.component.tns.html:2:2
JS: ORIGINAL EXCEPTION: TypeError: Cannot read property 'take' of undefined
JS: ORIGINAL STACKTRACE:
JS: TypeError: Cannot read property 'take' of undefined
JS:     at SafeSubscriber._next (/data/data/com.yourdomain.appname/files/app/app/frameworks/i18n/services/multilingual.service.js:59:55)
JS:     at SafeSubscriber.__tryOrUnsub (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:225:16)
JS:     at SafeSubscriber.next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:174:22)
JS:     at Subscriber._next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:124:26)
JS:     at Subscriber.next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:88:18)
JS:     at DistinctUntilChangedSubscriber._next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/operator/distinctUntilChanged.js:72:30)
JS:     at DistinctUntilChangedSubscriber.Subscriber.next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:88:18)
JS:     at MapSubscriber._next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/operator/map.js:82:26)
JS:     at MapSubscriber.Subscriber.next (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subscriber.js:88:18)
JS:     at Store.Subject._finalNext (/data/data/com.yourdomain.appname/files/app/tns_modules/rxjs/Subject.js:128:30)
JS: ERROR CONTEXT:
JS: [object Object]
```

**Comment by NathanWalker** [comment]
Thanks for reporting this, looks like the {N} ng2 -translate adaptor needs an update possibly. I'll have this fixed later today.

**Comment by NathanWalker** [comment]
This is now fixed on master. When you pull latest in, just clear:

```
rm -rf nativescript/node_modules nativescript/platforms
npm run start.ios  (or android, etc)
```

Thanks again.

**Comment by NirLevanon-zz** [comment]
I'm getting a similar error, but related to using `changeDetectorRef.detectChanges();` against 
`<Label text="No device detected." id="noBluetoothWarning" horizontalAlignment="center" color="#B11" *ngIf="bluetoothDisconnected" marginTop="30"></Label>`
(when trying to update UI after chaning `bluetoothDisconnected` in my `NSAppComponent` class)
