### ISSUE TITLE
 radio default checked?

### ISSUE THREAD

**Issue by ruanzy** [NathanWalker/angular-seed-advanced#174]
`import {Component} from '@angular/core';

@Component({
templateUrl: 'assets/setting.html'
})
export class Setting{

lang:string = 'cn';
constructor(){

}
}`

`<input type="radio" name="lang" id="lang1" value="cn" [(ngModel)]="lang">`
`<input type="radio" name="lang" id="lang2" value="en" [(ngModel)]="lang">`

the first radio not checked?

**Comment by NathanWalker** [comment]
You may try solutions here:
http://stackoverflow.com/questions/31879497/angular2-radio-button-binding

**Comment by NathanWalker** [comment]
Closing as this issue does not appear to be related to the seed. Please see stackoverflow or angular docs for answers to issues like this.
