### ISSUE TITLE
Streamline/cleanup adding of external dependencies

### ISSUE THREAD

**Issue by yvoronen** [NathanWalker/angular-seed-advanced#176]
**Steps to reproduce and a minimal demo of the problem**

Adding an external JS dependency to a project requires changes to a lot of different files, leading to bugs, and unexpected behavior.  This is not fully documented. Ideally one would somehow simplify this.

**Current behavior**

In order to add a dependency, at a minimum it seems that one would have to patch the following files

```
package.json  (usually automated via npm)
tools/config/project.config.ts
tools/tasks/project/desktop.libs.ts
tools/manual_typings/project/...
tools/utils/project/systemjs-packages.ts    (optional?)
karma.conf.js
test-main.js
```

Within `project.config.ts` itself, there is `SYSTEM_CONFIG.paths`, `SYSTEM_CONFIG.packages`, then also `SYSTEM_BUILDER_CONFIG.paths` and `.packages`.

It is not 100% clear to me when one has to patch the `.packages` vs just the `.paths`. 

**Expected/desired behavior**

It would be nice to have somebody provide an example of _fully_ (including karma/jasmine, desktop, prod builds, etc) integrating a new dependency.

Ideally one could add a dependency to package.json, or some other place and other configs would just pick it up. 

**Other information**

**Comment by NathanWalker** [comment]
Hi @yvoronen Thanks for bringing this up, I will plan to provide 1 example of a library integration showing all the files requiring modification by the end of this month.

**Comment by VladimirMakaev** [comment]
+1. Some libraries 'just work' after npm install --save. But for some it's a nightmare to get it working. I understand there are some conventions that try to capture majority of the cases but when it's outside of those conventions it's really hard and unclear.

**Comment by NathanWalker** [comment]
This has been made much simpler with latest upstream parent changes.
