### ISSUE TITLE
Failed to find Module

### ISSUE THREAD

**Issue by deanpeterson** [NathanWalker/angular-seed-advanced#178]
I just pulled down the latest and tried to run the android native script demo on a Mac.  I get the following error:
![screen shot 2016-07-26 at 9 44 56 am](https://cloud.githubusercontent.com/assets/1156788/17142406/a19cbb10-5315-11e6-86d4-5e34a967b05a.png)

**Comment by NathanWalker** [comment]
Hi @deanpeterson did you run `npm i` from the root of the project?
Also did you use `npm run start.android` to run from the root?

**Comment by deanpeterson** [comment]
Yes. I did both. I have been doing some reading. I had to install everything, including npm as root. I am normally on either a Redhat Linux machine or a Windows machine for development. Is it an absolute must that I set up my mac machine to allow non root npm i to get this to work on a mac?

**Comment by deanpeterson** [comment]
no matter what I try I keep getting these typescript issues. They appear to be the real problem:

```
/Users/deanpeterson/_devwork/angular2-seed-advanced/node_modules/ts-node/src/index.ts:280
        throw new TSError(diagnosticList)
              ^
TSError: ⨯ Unable to compile TypeScript
gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
gulpfile.ts (2,30): Cannot find module 'run-sequence'. (2307)
    at getOutput (/Users/deanpeterson/_devwork/angular2-seed-advanced/node_modules/ts-node/src/index.ts:280:15)
    at compile (/Users/deanpeterson/_devwork/angular2-seed-advanced/node_modules/ts-node/src/index.ts:289:14)
    at loader (/Users/deanpeterson/_devwork/angular2-seed-advanced/node_modules/ts-node/src/index.ts:304:23)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/deanpeterson/_devwork/angular2-seed-advanced/node_modules/ts-node/src/index.ts:321:14)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/Users/deanpeterson/_devwork/angular2-seed-advanced/node_modules/gulp/bin/gulp.js:116:3)
```

**Comment by NathanWalker** [comment]
I've seen that issue reported before in parent seed, check this for solution:
https://github.com/mgechev/angular2-seed/issues/147

**Comment by deanpeterson** [comment]
I was able to get past one problem by typing tsc --project tsconfig.json.  I am now at least able to run the web app with npm start.  However, I am getting a new error in the android emulator npm run start.android:
![screen shot 2016-07-26 at 1 57 09 pm](https://cloud.githubusercontent.com/assets/1156788/17151435/30f99788-5339-11e6-8e13-1a47a425a86f.png)

**Comment by deanpeterson** [comment]
I have cleaned everything up. All ts files are compiled. There are no errors during startup and I still get the above error about the "Application entry point file not found" running the android native script application. The web application works.

**Comment by NathanWalker** [comment]
@deanpeterson Seems like I've seen this with an incompatible android emulator version?
You may try using [GenyMotion](https://www.genymotion.com/) or at least use 5.1 android virtual device.
Also make sure your `tns` version is at least `2.1.1`.

**Comment by deanpeterson** [comment]
It must have been permission issues. I had cloned the angular2 advanced seed as a sudo user. I deleted everything, ran this: sudo chown -R deanpeterson $(npm config get prefix)/{lib/node_modules,bin,share}, then re-cloned the project as a non-sudo user and tried again.  It is working now.
