### ISSUE TITLE
build.prod not working (error with @angular/forms.js)

### ISSUE THREAD

**Issue by syrys-jwt** [NathanWalker/angular-seed-advanced#179]
Hey Guys,

Im new to angular2 and this seed project, i just started playing around with it and noticed that the repo fails to build for production, but dev builds and the normal run command work just fine. Can someone help me get started?

here is the error i get when i run the command `npm run build.prod`

```
... normal build outputs here untill the error happens...

[16:54:42] 'build.bundles.app' errored after 438 ms
[16:54:42] Error on fetch for @angular/forms.js at file:///E:/Test/angular2-seed-advanced/node_modules/@angular/forms.js
        Loading dist/tmp/main.web.js
        Error: ENOENT: no such file or directory, open 'E:\Test\angular2-seed-advanced\node_modules\@angular\forms.js'
    at Error (native)
[16:54:42] 'build.prod' errored after 8.04 s
[16:54:42] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on fetch for @angular/forms.js at file:///E:/Test/angular2-seed-advanced/node_modules/@angular/forms.js
        Loading dist/tmp/main.web.js
        ENOENT: no such file or directory, open 'E:\Test\angular2-seed-advanced\node_modules\@angular\forms.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open 'E:\Test\angular2-seed-advanced\node_modules\@angular\forms.js'
Stack:
Error on fetch for @angular/forms.js at file:///E:/Test/angular2-seed-advanced/node_modules/@angular/forms.js
        Loading dist/tmp/main.web.js
        Error: ENOENT: no such file or directory, open 'E:\Test\angular2-seed-advanced\node_modules\@angular\forms.js'
    at Error (native)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build.
prod"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed-advanced@0.0.0 build.prod: `gulp build.prod --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed-advanced@0.0.0 build.prod script 'gulp build.prod --color'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed-advanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build.prod --color
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed-advanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed-advanced
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Test\angular2-seed-advanced\npm-debug.log

E:\Test\angular2-seed-advanced>

```

Steps to reproduce you ask? Simple.
Follow the steps mentioned on the main readme file at the master branch.
1. use git command to clone the repo (or just download as zip and unzip).
2. using npm, install typescript and nativescript as global
3. use command line to navigate to the project root.
4. `npm install` => seems fine, no obvious errors
5. `npm run` => seems fine, demo pages runs on the web browser, no obvious errors
6. kill above process then run `npm run build.dev` => no obvious errors, though i did not test the integrity pf the output. But no obvious issues.
7. `npm run build.prod` => runs for a little while and dies with the error output displaying in the command line (mentioned earlier).

Anything else you want me to test?

Cheers.

OS: Windows 10
Node: 6.3.1
NPM: 3.10.3

**Comment by syrys-jwt** [comment]
@NathanWalker Are you the culprit? haha.
https://github.com/NathanWalker/angular2-seed-advanced/commit/36128ffda184ba68cd74d75587b6604eb55fa486
I hope im not doing something wrong here. But thats definatly the commit that looks like whats causing the issue. Im assuming the package version numbers might be incorrect, the versions that you are expecting this file/package changes?

**Comment by NathanWalker** [comment]
Thanks for reporting this. Production likely needs to be updated, that commit is correct is fixing the paths so that is for good reason ;) I'll fix prod build tomorrow.

**Comment by NathanWalker** [comment]
Actually I just went ahead and fixed it 👍  Please pull master (or merge in latest master to your project) and give it a go. Thanks again for bringing this to my attention!

**Comment by syrys** [comment]
(oops, posted the original bug using the wrong account)
@NathanWalker  Hey man, thanks so much for the quick fix. and no worries about posting it, will happily do that in the future. I have couple of unrelated questions for you guys, sort of support related but the answers to them could be beneficial to be added to the wiki/readme. Do you guys have a good way i can ask these? Its sort of related to how one goes about doing things with the project structured the way it is (ie, creating an app/website, adding/enabling sass/compass, adding packages/libraries/files to electron) without interfering too much with merging back with this seed project updates. Its easy enough to go ahead and edit the demo app, edit the config files etc, but i have a feeling that you guys have better ways in mind (in terms of merging capabilities and for future) which is not very well communicated with the end users (the readme does a fair bit but doesnt go into details/specifics), which the end users will likely only figure out after they go too far into their first/second project.

Cheers.

**Comment by clevegomes** [comment]
Thanks .. I too was facing the same problem
