### ISSUE TITLE
Debugging NativeScript App

### ISSUE THREAD

**Issue by zeeshanjan82** [NathanWalker/angular-seed-advanced#183]
I am currently building a nativescript app using the seed project, I am not able to find a way to debug the app. Is there any command I could use to debug the app using node-inspector when my app is running inside the emulator?

**Comment by NathanWalker** [comment]
If using VS Code, you can set breakpoints using this extension: https://www.nativescript.org/nativescript-for-visual-studio-code

You can use node/web inspector following this: https://docs.nativescript.org/runtimes/android/debug/debug-cli

**Comment by NathanWalker** [comment]
@zeeshanjan82 sounds like you went with cordova. If you are still curious about {N} options, just ping me back here.

**Comment by zeeshanjan82** [comment]
Thanks @NathanWalker I have moved ahead with Cordova for now, I really liked {N} however I have faced few issues when implementing {N} :
1. Compilation takes lot of time, I had to wait for 2-3 minutes for compilation to finish and emulator to reflect the changes. May be its because I am using i3 , 4GB RAM machine and also have emulator running.
2. There are very less styling options, only few things in CSS are supported.

Personally I have really liked {N} its a wonderful thing, but I will come back to it when I have a better machine. Do you have any recommendations for running {N} on a low end machine like mine?
