### ISSUE TITLE
Importing Electron (libraries/modules) to Web/Frontend

### ISSUE THREAD

**Issue by syrys** [NathanWalker/angular-seed-advanced#186]
Hey Guys,

Thought i should post this in its own post as it might help others in the future.

Im trying to integrate the electron's ipc connection with the code (more info here: `https://github.com/electron/electron/blob/master/docs/api/ipc-main.md`). I can easily do the backend part of it (simply adding the IPCMain stuff to the `main.desktop.ts`). For the frontend (web) part, its a bit tricky, and it feels like there is no doccumented logical way to import this to the web side of things.

Keep in mind, since this seed project will build into desktop/web/mobile, you only want this electron/ipc module available for desktop. So we need some way to distinguish this. So maybe someone can suggest some good ways to go about building services that work differently in web/mobile (using say http requests) vs desktop (electron ipc). A demo/guide would be greatly helpful for future devs.

I did however manage to get the IPC to work on the frontend, by adding the following to the index.html just before the ending body tag:

```
 <% if (TARGET_DESKTOP) { %>
  <script>
    console.log("Electron");
    System.set('electron', System.newModule(require('electron')));
  </script>
  <% } else { %>
  <script>
    console.log("Web");
    System.set('electron', System.newModule({})); // placeholder?
  </script>
  <% } %>
```

Then you can use the following line on any component that want to make use of the ipc:

```
import {ipcRenderer} from 'electron';
```

This works fine and functions as expected. You can use the ipcRenderer from within the component etc (`ipcAvailable = (typeof ipcRenderer != 'undefined');` within component constructor() should tell you if this is available or not). Only problem with this is, its showing up as an error on my IDE (Web Storm), although it actually works. Any better way to do this would be greatly appreciated. This feels very hacky to me, i bet there is a better way to go about this (if not, can we look into making one?).

**Comment by NathanWalker** [comment]
This is really good insight @syrys thank you for this. I'm not sure of a better way either however your method sounds feasible. We may repurpose this as a wiki article soon but lets leave open to see if any more improvements could be suggested by others. 👍

**Comment by syrys** [comment]
@NathanWalker awesome, great to know that im not completely off haha. I was a little confused as to the purpose of the `client/app/frameworks/*` section. Wasent 100% sure what that section was used for.

Also, if what i said above is actually accurate, then maybe that code snippet might be worth including almost as it is on the seed. Because for Electron developers, why wouldnt you inject electron (even if you dont use it, theres no real harm in it), and for web builds, its just 1 dummy line of code overhead. 

Saying that though, i do have couple of other suggestions. Sort of in relation to this:
1. Desktop and Desktop related dependencies (like electron above) can/should be included in the `project.config.ts`. The same way that you include `this.NPM_DEPENDENCIES = ...`, you can use something like `this.ELECTRON_FRONTEND_DEPENDENCIES = ['electron', 'blah', 'etc...']`, and as a result a similar output as what i mentioned on my original post above could be made by looping through this array (remember to create the placeholder/dummy so the import ).
2. This might be a bit harder, but is it possible to have multiple (environment specific) versions of a components (or service or what ever other types of ng2 files, sorry im not familiar with ng2 terms, im coming from ng1). By this, i mean, lets say you have a component `cool.component.ts`. One can also make a `cool.component.desktop.ts` (they dont have to, but they can). So, with this, if you run a "web build" the resulting `cool.component.js` will be a compile version of `cool.component.ts`, but if you run a desktop build, then the resulting `cool.component.js` would be a compile version of `cool.component.desktop.ts`. With me so far? So the compiler should look if a environment specific ts file exists, if so use that, if not then fall back to the default ts file. Which means we can make duplicate services that treat the execution slightly differently (i believe this is how nativescript works right? Sorry, not too familiar with that yet). This would just prevent your cross platform project's services/classes being full of huge if statements on most functions (if electron do this, if not then do this). 

Hope those suggestions are not too derp :)

**Comment by NathanWalker** [comment]
`client/app/frameworks/*` is out of the box seed code to support various things like i18n and/or core services like `LogService` and `WindowService` for instance which can be injected and safely used cross platform without worry it would break one or the other. It's intended for seed users to build their custom app code our of a folder inside`frameworks`; helps keep their code portable and altogether (ie, they could drop their folder in a new seed, switch seeds, etc.).
1. Sounds very reasonable and consistent with the seed approach to managing dependencies for systemjs builds, etc so this makes a lot of sense to help isolate platform specific dependencies.
2. You are correct, {N} does handle `.ios` and `.android` naming conventions for the same purpose. I like the thought of this in general as long as it easily defaults to using the web `.component` file if a specific platform alternate was not found. This way users aren't required to create a platform file for every single component. There are many instances where an electron/desktop component will be identical to its web browser counterpart since electron is effectively rendering a webview inside 👍

**Comment by syrys** [comment]
> You are correct, {N} does handle .ios and .android naming conventions for the same purpose. I like the thought of this in general as long as it easily defaults to using the web .component file if a specific platform alternate was not found. This way users aren't required to create a platform file for every single component. There are many instances where an electron/desktop component will be identical to its web browser counterpart since electron is effectively rendering a webview inside :+1:

Yup, if you code it well, usually it would be something like services (i think thats what they still call them in ng2, but ng1 had services/factories) that will see the bulk of the difference between web/desktop builds as the components (used to be controllers/directives) and pipes would and should remain the same. if you want different html, since its linked within the component, you can just create a duplicate html file and link from within the device specific component. But then a problem arises where you have duplicate html templates, but each of those would get compiled together in production web builds (adding un-necessary code). Suppose if people are worried about that, they can start writing templates inline within the components.

Saying that though, implementing 2. above is probably not the easiest task in the world :stuck_out_tongue: 1. should be easy, even i could probably do it haha.

**Comment by plyoung** [comment]
I discovered this repo and thought my problems are finally solved :/

I've been trying to get this ipcRenderer working in an Angular Component the whole week now while also trying to get a nice work flow going. Everyone mentions the System.newModule in index.html but then you are still stuck with that error during build and of course in the IDE.

I manage to get rid of the error and get intellisense in VS Code by installing the github-electron typings
`typings install dt~github-electron -SG` but then the build error changes to `error TS2304: Cannot find name 'NodeJS'.` I dare not mess with what this repo includes in its configs related to Node since I only started messing with this whole Node and Electron thing this week.

**Comment by kbrandwijk** [comment]
I very much like the approach for desktop to be the same like for tns. The only challenge I see right now is that the functionality for template and style is provided by ViewBroker, which is used in BaseComponent. It looks at the metadata for BaseComponent, and replaces the styles and template with the tns counterpart. To do this on component level for desktop/non-desktop would require to apply this same strategy at a higher level...

Looking at a possible place to do it would be in the gulp task for Typescript compilation, as Typescript support customizing module resolution. I have opened an issue on gulp-typescript to see if they can support this strategy. Then, I think it would be as simple as changing the import/export file name based on the build type (desktop, other).

Does this sound like the right approach?

**Comment by syrys** [comment]
Hey @NathanWalker i got into a hiccup with what i mentioned in the first post above. Can you please help me figure out how i can get this working?

So, what i was trying to do is integrate/use ipcRenderer from electron (obviously only in the case of electron app since its useless for web).

**What i did:**
1) added the following to `index.html`

```
 <% if (TARGET_DESKTOP) { %>
  <script>
    console.log("Electron");
    System.set('electron', System.newModule(require('electron')));
  </script>
  <% } else { %>
  <script>
    console.log("Web");
    System.set('electron', System.newModule({})); // placeholder?
  </script>
  <% } %>
```

2) added the following to a component (lets say `about.component.ts`)

```
import {ipcRenderer} from 'electron';
```

**Problem:** 
All works fine on building electron app and and building for dev. But if you build for production `build.prod` i get the following error:

```
[12:43:10] 'build.bundles.app' errored after 3.01 s
[12:43:10] Error on fetch for electron.js at file:///__PROJECT_DIR__/node_modules/
electron.js
        Loading dist/tmp/app/components/about/about.component.js
        Loading dist/tmp/web.module.js
        Loading dist/tmp/main.web.js
        Error: ENOENT: no such file or directory, open '__PROJECT_DIR__\node_modul
es\electron.js'
    at Error (native)
...
```

Obviously because it sees the `import` statement for `electron`, it looks for it in `node_modules` but fails to find it. 

Can you think of a way to work around this?

**Comment by syrys** [comment]
i think i solved the above problem.

Alter the `build.bundles.app.ts` and `build.bundles.app.exp.ts` and add `externals: ['electron']` to the `BUNDLER_OPTIONS` at the top. It should look something like this:

```
const BUNDLER_OPTIONS = {
  format: 'cjs',
  minify: true,
  mangle: false,
  externals: ['electron']
};
```

**Comment by TekSiDoT** [comment]
Great job on the IPC integration, imho it should become part of the standard seed as well.

**Comment by NathanWalker** [comment]
Feel free to continue discussion here, just closing to cleanup outstanding issues.

**Comment by ccoxtn** [comment]
I solved this problem without editing the index.html or build.bundle.* files. Just need to setup the SystemJS map for Node modules by adding this code to project.config.ts:

```
    // SystemJS map for Desktop builds
    if (this.TARGET_DESKTOP) {
      this.SYSTEM_CONFIG_DEV.map = {
        ...this.SYSTEM_CONFIG_DEV.map,
        'electron': '@node/electron'
      }
    }
```

See following link for more info:
[SystemJS Issue 1261](https://github.com/systemjs/systemjs/issues/1261#ref-issue-172579127)
