### ISSUE TITLE
Electrons (main.desktop.ts) environment name is incorrect

### ISSUE THREAD

**Issue by syrys** [NathanWalker/angular-seed-advanced#187]
Just debugged an issue i was having and tracked down to this. So, if you look at `main.desktop.ts`, you will see a pretty obvious line (if statement) near the top that has the following in it `process.env.NODE_ENV === 'development'`. Unless i somehow messed something up somewhere, This will ALWAYS be false. because if you inspect `process.env.NODE_ENV`, the value is infact `"development "` (yes, there is a space at the end).

Im assuming its a typo somewhere. Can we get this updated, otherwise we have to use `startsWith()` instead of `===`, which i will do on local for now.

Thanks :)

**Comment by NathanWalker** [comment]
Are you on Windows or Mac?

**Comment by NathanWalker** [comment]
Hmm, I actually just looked at this and there's no space. It's `development`. At least on a Mac, so it's correct on master. I'm going to close this now but if you are on Windows and seeing this, please reopen.

**Comment by syrys** [comment]
@NathanWalker Yes im using Windows (10). And yes its a problem. Just to make sure:

Did a fresh `git clone` and `npm install` just now. added a line `console.log(process.env)` to `main.desktop.ts` and ran `npm run start.desktop.windows`. Within the huge console log dump, i see the following line:

```
 NODE_ENV: 'development ',
```

Maybe i will try to debug it when i have a bit of time.

**Comment by syrys** [comment]
so from a quick read, it seems like this value is set on your computer somehow? Is this correct? 

If that is the case, i guess mine is set wrong, which i dont quite know how to fix (so the issue is coming from my machine). But if that is the case, and if this is not common knowledge, then should this value really be used to determine if the environment is `development` or `production`? Shouldn't we set the environment variable based on what we used in the build command? 

```
npm run start.desktop #development
npm run start.desktop.windows #development
npm run start.livesync.desktop #development
npm run start.livesync.desktop.windows #development

npm run build.desktop.mac #production
npm run build.desktop.windows #production
npm run build.desktop.linux #production
```

Maybe add the ability to build the production ones as development as well just in case you want to make a distributable development version. This would be fairly simple by adding an extra flag on `package.json` and/or adding couple of extra blocks to the gulpfile.

Sorry if im completely off about this.

**Comment by jvitor83** [comment]
The trouble is with the extra whitespace when setting the environment at the script package.
More info at
http://stackoverflow.com/a/30272349/1252994

**Comment by syrys** [comment]
@jvitor83 ah i see, i didnt realise that the NODE_ENV was set on the script commands on the package.json (i thought it was like a global setting for node that i would need to find some config file somewhere). learn something new every day haha (im fairly new to node btw) :P But yes, you are absolutely correct.

@NathanWalker i guess its an easy fix then? Just need to update package.json and remove whitespace before and after the `&&` that follows all the `NODE_DEV=development` part. Tested on my local and that fixes the problem.
