### ISSUE TITLE
Change Android App Name

### ISSUE THREAD

**Issue by zeeshanjan82** [NathanWalker/angular-seed-advanced#188]
I would like change the default AppName for Android from 'nativescript' currently each time I install the app it has the default app_name as 'nativescript' how can I change it. I noticed that the app_name is dynamically assigned to AndroidManifest.xml file 

```
    <application
        android:name="com.tns.NativeScriptApplication"
        android:allowBackup="true"
        android:icon="@drawable/icon"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
```

How can I change these values?

**Comment by zeeshanjan82** [comment]
Was able to figure this out.

**Comment by melliott03** [comment]
How did you solve this?

**Comment by Sharique-Hasan** [comment]
@zeeshanjan82 How did you solve this issue?

**Comment by erikhofer** [comment]
You can create the file `nativescript/src/App_Resources/Android/values/strings.xml` with the following content
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">Your App Name</string>
    <string name="title_activity_kimera">Your App Name</string>
</resources>
```

**Comment by chris-praxis** [comment]
In my case the file is here: [project path]/App_Resources/Android/src/main/res/values/strings.xml
