### ISSUE TITLE
Running Index.html directly

### ISSUE THREAD

**Issue by zeeshanjan82** [NathanWalker/angular-seed-advanced#189]
I have a very important and basic question as I am planning to use this seed project in my new cordova based application. When I clone the seed repo and run the command `npm run build.prod` I am able to get the release inside the dist/prod folder. When I run the release using some web server then I am able to view the app properly however my plan is to use the same seed project with cordova, I had tried with nativescript but faced some issues so decide to go ahead with cordova. In cordova the app is run from the file:/// url instead of http:// so when I double click the index.html file inside the dist/prod folder I am not able to view the app, I get the following error, is there any way I could fix it so that I can double click on the index.html file and the angular app works.
![error](https://cloud.githubusercontent.com/assets/8342604/17372499/ce0e9a8a-59c1-11e6-9b7f-5470af4706c3.png)

**Comment by vyakymenko** [comment]
Reason in relative path. Run it in server , or use _base_ property when building your app.

**Comment by NathanWalker** [comment]
@vyakymenko is correct, you will need to adjust the base property.

Feel free to share the NativeScript issues you faced, I may be able to help get you going there faster than trying to setup a hybrid.

**Comment by zeeshanjan82** [comment]
Thanks @vyakymenko @NathanWalker I tried to use `<base href="./">` and then when I try to double click the index.html file I can see the following errors in the console.
![error](https://cloud.githubusercontent.com/assets/8342604/17456605/66f4ce6e-5bfb-11e6-8a6e-a4a9b4cfcd20.png)
The interesting thing here is if I set my default route as this:

```
export const LoginRoutes = [
  {
    path: 'C:/cygwin/home/Administrator/WORK/giirbox_n/app/dist/prod',
    component: LoginComponent
  },
];
```

then everything works fine.

**Comment by zeeshanjan82** [comment]
I am also trying to check the command `npm run build.prod --base android_assets/www` but it doesn't seem to work. Instead of hardcoding the base value in the index or the seed.config.ts I could pass it dynamically each time I create a production build. I am really not sure if that is the correct approach?

I have also tried to put the base property as `<base href="/cygwin/home/Administrator/WORK/giirbox_n/app/dist/prod/">` this also gives the same error of not finding the route. I cannot run the app on server as I am building a cordova app which will be ultimately run as file:/// URL on the android or ios device.

**Comment by CNSKnight** [comment]
(Eavesdropping on this as I'm attempting to build as a plugin to a disparate app.)
Not understanding what @vyakymenko is meaning by 

> use base property when building
> I've tried eg `$ npm run build.dev --base="/different-from-dev-env/path-root/dist/dev"` but w/no change in index.html

**Comment by NathanWalker** [comment]
Feel free to continue discussion here, just closing to cleanup outstanding issues.
