### ISSUE TITLE
NativeScript app not working when deployed to a AVD. 

### ISSUE THREAD

**Issue by pravegali** [NathanWalker/angular-seed-advanced#190]
![image](https://cloud.githubusercontent.com/assets/12238474/17407115/1c39578c-5a34-11e6-8481-0cfdd5734b24.png)

Above is the screenshot of the error on the AVD. 
Looked at the code , files like app.ts under nativescript are yielding errors for the import statements. 

Any help is appreciated.!!

And the lines below on nativescript/app/pages/app/app.component.ts

import {AppComponent} from '../../app/components/app/app.component';
import {LogService} from '../../app/frameworks/core/index';
import {AnalyticsService} from '../../app/frameworks/analytics/index';

yields errors like "the modules cannot be found".  

CMD Output: 

Executing before-prepare hook from C:\Users\galipx\Source\Repos\angular2-seed-ad
vanced\nativescript\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
app/app.ts(16,37): error TS2307: Cannot find module './app/frameworks/core/index
'.

app/app.ts(23,22): error TS2307: Cannot find module './app/components/app/app.ro
utes'.
app/pages/app/app.component.ts(12,28): error TS2307: Cannot find module '../../a
pp/components/app/app.component'.
app/pages/app/app.component.ts(13,26): error TS2307: Cannot find module '../../a
pp/frameworks/core/index'.
app/pages/app/app.component.ts(14,32): error TS2307: Cannot find module '../../a
pp/frameworks/analytics/index'.
app/shared/core/services/window-native.service.ts(5,23): error TS2307: Cannot fi
nd module '../../../app/frameworks/core/interfaces/iwindow'.
app/shared/core/utils/actionbar.util.spec.ts(1,17): error TS2307: Cannot find mo
dule '../../../app/frameworks/test/index'.
app/shared/nativescript-config.spec.ts(1,17): error TS2307: Cannot find module '
../app/frameworks/test/index'.
app/shared/nativescript/index.ts(12,42): error TS2307: Cannot find module '../..
/app/frameworks/core/index'.
app/shared/nativescript/index.ts(13,32): error TS2307: Cannot find module '../..
/app/frameworks/analytics/index'.
app/shared/nativescript/index.ts(14,49): error TS2307: Cannot find module '../..
/app/frameworks/app/index'.
app/shared/nativescript/index.ts(15,56): error TS2307: Cannot find module '../..
/app/frameworks/i18n/index'.

**Comment by NathanWalker** [comment]
Did you run:

```
npm i
```

in the root on the project (not in the `nativescript` folder) first?

Your errors indicate that the symlink was not setup properly which is usually setup after running `npm i` in the root.

**Comment by NathanWalker** [comment]
@pravegali Please reopen if you still have issue but the above should help get you going.
