### ISSUE TITLE
Implementing angular2-forms with NativeScript

### ISSUE THREAD

**Issue by igonzalezespi** [NathanWalker/angular-seed-advanced#191]
Can be angular2-forms be implemented with NativeScript?
What's the best way if so?

**Comment by NathanWalker** [comment]
Hi @ivannugo good question! I have been wanting to experiment with new forms api and {N}.
If anyone else has tried, please share experience here. When I'm able to get to it I'll let you know.

**Comment by derekdon** [comment]
Might be of interest, https://github.com/NativeScript/nativescript-angular/issues/526

**Comment by derekdon** [comment]
I'd be interested to know how people are approaching not only form generation (if model driven) but also validation. For example if this seed were to have a registration form, how would perhaps shared validation rules and user form feedback be handled across the platforms. ie. enter a valid email address.

**Comment by NathanWalker** [comment]
Feel free to continue discussion here, just closing to cleanup outstanding issues. In meantime you could have a look at this: https://github.com/formly-js/ng-formly-nativescript
