### ISSUE TITLE
npm run build.prod creates .js and .js.map files in tools folder

### ISSUE THREAD

**Issue by Flood** [NathanWalker/angular-seed-advanced#196]
**Steps to reproduce and a minimal demo of the problem**

Under tools/config i have a project.config.ts file. After running "npm run build.prod" it creates js file that is nested (in Visual studio 2015) with the .ts file. This goes for all files under the tools folder, and also the gulpfile.ts has a gulpfile.js. 

After this run, when editing a .ts file the changes are not copied to the js files. So each time I run build.prod I have to delete ALL .js and .map files to get the changes.

If I delete only one js file the "npm start" does not work. Complaining about "Error: Cannot find module './config/project.config'". But if I delete all, everything works.

**Expected/desired behavior**
No files should be created. If they need to be created they should end up in the dist folder.

**Comment by NathanWalker** [comment]
I have never seen this. You may have something off in your local config or in your local npm setup.
Please check to make sure you have no auto-compilers on (some people use 3rd party program to watch directories and auto-compile things).

**Comment by Flood** [comment]
Hmm ok, it's weird. build.dev and npm start works...but build.prod creates these files. I have a clean installation of VS 2015 and Node.
