### ISSUE TITLE
json data is not rendering in desktop app

### ISSUE THREAD

**Issue by Ashish619** [NathanWalker/angular-seed-advanced#198]
List of predefined scientists is not rendering in desktop on windows.
web and android native are running perfectly.
can anybody please help me on this ?

![untitled](https://cloud.githubusercontent.com/assets/11409529/17586699/fb9373c0-5fe0-11e6-9cd7-ab28014f4680.png)

**Comment by orangedrink** [comment]
In src/client/app/frameworks/app/services/name-list.service.ts I changed line 51 to get from a relative path: ./assets/data.json

Working ok as far as I can tell on my mac. Haven't tested with mobile app builds.

**Comment by Ashish619** [comment]
Thanks , it Worked.

**Comment by orangedrink** [comment]
Awesome! #imhelping
