### ISSUE TITLE
Update ng2-translate

### ISSUE THREAD

**Issue by ocombe** [NathanWalker/angular-seed-advanced#2]
Hello,

your ng2-translate requirement is ^1.8.0, I made some breaking changes in 1.10.0 and you need to update your code. More info here: https://github.com/ocombe/ng2-translate/releases/tag/v1.10.0

I should have released a major version but well.. :-)

You could also freeze the dependency to 1.9.0 until you update your code

**Comment by NathanWalker** [comment]
Thanks for heads up @ocombe ! I'll freeze until I have time to update.

**Comment by NathanWalker** [comment]
Updated to `1.10.0` now.

**Comment by ocombe** [comment]
:+1:
