### ISSUE TITLE
Rxjs store, what's the right way to extend the store?

### ISSUE THREAD

**Issue by Sn3b** [NathanWalker/angular-seed-advanced#200]
After creating my own framework folder and added a few services, I'm now trying to create my own reducers just like it is done for the NameListService. So I defined my actions and reducer within the service file, again, trying to mimic the NameListService.

Am I now supposed to append src/client/app/frameworks/app/index.ts to reference my reducer, or create my own store within src/client/app/frameworks/myownframework/index.ts?

**Comment by NathanWalker** [comment]
@Sn3b You will want to export your new service/reducer etc. from `src/client/app/frameworks/myownframework/index.ts` to make available to the rest of your application.

**Comment by NathanWalker** [comment]
You can then import your new service here and use it to extend or modify the store:
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/src/client/app/frameworks/app/index.ts#L16-L19

You can also move that store definition anywhere in your application. It does not have to exist in `app/index.ts`.

**Comment by Sn3b** [comment]
Thank you for your answer Nathan, I have now read a little more about rxjs store, but it's still nice to have your confirmation. I was espcially trying to modify the least amount of files to make future merges easy.

Cheers! :)
