### ISSUE TITLE
{N} http and response.json() bug? (workaround)

### ISSUE THREAD

**Issue by fourctv** [NathanWalker/angular-seed-advanced#201]
I using @angular/http in my app and when I subscribe to an `http.post` and take the `response.json()` value, it all works fine on web and Electron, but fails in Nativescript.

In {N}, both `response.text()` and `response.json()` return the same string value. It looks like a {N} bug or something.

As a workaround, I've replaced all places where I have `response.json()` by `JSON.parse(response.text())`.

Now everything works as expected.

Hope this helps someone else using {N} http.

**Comment by m-abs** [comment]
Could you provide the JSON structure that fails? We're using `response.json()` without any issues.

**Comment by fourctv** [comment]
I am talking specifically about NativeScript. All other environments, `response.json()` works as expected. NativeScript fails.

Here is a sample response, that fails in NativeScript:

```
{"valid": true, "session":{"options": {"_email": "","_isAdmin": "yes","_isReadOnly": "no","_passwordExpired": "no","_userID": "2"},"groups": ["Admin","Curator","Viewer"],"key": "AjnEDnIznKznQjo52tsF4o1z32z1V2Qzz3zmGzm7Dl3DnCjmQzyi2ys22QD27DmGzmKjmKzmOTo9DoATou1D9zV"}}
```

As I mentioned, if I do `JSON.parse(response.text())` it works.

**Comment by NathanWalker** [comment]
@fourctv please try the latest since master is now using rc.5. Would be curious if you still encounter this issue. Ensure you are clean _after_ merging in latest by:

```
npm run clean
```

Then you can build/run any platform.

**Comment by fourctv** [comment]
@NathanWalker sorry for the delay as it took me a loooong time to get my stuff upgraded to 2.0.0.

I've finally got to test my stuff in {N} and I'm back to this ticket.

Now, with the latest seed, here is what happens:
- response.text() always returns blank
- response.json() new returns the response text, not converted to json!

So now, I'd have to do a `JSON.parse(response.json())`! duh!

Problem is that doing so breaks web/desktop versions.

It is worse now than before!

Is there a venue to voice that kind of issue to Telerik? I could not find any, in fact not even mention of new support for angular2 http. Telerik docs only mention their own Http service.
