### ISSUE TITLE
Migrate to `@angular/router` from now deprecated `@ngrx/router`.

### ISSUE THREAD

**Issue by mko** [NathanWalker/angular-seed-advanced#205]
As per the `@ngrx/router` project, they are deprecating their router in favor of the Angular2 official router. It may be best to do this as part of the migration to RC5 ([Issue #197](https://github.com/NathanWalker/angular2-seed-advanced/issues/197)) since the migration from the ngrx router to Angular2 router assumes RC5.

![screen shot 2016-08-26 at 10 27 47 am](https://cloud.githubusercontent.com/assets/85261/18014452/d6fd4b1a-6b77-11e6-9f16-b9b402f90097.png)

Link to the migration guide: https://github.com/ngrx/router/blob/master/docs/overview/migration.md

**Comment by mko** [comment]
Note: This is already in progress on https://github.com/NathanWalker/angular2-seed-advanced/tree/rc5-upgrade

This issue is intended for tracking the issue for people searching for information on it.

**Comment by NathanWalker** [comment]
This project never used ngrx/router.
At any rate, rc.5 update just landed: https://github.com/NathanWalker/angular2-seed-advanced/pull/208 👍
