### ISSUE TITLE
@angular/core@2.0.0-rc.4 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by swapneshran** [NathanWalker/angular-seed-advanced#207]
While running nativescript app I am getting the below error.

<b>
Unable to install dependencies. Make sure your package.json is valid and all dependencies are correct. Error is: The package @angular/core@2.0.0-rc.4 does not satisfy its siblings' peerDependencies requirements!
</b>

I am using node v 6.4.0  and npm 3.10.6

Thanks
Swapnesh

**Comment by NathanWalker** [comment]
Seed was just updated to use rc.5 via https://github.com/NathanWalker/angular2-seed-advanced/pull/208 and latest everything across the board, please try to clone or pull master again. Reopen if you still have trouble 👍
