### ISSUE TITLE
NgModule RC5 to RC6 module warning.

### ISSUE THREAD

**Issue by lfarran** [NathanWalker/angular-seed-advanced#209]
**Steps to reproduce and a minimal demo of the problem**
Run app in dev mode and open developer tools to see console output. As of master commit da248379812ae2960739834006fcbfd74b699a2f

**Current behavior**
Console output warnings:
"NgModule WebModule uses HomeComponent via "entryComponents" but it was neither declared nor imported! This warning will become an error after final."

"NgModule WebModule uses AboutComponent via "entryComponents" but it was neither declared nor imported! This warning will become an error after final."

**Expected/desired behavior**
Remove warnings as they will become errors in Angular2 RC6

**Comment by NathanWalker** [comment]
Thanks for heads up 👍  Fixed on master now.
