### ISSUE TITLE
TSLint Error for missing env.config

### ISSUE THREAD

**Issue by lfarran** [NathanWalker/angular-seed-advanced#210]
**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_
Run "tsc"

**Current behavior**
Error:
"1 export {EnvConfig} from '../../src/client/app/shared/config/env.config';
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

tools/env/env-config.interface.ts(1,25): error TS2307: Cannot find module '../../src/client/app/shared/config/env.config'."

**Expected/desired behavior**
No errors.

**Comment by NathanWalker** [comment]
@lfarran `env.config` does not exist in this repo as it does in the parent angular2-seed.
Instead it is wrapped in here:
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/src/client/app/frameworks/core/utils/config.ts#L17-L26
It can be used similarly like this:
https://github.com/NathanWalker/angular2-seed-advanced/blob/master/src/client/app/components/app.component.ts#L19
