### ISSUE TITLE
error on npm run git.merge

### ISSUE THREAD

**Issue by TheServat** [NathanWalker/angular-seed-advanced#211]
when i run `npm run git.merge` after fetching it's failed with error:
`fatal: refusing to merge unrelated histories`

**Comment by NathanWalker** [comment]
@sajjad-ser due to the changes with the rc.5 upgrade, I would recommend downloading a new zip, and re-setting up, then just drop your code back in and create a `NgModule` for your code and import that into the `web.module.ts` and the `native.module.ts` respectively.

**Comment by TheServat** [comment]
i use `git fetch upstream && git merge upstream/master --allow-unrelated-histories`  is that ok?

**Comment by NathanWalker** [comment]
Well your error is:

```
fatal: refusing to merge unrelated histories
```

so no it's not ;)

Given these latest changes though, depending on how many changes your project has already, re-setting up may take less time than clearing merge conflicts.

**Comment by TheServat** [comment]
tanks
