### ISSUE TITLE
Firebase Guide Wiki and angular2 RC5 update

### ISSUE THREAD

**Issue by codeback** [NathanWalker/angular-seed-advanced#212]
Now that the project has been updated to RC5, is the guide 'How to integrate Firebase across all platforms'  still valid or it needs to be updated?

In a fresh project, I am having some issues and probably it is because I am doing something wrong when trying to include Firebase in the new structure.

Thanks in advanced.

**Comment by NathanWalker** [comment]
@codeback thanks for pinging an issue for this. There are slight modifications that need to be made and I'll update that wiki soon.
In meantime, you like need to do this with your token:

```
var firebase = require('firebase');

let BOOTSTRAP_PROVIDERS: any[] = [
  ENV_PROVIDERS,
  { 
    provide: FIREBASE, useFactory: () => {
      return firebase;
    } 
  },
  // etc..
];
```

The wiki also uses the `provide` api, but you can just use the literal map as shown above.
Lemme know if this gets you going.

**Comment by codeback** [comment]
That's it! 
Thanks a lot @NathanWalker!! Your solution solves my problem.
