### ISSUE TITLE
Configuration Environment

### ISSUE THREAD

**Issue by jvitor83** [NathanWalker/angular-seed-advanced#213]
@NathanWalker have a question for you! I see that you and me was working at the same problem/feature. The Environment Configuration one.
I see your commit (https://github.com/NathanWalker/angular2-seed-advanced/commit/6796bdfce173a91fed1658605b93f5fbe555a3bf) and i have made another (https://github.com/jvitor83/angular2-seed-advanced-1/commit/58ea36ecc651dfe07725f9c4e999a8c33d5555ab) that solve the same problem, but with a different approach. Was about to make a PR to the seed-advanced, but you make it first.

I want you to take a look and see if its worth to merge using this aproach.

What i need is to build/test against multiples configurations/environments (like the parent seed allows to do with the `npm start -- --conf-env dev`). I have been thinking about how to achieve this.

What i have come in mind was to "**Create a hook at nativescript cli on before-prepare** that":
**1 - Use the existing build task `gulp build.dev --config-env dev` to transpile the `env.config.ts` (using the templateLocals of gulp)**
**2 - And replacing the `env.config.js` generated by the nativescript transpilation by the one generated by gulp (which has the config)**
I have created this and it works.

The final scripts at package.json to run the ns will be something like `npm run clean.dist && cd nativescript && tns emulate android` and the command to run with the specific environment will be **`SET APP_CONFIG_ENV=prod && npm run start.livesync.android`** which **is equivalent to** `npm start -- --conf-env dev` from the parent seed. But it works without executing with the Environment Variable too like `npm run start.livesync.android` as usual (it defaults to the dev).

_Just to clarify: The reason i don't create with the same parameter (like `npm run start.android -- --conf-env dev`) is because the tns cli don't have any 'extended argument' that can be passed through the hook, the only way was using an custom environment variable APP_CONFIG_ENV._

> My goal was to be able to change the config at build time by passing some parameter and with this:
> **`SET APP_CONFIG_ENV=prod && npm run start.livesync.android`**
> I could achieve that like the parent seed:
> **`npm start -- --conf-env prod`**

Can you try and see if its valid or need any change?

Source => https://github.com/jvitor83/angular2-seed-advanced-1
Commit => https://github.com/jvitor83/angular2-seed-advanced-1/commit/58ea36ecc651dfe07725f9c4e999a8c33d5555ab

**Comment by NathanWalker** [comment]
@jvitor83 I really really like this. The only negative is having to exclude the before-prepare hook and keep that on git. I wonder if we should make this a little npm plugin that could be installed into any {N} app? And maybe the environment config path could be configured by some setting in package that the hook would pick up?

Really appreciate this.

**Comment by jvitor83** [comment]
Well... I thought about that (create a npm plugin) but don't know exactly how.... It is too specific to this seed.
My aproach was to use the existing gulp build to reuse the conf-env already implemented.

To create a plugin to every {N} app, we would need to separate the **command to build** (which generate the env-conf.js from the **one that copy the file**... This will end up making the task to start.android/ios in this seed to do the build before (which i think is not a good thing since will make everyone to use the task and not to directly use `tns emulate android`...).

What you have thinking is to give the {N} hook some kind of path that will be "inserted" at the generated files right? 
But what i don't know is how to make the app runtime to load this file? _(Which allow to get those configs from a global variable)_
Or maybe we don't need to? Leaving this to the dev to import?

Or we create something that get the config from a SO Environment Variable? Like `set APP_CONFIG_ENV={ key:"value", key2:"value" } && tns emulate android` ?

It is a little blurry to me yet what approach to follow or even if worth it.
What do you think?

**Comment by NathanWalker** [comment]
Feel free to continue discussion here, just closing to cleanup outstanding issues. I believe we will leave the config how it has at moment. Can definitely revisit.
