### ISSUE TITLE
Better Unit Testing Workflow - maybe wallabyjs?

### ISSUE THREAD

**Issue by VladimirMakaev** [NathanWalker/angular-seed-advanced#214]
Currently it's possible to do _karma.watch_ in one window and _watch.test_ in another. That would effectively automatically run unit tests when something changes.

However there the following problems that make the process far from ideal:
When I change a test the whole pipeline of building everything is executed which triggers multiple times karma rerun which ruins productivity in TDD like workflow.  Ideally if a test changed then only rebuild test files, if code changed then don't rebuild tests. So that the feedback from unit tests is as fast as possible.

Karma also needs to run only once compilation is finished and not multiple times along the way

Maybe I'm doing something wrong and it's not how it supposed to work. Any help appreciated.

**Comment by spicemix** [comment]
This is better: https://wallabyjs.com

**Comment by VladimirMakaev** [comment]
@NathanWalker Do you have any plans to integrate wallbyjs in the seed?

**Comment by NathanWalker** [comment]
It does fall inline with the goals of the seed to provide enhanced testing support so I'm definitely open to it. No plans at the moment, but I may retitle with wallabyjs support.
Here's a webpack sample:
https://github.com/wallabyjs/wallaby-ng2-test-seed

**Comment by NathanWalker** [comment]
@VladimirMakaev there is a new dev command for TDD style on latest master:
npm run start.deving

👍
