### ISSUE TITLE
How to override component specific css

### ISSUE THREAD

**Issue by TO-mkegler** [NathanWalker/angular-seed-advanced#215]
Hi, 
I hope this is the right place for this question, if not please point me in the right direction!

I injected a custom css file (my.css) via project.config.ts APP_ASSETS.
This is working as intended.

> `this.APP_ASSETS = [`
> `...this.APP_ASSETS,`
> `{src: '${this.CSS_SRC}/my.css', inject: true, vendor: false},`
> `];`

Now the component specific css files override my custom css (which is aswell, [as far is I understand](https://github.com/mgechev/angular2-seed/issues/779), intended). 
Is there any way to implement my custom (global) css so that it overrides the component specific styles?

Maybe there is some basic concept I haven't understood, I'm quite new to angular and this seed project.

Thanks a lot in advance for any advice..

**Comment by NathanWalker** [comment]
You may have found an answer by now, but it is the way the angular component design works. Hope you are enjoying Angular 2 development!
