### ISSUE TITLE
Trying to install Auth0 angular2-jwt

### ISSUE THREAD

**Issue by nigel-dewar** [NathanWalker/angular-seed-advanced#218]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

I have spent a few hours trying to get angular2-jwt working with seed-advanced.

_What steps should we try in your demo to see the problem?_

**Current behavior**

I dont understand how modules are loaded in angular seed. There are config files all over the place. Where is someone supposed to load in stuff???

**Expected/desired behavior**

Doco for loading in external dependencies, modules etc

**Other information**

**Comment by NathanWalker** [comment]
Please refer to parent wiki for instructions on how to handle external dependencies. This this is merely an extension to that seed, the process is the same:
https://github.com/mgechev/angular2-seed/wiki
