### ISSUE TITLE
PouchDB - error during installation - UNMET PEER DEPENDENCY rxjs@5.0.0-beta.11

### ISSUE THREAD

**Issue by mardale19** [NathanWalker/angular-seed-advanced#220]
Errors during PouchDB module installation

To reproduce run the command: npm install pouchdb --save

Errors:
`-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.11

I tried the same steps on "angular2-seed" and I didn't have any issue.

Below my enviroment:

WIN 7
{ 'angular2-seed-advanced': '0.0.0',
  npm: '3.10.3',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.5.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.1.281.81',
  zlib: '1.2.8' }

Any help to solve the issue?

**Comment by NathanWalker** [comment]
Latest master uses rc.6 and rxjs beta.11 so this is no longer applicable.
