### ISSUE TITLE
Update of gulp-tslint removes format

### ISSUE THREAD

**Issue by jabaa** [NathanWalker/angular-seed-advanced#221]
**Steps to reproduce and a minimal demo of the problem**
Clone a clean copy of this project and insert some tslint-warnings like:
- change src/client/app/components/home/home.components.ts:2 to `import { Store } from "@ngrx/store";`
- run `gulp tslint`

**Current behavior**
Warning is thrown without colors and format. In my case the linting process even crashes with some errors and stops the build process but I can't produce a mwe.

**Expected/desired behavior**
Formatted and colored warnings like with `gulp-tslint@4.3.3` without errors in `gulp-tslint`

**Other information**
A change in `package.json:104` to `"gulp-tslint": "^4.3.3",` corrects this behavior.

**Comment by NathanWalker** [comment]
We are now at 6.1.2.

**Comment by jabaa** [comment]
The update to gulp-tslint@6.1.2 didn't help. I'm working with an older version of this project with gulp-tslint@4.3.3 and the lint messages are colored and styled. The lint messages in the current version of this project are grey and not styled. The configuration with gulp-tslint@4.3.3 was correct and the styling of the  current gulp-tslint doesn't work for me.

**Comment by jabaa** [comment]
That's how it looked in an earlier version with gulp-tslint@4.3.3
![433lint](https://cloud.githubusercontent.com/assets/6706626/19468888/27080e7c-9519-11e6-87e0-e0c5fdcfb5aa.png)

And that's how it looks now with gulp-tslint@6.1.2
![currentlint](https://cloud.githubusercontent.com/assets/6706626/19468904/3acc62fa-9519-11e6-99fe-7febdcd923b3.png)
