### ISSUE TITLE
NativeScript Webpack support?

### ISSUE THREAD

**Issue by anton-staroverov** [NathanWalker/angular-seed-advanced#222]
NativeScript team announced Webpack as a primary tool for Nativescript: https://www.nativescript.org/blog/announcing-nativescript-2.2.

How about to use it in your seed?

**Comment by NathanWalker** [comment]
@tonystar 

```
cd nativescript
npm i nativescript-dev-webpack --save-dev
```

Then you will need to modify your components to _not_ use `moduleId: module.id` and change `templateUrl` to true relative app, for example:

before:

```
@BaseComponent({
  moduleId: module.id,
  selector: 'sd-home',
  templateUrl: 'home.component.html',
  styleUrls: ['home.component.css']
})
```

after:

```
@BaseComponent({
  // moduleId: module.id,
  selector: 'sd-home',
  templateUrl: './app/components/home/home.component.html',
  styleUrls: ['./app/components/home/home.component.css']
})
```

Then to build:

Ensure you are in the `nativescript` directory when running these commands.
- iOS: `WEBPACK_OPTS="--display-error-details" tns build ios --bundle`
- Android: `WEBPACK_OPTS="--display-error-details" tns build android --bundle`

Notice your final build will be drastically smaller. In some cases 130 megs > ~30 megs. 👍 

A note will be added to README soon about this.

**Comment by anton-staroverov** [comment]
Thanks Nathan! Will try and let you know.

Just couldn't imagine web development today w/o Webpack ;)

**Comment by jlooper** [comment]
one thing that keeps biting me is that the paths that are necessary to the webpacking breaks the production build process...not quite sure why, let me take a look. Bites me every time!
