### ISSUE TITLE
Angular Universal integration

### ISSUE THREAD

**Issue by MitkoTschimev** [NathanWalker/angular-seed-advanced#228]
Do you have any plans to integrate angular universal too?

I like this seed so much and this is the last thing what i am missing to have a big platform solution.

**Comment by NathanWalker** [comment]
Hi @tfiwm thank you.
Angular Universal is awesome.
There was discussion about this here: 
https://github.com/NathanWalker/angular2-seed-advanced/issues/61
The problem with integrating here is the extra tooling needed to provide an out of box setup, not to mention to maintain here.

**Comment by MitkoTschimev** [comment]
Thanks a lot! The discussion was good and productive. Is there already a user project which uses this seed as fork + NG universal? Do you know something? 

Thx a lot for this awesome seed!!!

**Comment by NathanWalker** [comment]
I'm not aware of any at moment however my day job needs it right now so I may give it a go soon.

**Comment by MitkoTschimev** [comment]
i tried to integrate it but at the end the biggest problem was, that they still not support lazy load and i stop with it till they will announce something ;)

**Comment by kadosh1000** [comment]
@NathanWalker have you managed to combine NG universal into the seed?

**Comment by MitkoTschimev** [comment]
I think we should wait until angular will have it finally in the core maybe with angular@4.

**Comment by NathanWalker** [comment]
Feel free to continue discussion here, just closing to cleanup outstanding issues. It's likely Universal would not be integrated here directly however if anyone has a fork with the integration please share 👍

**Comment by patrickmichalina** [comment]
Anyone looking for a universal starter, can checkout one here:

https://github.com/patrickmichalina/fusebox-angular-universal-starter
