### ISSUE TITLE
rxjs not found when merging latest upstream changes

### ISSUE THREAD

**Issue by codeback** [NathanWalker/angular-seed-advanced#229]
After merging the latest upstream changes, I'm finding an error when starting the web project:
XHR error (404 Not Found) loading http://localhost:5555/node_modules/rxjs.js

It's possible that I've accidentally removed something while resolving the conflicts.
I've reviewed the seed.config file and everything seems ok. 

Any idea?

**Comment by NathanWalker** [comment]
Please pull latest master, then:

```
npm run clean
```

Please close if that gets ya going.

**Comment by codeback** [comment]
I've done that and I'm still having the same issue.

Apart from the seed.config file, in which files should I look into?

**Comment by NathanWalker** [comment]
@codeback you may have been running into what was going on here:
https://github.com/NathanWalker/angular2-seed-advanced/issues/236

Please pull latest master (fixed just pushed in) and do a `npm run clean` after pulling those in and give it a try.

**Comment by NathanWalker** [comment]
If you still have trouble, try downloading latest seed and follow this guide for your project before making any changes:
https://github.com/NathanWalker/angular2-seed-advanced#how-best-to-use-for-your-project

Then just move your custom code back in.

**Comment by codeback** [comment]
Solved. The problem was that I had wrong imports in my code: 
- Wrong: import { Observable } from 'rxjs';
- Ok: import { Observable } from 'rxjs/Observable';

Thank you very much @NathanWalker
