### ISSUE TITLE
Property 'assign' does not exist on type 'ObjectConstructor'.

### ISSUE THREAD

**Issue by ringodotnl** [NathanWalker/angular-seed-advanced#234]
1. Pull git
2. npm install, 
3. npm run start.livesync.android

Getting:
Found peer TypeScript 1.8.10
app/app/frameworks/i18n/services/multilingual.service.ts(25,22): error TS2665: Module augmentation cannot introduce new names in the top level scope.

app/app/frameworks/i18n/services/multilingual.service.ts(41,21): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.

**Comment by jlooper** [comment]
I'd like to prioritize this, submitting PR as it's a pretty easy fix

**Comment by ringodotnl** [comment]
Great soved

**Comment by ringodotnl** [comment]
Issue seems to be back after 'npm start' fix. 

app/app/frameworks/i18n/services/multilingual.service.ts(35,21): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.

This commit https://github.com/NathanWalker/angular2-seed-advanced/commit/d4fa661a262fa8f3d591c0677e2804b64c6399da seems to be reverted

**Comment by netwiser** [comment]
Same here, npm run start.ios has the same error.

**Comment by llwt** [comment]
@NathanWalker is there any way to specify the `es6` lib option so that we don't need to use `(<any>Object).assign`? I've tried adding it to the `tsconfig` under the nativescript directory but the build seems to ignore the lib compiler option.

**Comment by llwt** [comment]
@NathanWalker After playing around a bit changing the `nativescript/references.d.ts` to the following removes the build error with `Object.assign`:
```
/// <reference path="../node_modules/tns-core-modules/tns-core-modules.es6.d.ts" />
/// <reference path="../node_modules/typescript/lib/lib.es6.d.ts" />
```

I was wondering if using these reference files instead is actually "correct" or if this introduces extra types for unsupported functions/removes definitions for implementations that are supported.

**Comment by ar000n** [comment]
seems we have to specify type `<any>` to Object assignment.Like `(<any>Object).assign`.
