### ISSUE TITLE
npm run start not working

### ISSUE THREAD

**Issue by ringodotnl** [NathanWalker/angular-seed-advanced#236]
error: (404 Not Found) loading http://localhost:5555/node_modules/traceur.js(…)

**Comment by jakubikan** [comment]
got the same error. 

```
GET http://localhost:5555/node_modules/traceur.js 404 (Not Found)
Error: Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/traceur.js
        at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:5555/node_modules/zone.js/dist/zone.js?1474114983696:628:29)
        at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1474114983696:225:37)
        at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1474114983696:125:47)
        at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1474114983696:293:33)
    Error loading http://localhost:5555/node_modules/traceur.js
    Error loading http://localhost:5555/node_modules/@ngrx/store/index.js as "@ngrx/store" from http://localhost:5555/app/components/home/home.component.js "Report this error at https://github.com/NathanWalker/angular2-seed-advanced/issues"
```

Seems to be something with ngrx store, but seems very strange that it tries to load the js directly out of `node_modules` without a subdirectory.

**Comment by esteban-url** [comment]
there are multiple possible reasons for this failure,

one of them is multiple line comments as described here: http://stackoverflow.com/a/37181985 and here https://github.com/systemjs/systemjs/issues/1408

there is also this: http://stackoverflow.com/a/37023422

I tried searching for `/*` but could find anything I also tried updating the systemjs version, but still got the error.

further information: https://github.com/angular/angular/issues/11358

**Comment by NathanWalker** [comment]
This was related to the new ngrx/store being distributed with umd bundles.
The fix is now on master 👍

**Comment by ringodotnl** [comment]
Cheers working
