### ISSUE TITLE
Doesn't inject or copy polymer node module when running npm start

### ISSUE THREAD

**Issue by freemo** [NathanWalker/angular-seed-advanced#238]
After 2 days of wrestling with this problem I am convinced it must be a bug somewhere. What I am trying to do is simple. I want a module that I added to the package.json to show up and be accessible to the server when i run "npm start". I have done this successfully with a few packages but I cant get it to work for the "@polymer/paper-card" module. I also wish to inject a link to this module in the index.html but I never seem to get this far. 

I tried adding the following lines to my project config after installing the module:

```
    this.SYSTEM_CONFIG['packageConfigPaths'] = [
      ...this.SYSTEM_CONFIG['packageConfigPaths'],
      // other stuff here omited
      `${this.APP_BASE}node_modules/@polymer/*/package.json`
    ];
    this.SYSTEM_CONFIG.paths['@polymer/paper-card'] = `${this.APP_BASE}node_modules/@polymer/paper-card/paper-card.html`;
    this.SYSTEM_CONFIG.paths['@polymer/paper-card/*'] = `${this.APP_BASE}node_modules/@polymer/paper-card/*`;
    this.SYSTEM_CONFIG['packages']['@polymer/paper-card'] = {
      main: 'paper-card.html',
      defaultExtension: 'html'
    };


    this.SYSTEM_BUILDER_CONFIG['packageConfigPaths'] = [
      // other stuff here omited.
      `${this.APP_BASE}node_modules/@polymer/*/package.json`
    ];
    this.SYSTEM_BUILDER_CONFIG['packages']['@polymer/paper-card'] = {
      main: 'paper-card.html',
      defaultExtension: 'html'
    };
```

When I start up npm with `npm start` the server doesnt load, producing some errors. When I traverse to the node_modules directory being hosted (viewed through the inspector in chromium) I notice while most of my other modules are being loaded and injected just fine, this particular one is completely absent. It is however present in the root of the project in the node_module directory there.

I attempted a bit of a hack solution by adding the following task to gulp (modeled after the desktop.libs.ts task):

```
import * as gulp from 'gulp';
import {join} from 'path';
import Config from '../../config';

export = () => {
  let src = [
    'node_modules/@polymer/**/*'
  ];
  gulp.src(src, { base: 'node_modules' })
    .pipe(gulp.dest(join(Config.APP_DEST + '/node_modules')));
};
```

While this did produce the module in the node_modules subdirectory of the dist folder, when I run "npm start" it still failed to show up on the server itself according to the inspector and the application continues to error out.

**Comment by NathanWalker** [comment]
Feel free to continue discussion here, just closing to cleanup outstanding issues.
