### ISSUE TITLE
Routing no longer properly works when trying to access a child route in typing the url rather then clicking a link

### ISSUE THREAD

**Issue by rernens** [NathanWalker/angular-seed-advanced#239]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

**1. add a third component to the seed ie Test component**

test.component.ts 

```
import { Component } from '@angular/core';

/**
 * This class represents the lazy loaded AboutComponent.
 */
@Component({
  moduleId: module.id,
  selector: 'sd-test',
  templateUrl: 'test.component.html',
  styleUrls: ['test.component.css']
})
export class TestComponent { }
```

test.component.html

```
<p>
  Angular 2 Seed Test is used to check whether routing works when url is entered in the navigation bar .
</p>

<h2>Test Component</h2>
<p>
  lorem lipsum ....
</p>

<a [routerLink]="['./']" [routerLinkActive]="['router-link-active']" [routerLinkActiveOptions]="{exact:true}">Test 1</a>
<a [routerLink]="['./test2']" [routerLinkActive]="['router-link-active']" [routerLinkActiveOptions]="{exact:true}">Test 2</a>

<router-outlet></router-outlet>
```

**2. add 2 sub components named test1 and test2** 

test.route.ts

```
import { Route } from '@angular/router';
import { TestComponent } from './index';
import { Test1Component } from './test1/test1.component';
import { Test2Component } from './test2/test2.component';

export const TestRoutes: Route[] = [
  {
    path: 'test',
    component: TestComponent,
    children: [
      { path: '', component: Test1Component },
      { path: 'test2', component: Test2Component }
    ]
  }
];
```

**3. test that navigation works properly using the links and watch the url properly changing in the navigation bar to reflect routing**

_What steps should we try in your demo to see the problem?_
1. goto to test1 or test 2 view
2. copy the url displayed in the navigation bar
3. open a new tab, paste the the copied url and click enter to access the page

**Current behavior**

page fails to load with the following error

```
GET http://localhost:5557/test/system-config.js                                                    
GET http://localhost:5557/test/system-config.js 404 (Not Found)     
GET http://localhost:5557/test/main.web 404 (Not Found)54 
Error: Error: XHR error (404 Not Found) loading http://localhost:5557/test/main.web(…) 
"Report this error at https://github.com/NathanWalker/angular2-seed-advanced/issues"
```

**Expected/desired behavior**

to properly load the page as it should

**Other information**
- was working properly prior to seed update with rc.5 and following
- is working properly with Minko Gechev's angular2-seed

**Comment by rernens** [comment]
further investigation shows that in the index.html file changing the 

`<base href="<%= APP_BASE %>">`

to

`<base href="/">`

fixes the issue.

**Comment by m-abs** [comment]
@NathanWalker Is there a better way to fix this? I tried to set APP_BASE = '/' in the `config` but that breaks the project.

**Comment by rernens** [comment]
@m-abs use my method. Leave APP_BASE = "" and change the index file to be 

`<base href="/">`

May be not the best and most elegant way but the project works and it fixes the issue.

If someone has a better approach, let us know.

**Comment by kbrandwijk** [comment]
I'm guessing Electron doesn't work with `<base href="/">`

**Comment by rernens** [comment]
@kbrandwijk haven't tested it. Electron is not a target platform so far for me but it will come. I'll check as soon as I have some time.

**Comment by NathanWalker** [comment]
Works on master now.

**Comment by Sn3b** [comment]
Hi sorry if this is an old post, but I'm facing something similar...
Setting `this.APP_BASE = '/';` in `project.config.ts` works fine, so then my web app works, but electron app doesn't...

Should I simply remove it for compiling the electron app?
