### ISSUE TITLE
Feature request: automatically determine input for desktop.libs task

### ISSUE THREAD

**Issue by kbrandwijk** [NathanWalker/angular-seed-advanced#243]
Currently, all node_modules that need to be 'copied' for the desktop need to be specified manually in desktop.libs.ts. However, from what I can determine, all information about the dependencies and their locations is already specified in the included configuration.

I'm looking for a way in which the desktop.libs task can determine automatically, based on the configuration on the dependencies, which files to copy. Would this be doable?

**Comment by kbrandwijk** [comment]
I updated desktop.libs.ts to automatically add the dependencies and assets that were added to project.config.ts, by adding this line, and the necessary include:

```
include { relative, join } from 'path';

src.push(...Config.DEPENDENCIES.map(x => relative(Config.PROJECT_ROOT, x.src)));
```

It's not perfect (Config.DEPENDENCIES actually includes the hardcoded NPM_DEPENDENCIES values from seed.config.ts), but at least you don't have to manually add any dependencies or assets you add to project.config.ts to desktop.libs.ts.

**Comment by jvitor83** [comment]
Amazing. You could do a PR with this!

**Comment by kbrandwijk** [comment]
Will do.
-edit- Done.
