### ISSUE TITLE
BaseComponent Template rendering issue when using an observer service

### ISSUE THREAD

**Issue by ringodotnl** [NathanWalker/angular-seed-advanced#245]
I noticed that when I use the baseComponent. The template renders before the observer service completes and I cannot display the data in the template.But how ever when i changed the BaseComponent to Component every thing works fine.

See issue https://github.com/NathanWalker/angular2-seed-advanced/issues/115

These seems to be still a problem.

**Comment by NathanWalker** [comment]
@ringodotnl could you provide your component setup with the observable and view setup?
That will help me help you 👍

**Comment by NathanWalker** [comment]
Closing due to nonresponse.
