### ISSUE TITLE
Missing file: src/client/web.module.ngfactory.ts

### ISSUE THREAD

**Issue by zieve** [NathanWalker/angular-seed-advanced#249]
**Steps to reproduce and a minimal demo of the problem**

```
Checkout project
npm i
npm start
npm serve.docs
```

**Current behavior**

```
Starting 'build.docs'...
TypeDoc 0.4.5
Using TypeScript 1.8.10 from C:\Users\User\dev\angular2-seed-advanced\node_modules\typedoc\node_modules\typescript\lib

C:/Users/User/dev/angular2-seed-advanced/src/client/main.web.prod.ts(7)
Cannot find module './web.module.ngfactory'.
'build.docs' errored after 3.52 s
Error in plugin 'gulp-typedoc'
Message:
    Failed to generate load TypeDoc project.
```

**Expected/desired behavior**
main.web.prod.ts needs to reference a file that exists. web.module.ngfactory.ts needs to be included in the repo

**Comment by m-abs** [comment]
`*.ngfactory.ts`files are generated by `@angular/compiler-cli` but why the seed project needs it I don't know.

**Comment by NathanWalker** [comment]
Correct, it's used for the compiler AoT build. You can comment out when building docs in meantime.
