### ISSUE TITLE
How do I know I am running under NativeScript

### ISSUE THREAD

**Issue by fourctv** [NathanWalker/angular-seed-advanced#251]
The web/desktop builds allow for conditional compilation/execution based on the target environment, like:

```
                    if (String('<%= TARGET_DESKTOP %>') === 'true') {
                        .. do something for desktop environment only
                    }
```

Is there something similar I can use to indicate I'm running under {N}?

I need that because {N} angular/http is still bogus, as the http response.json() fails, and I need to do a JSON.parse() on the response. But only for NativeScript environments.

**Comment by kbrandwijk** [comment]
See https://github.com/NathanWalker/angular2-seed-advanced/blob/master/src/client/app/frameworks/i18n/components/lang-switcher.component.ts#L35-L41 for an example, as mentioned in the readme. In short, use `Config.IS_MOBILE_NATIVE()`.

**Comment by NathanWalker** [comment]
{N} angular/http works great. I use it a lot :)
You might post what is causing you issue. In all cases I have seen, its related to the API and/or you need iOS 9 apptransportsecurity added to Info.plist.

**Comment by fourctv** [comment]
I am connecting to `localhost`, so apptransportsecurity is not an issue.

What type of http request do you use? 
I am using ng2 `http.post`,  to receive a json response, and use something like this:

```
     http.post(...)
       .subscribe ( response => {
           let responseData = response.json();
           ....
           });
```

Running web/desktop, `responseData` has the parsed json object. Works like a charm.

But trying the same code in {N}, `responseData` returns the json string, not a parsed object. If in {N} I replace that line by `let responseData = JSON.parse(response.json());`, then everything works.

Thus my question on how to determine if running mobile or not.

Is there anything wrong with what I'm doing?

**Comment by NathanWalker** [comment]
As @kbrandwijk mentioned, you can use:

```
if (Config.IS_MOBILE_NATIVE()) {
  // on nativescript
}
```

You may try setting headers on that post to ensure it is json type.
