### ISSUE TITLE
ATTN: Using bleeding edge Angular: 2.1.0-rc.0 on master...  {N} build note:

### ISSUE THREAD

**Issue by NathanWalker** [NathanWalker/angular-seed-advanced#252]
When updating to latest master, you will notice these warnings after running `npm i`:

```
npm WARN @ngrx/effects@2.0.0 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN ng2-translate@3.1.0 requires a peer of @angular/core@~2.0.0 but none was installed.
npm WARN ng2-translate@3.1.0 requires a peer of @angular/http@~2.0.0 but none was installed.
npm WARN @ngrx/store@2.2.1 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN @angular/platform-server@2.0.2 requires a peer of @angular/core@2.0.2 but none was installed.
npm WARN @angular/platform-server@2.0.2 requires a peer of @angular/common@2.0.2 but none was installed.
npm WARN @angular/platform-server@2.0.2 requires a peer of @angular/compiler@2.0.2 but none was installed.
npm WARN @angular/platform-server@2.0.2 requires a peer of @angular/platform-browser@2.0.2 but none was installed.
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/compiler@2.0.2 but none was installed.
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/core@2.0.2 but none was installed.
npm WARN codelyzer@1.0.0-beta.1 requires a peer of @angular/compiler@^2.0.2 but none was installed.
npm WARN codelyzer@1.0.0-beta.1 requires a peer of @angular/core@^2.0.2 but none was installed.
```

Web builds and desktop will run fine. Master is using this bleeding edge tag to circumvent this issue:
https://github.com/angular/angular/issues/10770#issuecomment-250071307

This temporarily causes an issue with {N} `tns` build command which will cause the {N} app build/run to fail. (related to this: https://github.com/NativeScript/nativescript-cli/issues/2056) A fix will come soon for this but please take note of this if updating to latest master.

**Comment by bbultman** [comment]
Hey, saw the issue you opened for this on the nativescript repo, are you aware of any progress?

**Comment by OussaZaki** [comment]
@NathanWalker I just hit this issue this morning, Is there any stable commit that you recommend where {N} works fine ?

**Comment by bbultman** [comment]
I've had some success with: 0045053

**Comment by bbultman** [comment]
For those not tracking the issue on nativescript/nativescript-cli, this is now solved as of the latest merge to master (70ebb32ad0d4503e48d86f95ed8673f5e602b6ef).

So to get it running now, until the next release:

`npm uninstall -g nativescript`
`git clone git@github.com:NativeScript/nativescript-cli.git`
`cd nativescript-cli`
`npm i`
`grunt`
`npm link`

And then you'll be up and running.

**Comment by NathanWalker** [comment]
@bbultman thank you. For now, anyone needing to develop and run their {N} app with latest master, please use those steps.

Once next {N} cli version has been released, I'll update the seed and we can close this.

**Comment by kbrandwijk** [comment]
As far as I know, the master branch is linked to the next tag, so just using `npm install nativescript@next`should also work...

**Comment by salauddinShaikh** [comment]
@**bbultman**  grunt task throwing warning  "You may wish to enable the suppressImplicitAnyIndexErrors grunt-ts option to allow dynamic property access by index.  This will suppress TypeScript error TS7017. "
I tried with setting  **suppressExcessPropertyErrors** to  true.
Then npm link throwing error of Cannot find module **'./common/verify-node-version'**

**Comment by NathanWalker** [comment]
Closing in favor of https://github.com/NathanWalker/angular-seed-advanced/issues/266

Using bleeding edge is technically not a problem any longer as the scripts have been updated with the workaround:
https://github.com/NathanWalker/angular-seed-advanced/blob/master/package.json#L49

Currently, the {N} build is affected by this:
https://github.com/NativeScript/nativescript-angular/issues/493
...which will be fixed momentarily.
