### ISSUE TITLE
build.prod doesn't work on windows

### ISSUE THREAD

**Issue by lucasvanhalst** [NathanWalker/angular-seed-advanced#255]
Continuation of #250 
Issue persists on windows. Works fine on ubuntu however. 

**Steps to reproduce and a minimal demo of the problem**
run `build.prod` on windows

**Current behavior**
It looks like it is searching for main.web.js in the `node_modules` folder instead of the parent folder.

```
[18:46:58] Error on fetch for dist\tmp\main.web.js at file:///C:/Users/user/git/angular2-seed-advanced/node_modules/dist\tmp\main.web.js
        Error: ENOENT: no such file or directory, open 'C:\Users\user\git\angular2-seed-advanced\node_modules\dist\tmp\main.web.js'
    at Error (native)
[18:46:58] 'build.prod' errored after 31 s
[18:46:58] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on fetch for dist\tmp\main.web.js at file:///C:/Users/user/git/angular2-seed-advanced/node_modules/dist\tmp\main.web.js
        ENOENT: no such file or directory, open 'C:\Users\user\git\angular2-seed-advanced\node_modules\dist\tmp\main.web.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open 'C:\Users\user\git\angular2-seed-advanced\node_modules\dist\tmp\main.web.js'
Stack:
Error on fetch for dist\tmp\main.web.js at file:///C:/Users/user/git/angular2-seed-advanced/node_modules/dist\tmp\main.web.js
        Error: ENOENT: no such file or directory, open 'C:\Users\user\git\angular2-seed-advanced\node_modules\dist\tmp\main.web.js'
    at Error (native)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build.prod"
npm ERR! node v6.6.0
```

**Expected/desired behavior**
Should build without any issues

**Other information**
node 6.6.0

**Comment by ro-** [comment]
changing **base** to **baseURL** in the SYSTEM_BUILDER_CONFIG in seed.config.ts fixed this for me

as far as I can tell in "systemjs-builder": "0.15.32" thats the correct property name

**Comment by ro-** [comment]
try changing the paths value in SYSTEM_BUILDER_CONFIG so it uses join. I think its a slash issue, hence it working on *nix

SYSTEM_BUILDER_CONFIG: any = {
    defaultJSExtensions: true,
    base: this.PROJECT_ROOT,
    packageConfigPaths: [
      join('node_modules', '_', 'package.json'),
      join('node_modules', '@angular', '_', 'package.json')
    ],
    paths: {
      [join(this.TMP_DIR, '_')]: `${this.TMP_DIR}/_`,
      'node_modules/_': 'node_modules/_',
      '_': 'node_modules/_'
    },

**Comment by NathanWalker** [comment]
@lucasvanhalst did @ro- suggestion work for you?

**Comment by lucasvanhalst** [comment]
No it didn't. but whatever, I'm not going to use it on windows anyway

**Comment by xLama** [comment]
@NathanWalker @ro-  suggestions It works perfect but he made a mistake typing:. He forgot the *

seed.config.ts:

``` ts
[join(this.TMP_DIR, '')]: `${this.TMP_DIR}/`,
```

seed.config.ts:

``` ts
[join(this.TMP_DIR, '*')]: `${this.TMP_DIR}/`,
```

Checked on Windows 10 and working fine.

**Comment by ro-** [comment]
@xLama  good catch, reviewing it now my line is

`[join(this.TMP_DIR, '*')]: '${this.TMP_DIR}/*'`

possibly just a bad copy+paste

**Comment by NathanWalker** [comment]
@ro- @xLama @lucasvanhalst that line is on master btw (the join is not absolutely necessary):
https://github.com/NathanWalker/angular-seed-advanced/blob/master/tools/config/seed.config.ts#L436

**Comment by NathanWalker** [comment]
OH wait actually the join is needed, pushing to master with that fix in moment 👍

**Comment by NathanWalker** [comment]
Ok that fix is now on master, thanks again for the clarity.
