### ISSUE TITLE
Expected a source file with stats

### ISSUE THREAD

**Issue by sqwk** [NathanWalker/angular-seed-advanced#259]
Running `npm run build.prod` runs into the following problem:

```
[18:08:04] Starting 'build.html_css'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Expected a source file with stats
```

I am using the latest version of angular2-seed-advanced and have enabled the scss support in `project-config.ts` using `this.ENABLE_SCSS = true`;

`npm start` or `npm run start.desktop` work fine.

**Comment by aaweb** [comment]
Same issue here :(

**Comment by sankaran85** [comment]
any update on this issue ?

**Comment by NathanWalker** [comment]
@sankaran85 @sqwk @aaweb This is now fixed on master, thank you for reporting it 👍
