### ISSUE TITLE
Runtime error "(SystemJS) __decorate is not defined..."

### ISSUE THREAD

**Issue by fourctv** [NathanWalker/angular-seed-advanced#260]
After merging the latest seed I am no getting the error above in my project.

I'm using VSCode on OSX.

For some reason the generated .js files are missing `__metadata` and `__decorate` declarations on all component files, including those in the seed like console service or log service.

Funny that on the same environment, the original seed transpiles fine. That's how I found out about the missing `__decorate`, by comparing code generated in my project and the original seed.

So, there is some setting in my project that causes typescript compiler not to generate that code.
I compared all the .json config files and they are the same.

In fact, no change was detected in any of the config files from the merge.

Any suggestions or hints as to what might be causing this issue will be highly appreciated, as I am at loss here chasing that :(

**Comment by NathanWalker** [comment]
Try doing:
npm run clean

Curious if you may have some old stray js files around interfering.

**Comment by NathanWalker** [comment]
@fourctv curious if you tried the above and if it helped you get past the above?

**Comment by fourctv** [comment]
@NathanWalker yes I did run clean but that did not help. I have not had time to look into that yet. I'll keep you posted here.

**Comment by fourctv** [comment]
@NathanWalker I tried it again, to do `npm run clean` and also delete `dist` folder, and that error is now gone!
Not sure what happened first time I tried run clean, but all good now.

Closing this.
