### ISSUE TITLE
npm run start.android giving error?

### ISSUE THREAD

**Issue by salauddinShaikh** [NathanWalker/angular-seed-advanced#262]
Unable to install dependencies. Make sure your package.json is valid and all dependencies are correct. Error is: The package @angular/core@2.1.0-beta.0 does not satisfy its siblings' peerDependencies requirements!

UNMET PEER DEPENDENCY @angular/common@2.1.0-beta.0
 +-- UNMET PEER DEPENDENCY @angular/compiler@2.1.0-beta.0
 +-- UNMET PEER DEPENDENCY @angular/core@2.1.0-beta.0
 +-- UNMET PEER DEPENDENCY @angular/http@2.1.0-beta.0 
`-- UNMET PEER DEPENDENCY @angular/platform-browser@2.1.0-beta.0

**Comment by uno-de-piera** [comment]
Same issue.

**Comment by NathanWalker** [comment]
Please see this:
https://github.com/NathanWalker/angular2-seed-advanced/issues/252
