### ISSUE TITLE
Adding "ng2-bootstrap & moment" through SYSTEM_CONFIG.paths no longer works

### ISSUE THREAD

**Issue by rernens** [NathanWalker/angular-seed-advanced#269]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

I downloaded the most recent seed version for using it for a new project.
ng2-bootstrap being standard in all my projects I have added ng2-bootstrap as always

```
npm install ng2-bootstrap --save
npm install moment --save
```

and have added the following lines to the  /tools/config/project.config.ts file

```
    this.SYSTEM_CONFIG_DEV.paths['moment'] = `${this.APP_BASE}node_modules/moment/moment.js`;
    this.SYSTEM_CONFIG_DEV.paths['ng2-bootstrap'] = `${this.APP_BASE}node_modules/ng2-bootstrap/bundles/ng2-bootstrap.umd.js`;

    this.SYSTEM_BUILDER_CONFIG.packages['moment'] = {
      main: 'moment.js',
      defaultExtension: 'js'
    };
    this.SYSTEM_BUILDER_CONFIG.packages['ng2-bootstrap'] = {
      main: 'ng2-bootstrap.js',
      defaultExtension: 'js'
    };
```

then replacing the sample module import in web.module.ts  by my application module that imports a shared module that imports the ng2-bootstrap modules required.

_What steps should we try in your demo to see the problem?_

see above

**Current behavior**

running npm start throw the following error

```
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:57 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/moment.js(…) "Report this error at https://github.com/NathanWalker/angular-seed-advanced/issues"
```

it looks like the additional SYSTEM_CONFIG.packages definitions are not taken into account.

in fact the system-config.js is not rebuilt even after terminating  the server et relaunching npm start

**Expected/desired behavior**

npm start should rebuild the the systemp-config.js file if any of the config files are changed

**Other information**

I have tried adding the definitions to the advanced.seed.config but same pb.

**Comment by NathanWalker** [comment]
@rernens adjust your `profect.config` to _just_ this:

```
// dev
this.SYSTEM_CONFIG.paths['moment'] = `${this.APP_BASE}node_modules/moment/moment`;

// prod
this.SYSTEM_BUILDER_CONFIG.paths['moment'] = `node_modules/moment/moment.js`;
```

I use the same (ng2-bootstrap and moment, required by the former) in a project I'm working on now. The above is all the config I need.

Please close when working for ya'.

**Comment by rernens** [comment]
@NathanWalker  thanks for your reply, meanwhile I found out that the problem is not the changes made to project_config.

In the last seed version, stopping the server than running npm start does not update the system-config.js even if project_config has been changed.

By the way, it looks like other files are not updated either.

Deleting the dist/dev directory before running npm start fixes the pb.

**Comment by NathanWalker** [comment]
A PR that was contributed awhile back (regarding `newer` plugin) caused that issue.
I have since removed it here https://github.com/NathanWalker/angular-seed-advanced/commit/e453ce28db5d406344f39f73469aafd90a13d7de#diff-c872f9f7f2909766c21c5583e01038bbL37 and now that problem is gone on master.
Lemme know if you have any further trouble.
