### ISSUE TITLE
build.dev failing with module not found

### ISSUE THREAD

**Issue by CNSKnight** [NathanWalker/angular-seed-advanced#273]
I've just merged and after some fiddling, `npm update` gives no complaints but build emits the following:

```
$ npm run build.dev
...
[09:03:15] 'build.dev' errored after 867 ms
[09:03:15] Error in plugin 'run-sequence(build.html_css)'
Message:
    Cannot find module '.tmp/Rx.min.js'
```

**Comment by NathanWalker** [comment]
@CNSKnight  Can you try pulling down a fresh repo and run that just to determine if it's something with your merge?

I'm not seeing that here.

**Comment by CNSKnight** [comment]
Yes I had done that - could be still something w/my nvm/node(6.8.*) setup but I haven't figured it out.

**Comment by NathanWalker** [comment]
Did you try running:

```
npm run clean
```

?

Also go ahead and merge in upstream one more time with fixes that went in just moments ago.

**Comment by NathanWalker** [comment]
Btw, this is my setup that I use for everything:

```
Mac:angular-seed-advanced nathan$ node --version
v5.5.0
Mac:angular-seed-advanced nathan$ npm --version
3.5.3
```

**Comment by NathanWalker** [comment]
@CNSKnight I believe the resolution to this issue: https://github.com/NathanWalker/angular-seed-advanced/issues/255 may have fixed this for you.

Please pull latest master and reopen this if still an issue for you 👍

**Comment by CNSKnight** [comment]
Thanks Nat.
I've done the above and still getting failure, but literally no specific log messages.
(working w/only build.prod)
I do get a few linter and transpiler errors but would not expect these to choke the build.
