### ISSUE TITLE
Navigating to nested routes causes refresh/livereload problem 404 (Not Found) main.web

### ISSUE THREAD

**Issue by orangedrink** [NathanWalker/angular-seed-advanced#275]
**Steps to reproduce and a minimal demo of the problem**
1. Clone a fresh copy of the seed
2. Add a route parameter in about.routes.ts line 6 `path: 'about/:test',`
3. Add a route parameter to the routerLink in navbar.component.html on line 3 `<a [routerLink]="['/about', 'test']" [routerLinkActive]=...`
4. Run the project `npm install && npm start`
5. Click the about link to navigate to /about/test
6. Refresh the page

In the console of dev tools you'll see:

Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:5556/about/main.web

Because APP_BASE is set to an empty string this and a couple of other resources are being loaded relative to this current directory 'about'

It should be pretty easy to check the platform on line 35 of seed-advanced.config.ts and build an APP_BASE that works in all cases. Once i have a working solution I'll share it here.

**Comment by NathanWalker** [comment]
Thanks @orangedrink a contribution would be great. It seems like this used to work even with parent seed but some change along the way has interfered with this. I'll take a look sometime next week if you don't have a solution by then. 👍

**Comment by orangedrink** [comment]
This on line 35 of seed-advanced.config.ts seems to be working for me
`this.APP_BASE = this.TARGET_DESKTOP ? '' : '/';`

**Comment by orangedrink** [comment]
#239 is closed. Is this the same issue?

**Comment by orangedrink** [comment]
My code here wasn't working as well as I thought. looks like when system-config.js was rebuilt it caused some issues wit the electron app.

**Comment by orangedrink** [comment]
Ok I think I have this working the way I need it to now. 

In seed-advanced.config.ts

Line 35:
`this.APP_BASE = this.TARGET_DESKTOP ? '' : '/';`

Then on lines 45 and 46:

```
'node_modules/*/package.json',

'node_modules/@ngrx/*/package.json'
```

**Comment by mikaelkristiansson** [comment]
well that fixes the problem, but now the test doesnt work.

**Comment by mikaelkristiansson** [comment]
to fix the testing as well I had to remove the APP_BASE from my libs:
  // Fix up paths for libs
    this.SYSTEM_CONFIG.paths[this.BOOTSTRAP_MODULE] = `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`;
    this.SYSTEM_CONFIG.paths['lodash'] = `node_modules/lodash/index`;
    this.SYSTEM_CONFIG.paths['ngrx-store-freeze'] = `node_modules/ngrx-store-freeze/dist/index`;
    this.SYSTEM_CONFIG.paths['deep-freeze'] = `node_modules/deep-freeze/index`;

**Comment by NathanWalker** [comment]
Sounds like you guys found a solution. Feel free to continue discussion if needed. Just cleaning up outstanding.
