### ISSUE TITLE
[Question] Folders "nativescript" and "src/client" are not in sync as described in the description?

### ISSUE THREAD

**Issue by chaitanya9186** [NathanWalker/angular-seed-advanced#276]

**Comment by NathanWalker** [comment]
Only the `src/client/app` and `src/client/assets` folders are symlinked into `nativescript` folder so you should only see `nativescript/app/app` and `nativescript/app/assets` as symlinks. This is expected and how it should be.

If you don't see those, try running:

```
npm run clean
```

or simply:

```
node tools/install.js
```
