### ISSUE TITLE
Little issue with external dependency (HelloJS)

### ISSUE THREAD

**Issue by Sn3b** [NathanWalker/angular-seed-advanced#277]
I've just updated to the lastest version of the seed and I now have a little issue with HelloJS.
To add the dependency I only add the following to NPM_DEPENDENCIES in project.config.ts:

`{ src: 'hellojs/dist/hello.all.js', inject: 'libs' }`

And now the site doesn't load anymore complaining it cannot find the dependency:

`zone.js?1476602905222:1274 GET http://localhost:5555/node_modules/hellojs.js 404 (Not Found)`

I've noticed if I remove the import from my ts component, say `about.component.ts`, then it works fine, but the compiler complains it cannot find the module 'hello':

`src\client\app\components\about\about.component.ts(28,5): error TS2304: Cannot find name 'hello'.`

Steps to reproduce:
- Clone seed
- npm install
- npm install --save hellojs
- npm install --save-dev @types/hellojs
- add `{ src: 'hellojs/dist/hello.all.js', inject: 'libs' }` to NPM_DEPENDENCIES in project.config.ts
- modify about.component.ts:

``` javascript
import { Injector } from '@angular/core';
import { BaseComponent, Config } from '../../frameworks/core/index';
import * as hello from 'hellojs';

@BaseComponent({
  moduleId: module.id,
  selector: 'sd-about',
  templateUrl: 'about.component.html',
  styleUrls: ['about.component.css']
})
export class AboutComponent {
  private _page: any;
  private get page() {
    if (Config.PageClass) {
      if (!this._page) {
        this._page = this.injector.get(Config.PageClass);
      }

      return this._page;
    }
  }

  constructor(private injector: Injector) {
    if (this.page) {
      this.page.actionBarHidden = true;
    }

    hello.init({
        google: 'GOOGLE_CLIENT_ID'
    }, {redirect_uri: 'redirect.html'});
  }

  public doLogin() {
    hello('google').login();
  }
}
```

Finally, I've noticed the parent seed works fine with the same steps.

Any help appreciated, thanks :)

**Comment by NathanWalker** [comment]
@Sn3b try this inside `project.config.ts`:
Instead of doing the npm_dependencies include, do this instead and let systemjs load it:

```
// dev
this.SYSTEM_CONFIG.paths['hellojs'] = `${this.APP_BASE}node_modules/hellojs/dist/hello.all`;

// prod
this.SYSTEM_BUILDER_CONFIG.paths['hellojs'] = `${this.APP_BASE}node_modules/hellojs/dist/hello.all.js`;
```

Lemme know how it goes.

**Comment by Sn3b** [comment]
Thank you for your answer @NathanWalker but I had already tried that without success...  :(
It still complains:
GET http://localhost:5555/node_modules/hellojs.js 404 (Not Found)

**Comment by NathanWalker** [comment]
Try updating to latest master as of today and try one more time with that. Also if you have project to share I could take a look and run it here to let ya know a fix.

**Comment by Sn3b** [comment]
It works now :/
Thanks! Even if I hate it when I spend days on an issue and finally when I decide to post about it, there's an update that fixes everything...

Going to reinstall the next dependency now, ngrx devtools, fingers crossed :P

**Comment by NathanWalker** [comment]
Lol, I know what ya mean ;) There's been quite a few things in past 2 weeks for some reason that all kinda came at once. Things are looking pretty good now.

**Comment by NathanWalker** [comment]
@Sn3b

Btw, here's all you need in `project.config.ts` for ngrx devtools you need (I use them myself :) ):

```
// debug tools
    this.SYSTEM_CONFIG['packages']['@ngrx/store-devtools'] = {
      main: 'bundles/store-devtools.umd.js',
      defaultExtension: 'js'
    };
    this.SYSTEM_CONFIG['packages']['@ngrx/store-log-monitor'] = {
      main: 'bundles/store-log-monitor.umd.js',
      defaultExtension: 'js'
    };
```

Then in `web.module.ts` (in part):

```
// dev tools
import { StoreDevtoolsModule } from '@ngrx/store-devtools';
import { StoreLogMonitorModule, useLogMonitor } from '@ngrx/store-log-monitor';

@NgModule({
  imports: [
    // etc...
    // dev: debug store (just comment these out when going to production
    // or conditionally add them based on dev build flags ;)
    StoreDevtoolsModule.instrumentStore({
      monitor: useLogMonitor({
        visible: true,
        position: 'right'
      })
    }),
    StoreLogMonitorModule
  ],
```

**Comment by Sn3b** [comment]
I managed to work that one out, but I appreciate the tip thanks :)
I actually just checked how you configured ngrx store in the advanced config file ;)
