### ISSUE TITLE
Production build is failing

### ISSUE THREAD

**Issue by gomesNazareth** [NathanWalker/angular-seed-advanced#278]
1) took the latest seed updates
2) upgraded to node 6.8 from 4.6 since  npm i  failed with 4.6
3) ran     npm run build.prod      after npm i installed successfully
4) but i got the following error 
'build.bundles.app' errored after 1.6 s
[11:32:05] Error on fetch for dist\tmp\main.web.js at file:///D:/projects/spa/nathan/angular-seed-advanced/node_modules/dist\tmp\main.web.js
        Error: ENOENT: no such file or directory, open 'D:\projects\spa\nathan\angular-seed-advanced\node_modules\dist\tmp\main.web.js'
    at Error (native)
[11:32:05] 'build.prod' errored after 18 s
[11:32:05] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on fetch for dist\tmp\main.web.js at file:///D:/projects/spa/nathan/angular-seed-advanced/node_modules/dist\tmp\main.web.js
        ENOENT: no such file or directory, open 'D:\projects\spa\nathan\angular-seed-advanced\node_modules\dist\tmp\main.web.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open 'D:\projects\spa\nathan\angular-seed-advanced\node_modules\dist\tmp\main.web.js'
Stack:
Error on fetch for dist\tmp\main.web.js at file:///D:/projects/spa/nathan/angular-seed-advanced/node_modules/dist\tmp\main.web.js
        Error: ENOENT: no such file or directory, open 'D:\projects\spa\nathan\angular-seed-advanced\node_modules\dist\tmp\main.web.js'
    at Error (native)

**Comment by xLama** [comment]
I think it fails on Windows but not on Mac.

You can see fix here:
#255

**Comment by NathanWalker** [comment]
@gomesNazareth you can pull latest master now to get that fix. Please reopen if still an issue for you after doing so.
