### ISSUE TITLE
install the nativescript-plugin-firebase hit the @angular/core@2.1.0 does not satisfy its siblings problem

### ISSUE THREAD

**Issue by netwiser** [NathanWalker/angular-seed-advanced#279]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**
Clone the master branch. npm install, go to nativescript folder, tns plugin add nativescript-plugin-firebase, it prompts:
The package @angular/core@2.1.0 does not satisfy its siblings' peerDependencies requirements!

_What steps should we try in your demo to see the problem?_

**Current behavior**

**Expected/desired behavior**
Plugin installed

**Other information**
Not sure this issue belongs to which party, just hope can get a ready environment to start building nativescript realtime app.

**Comment by NathanWalker** [comment]
@netwiser do this (lil' trick to get around that):
From inside the `nativescript` folder...

```
npm i nativescript-plugin-firebase --save
npm i && tns emulate ios --disableNpmInstall
```

You can run android the same way:

```
tns run android --disableNpmInstall
```

The `package` script when run from the root of the seed takes care of that for you, for example:
https://github.com/NathanWalker/angular-seed-advanced/blob/master/package.json#L49

I believe `2.4.0` of NativeScript (due out by ~ 11/2) should solve that.
Cheers!

**Comment by ajanytime** [comment]
was having the same issue, thanks Nathan !

**Comment by netwiser** [comment]
Awesome, thanks a lot!
