### ISSUE TITLE
localhost/:54 Error: (SystemJS) XHR error

### ISSUE THREAD

**Issue by geminiyellow** [NathanWalker/angular-seed-advanced#280]
- Setup 
  I follow the [Setup](https://github.com/NathanWalker/angular-seed-advanced#setup-1) guide on the top `README`,  in `5. npm run git.merge`, hit the frist error, there are 3 conflicts need to fix.
  and i copy the latest version from the master branch, and finish the `Setup` guide.  
- Dev
  then i just start up the dev server by command `npm start`, 

```
[14:41:58] Starting 'serve.dev'...
[14:41:58] Starting 'build.dev'...
[14:41:58] Starting 'build.assets.dev'...
[14:41:58] Finished 'build.assets.dev' after 342 ms
[14:41:58] Starting 'build.html_css'...
[14:41:59] Finished 'build.html_css' after 572 ms
[14:41:59] Starting 'build.js.dev'...
[14:42:02] Finished 'build.js.dev' after 3.28 s
[14:42:02] Starting 'build.index.dev'...
[14:42:02] gulp-inject 4 files into index.html.
[14:42:02] gulp-inject 2 files into index.html.
[14:42:02] gulp-inject 1 files into index.html.
[14:42:02] Finished 'build.index.dev' after 137 ms
[14:42:02] Finished 'build.dev' after 4.33 s
[14:42:02] Starting 'server.start'...
[14:42:02] Finished 'server.start' after 89 ms
[14:42:02] Starting 'watch.dev'...
[14:42:03] Finished 'watch.dev' after 149 ms
[14:42:03] Finished 'serve.dev' after 4.57 s
[BS] Access URLs:
 -----------------------------------
       Local: http://localhost:5555/
    External: http://10.0.1.53:5555/
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.1.53:3001
 -----------------------------------
[BS] Serving files from: dist/empty/
```

that is good, no error, but when i open the page.
- Error

```
localhost/:54 Error: (SystemJS) XHR error loading http://localhost:5555/app/frameworks/analytics/analytics.module.js
    Error: XHR error loading http://localhost:5555/app/frameworks/analytics/analytics.module.js
        at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1476682922782:236:37)
        at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1476682922782:136:47)
        at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1476682922782:304:33)
    Error loading http://localhost:5555/app/frameworks/analytics/analytics.module.js as "./app/frameworks/analytics/analytics.module" from http://localhost:5555/web.module.js
        at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1476682922782:236:37)
        at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1476682922782:136:47)
        at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1476682922782:304:33)
    Error loading http://localhost:5555/app/frameworks/analytics/analytics.module.js as "./app/frameworks/analytics/analytics.module" from http://localhost:5555/web.module.js "Report this error at https://github.com/NathanWalker/angular-seed-advanced/issues"(anonymous function) @ localhost/:54
http://localhost:5555/app/frameworks/analytics/index.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

i check the `pacakge.json` and `node_modules`, `system.js` is here

@NathanWalker can you tell me how to fix it?

**Comment by NathanWalker** [comment]
> hit the frist error, there are 3 conflicts need to fix.

You may have an issue with a conflict resolution?
Do you have link to your commit where you did the merge and I could see if something is awry.
Definitely sounds like misconfiguration.

Worst case, just download see again fresh, follow [this](https://github.com/NathanWalker/angular-seed-advanced#how-best-to-use-for-your-project) and then just drop your code back in.

**Comment by geminiyellow** [comment]
hmmm, @NathanWalker thanks for your reply, i try it in a empty repo, and work well. so, maybe as you said, 

> Definitely sounds like misconfiguration.

i will try it again.

**Comment by geminiyellow** [comment]
but finally faild. 
here is my public repos: https://github.com/geminiyellow/bearnose

i delete all files, and create a empty folder and put the zip in ,

it looks like that:

![image](https://cloud.githubusercontent.com/assets/929878/19557292/07e415ca-9700-11e6-883e-fef4dabd4929.png)

follow [this](https://github.com/NathanWalker/angular-seed-advanced#how-best-to-use-for-your-project), all is good.

then i try to 

```
# watches your files and uses livereload by default
npm start

[20:04:04] Finished 'serve.dev' after 4.73 s
[BS] Access URLs:
 -----------------------------------
       Local: http://localhost:5555/
    External: http://10.0.1.53:5555/
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.1.53:3001
 -----------------------------------
[BS] Serving files from: dist/empty/

```

server started, but

```
localhost/:54 Error: (SystemJS) XHR error loading http://localhost:5555/app/frameworks/analytics/analytics.module.js(…) "Report this error at https://github.com/NathanWalker/angular-seed-advanced/issues"
```

the same.

**Comment by geminiyellow** [comment]
i dont know if my mac env or not. 
i clone the master branch, and try to run it, and got the same error.

```
npm run build

------------------------ Angular Seed Advanced is Now Ready ----------------------------

Run your web app with:
  npm start
```

**Comment by geminiyellow** [comment]
the desktop version and nativescript version is good, the web version is down. 
- node: v6.9.1
- npm: 3.10.8
- nativescript: 2.3.0
- typescript: 2.0.3
- chrome:  52.0.2743.116 (64-bit)

**Comment by sunjith** [comment]
@geminiyellow
Can you expand that ellipsis in braces just after the name of the js file in error message and provide the full stack trace?
I had a similar error when upgrading to ng2-translate@3.1.2 which was because ng2-translate@3.0.0 dropped support for commonjs module and only supports ES and UMD (Ref: [https://github.com/ocombe/ng2-translate/releases](url)). To fix it, had to specify it's bundle in SystemJS packages config.

```
    this.SYSTEM_CONFIG['packages']['ng2-translate'] = {
      main: 'bundles/ng2-translate.js',
      defaultExtension: 'js'
    };
```

Added the above in tools/config/seed-advanced.config.ts after line 62.

**Comment by NathanWalker** [comment]
@geminiyellow @sunjith latest master contains a lot of fixes and updates (as of a few minutes ago) including the latest ng2-translate compatible for web and {N}. Closing as I believe this will solve the above. Please clone latest master fresh and give it a shot.

**Comment by geminiyellow** [comment]
@NathanWalker sorry, but it still here. thanks for your reply sir, i think i can check it out myself. if cannot, i will reopen this.
