### ISSUE TITLE
Issue with adding assets

### ISSUE THREAD

**Issue by NTPLThavarajan** [NathanWalker/angular-seed-advanced#281]
**Steps to reproduce and a minimal demo of the problem**
add the following code in project.config

```
this.APP_ASSETS = [
      ...this.APP_ASSETS,
      { src: `${this.APP_SRC}/bootstrap/css/bootstrap.min.css`, inject: true, vendor: false },
      { src: `${this.APP_SRC}/bootstrap/js/bootstrap.min.js`, inject: true, vendor: false }
    ];

```

**Current behavior**
the css and js files are not injected

**Expected/desired behavior**
the css and js files are need to be injected

or am i do anything wrong here

**Other information**
i am just try to add bootstrap 4 in my application

And the main thing is 
thanks for such a awesome repo

**Comment by NathanWalker** [comment]
Hopefully you installed `bootstrap` via npm. If not, do this:

```
npm install bootstrap@4.0.0-alpha.4 --save
```

Move the css portion into `src/client/assets/styles`, then setup assets as follows for css:

```
this.APP_ASSETS = [
  ...this.APP_ASSETS,
  // create styles directory inside src/client/assets if not there
  { src: `${this.ASSETS_SRC}/styles/bootstrap/css/bootstrap.min.css`, inject: true },
];
```

Then for JS (this will pull from `node_modules` folder):

```
this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      {src: 'bootstrap/js/bootstrap.min.js', inject: 'libs'}
    ];
```

**Comment by NTPLThavarajan** [comment]
yes i installed the bootstrap 4 through npm,

Thanks for your information @NathanWalker  
CSS Part is worked perfectly

but how could i add the dependencies of bootstrap automatically 
i try the following 
`this.SYSTEM_CONFIG_DEV.packageConfigPaths.push(`/node_modules/bootstrap/package.json`);`
but seems it is not working,
i think i am doing something wrong here
or do i need to add  it separately one by one using 
npm install jquery
npm install tether
and add the reference to it's js separately 

also one more thing is there any other way to implement the Bootstrap SCSS into our project 
is it possible? 
do i need to copy the entire scss folder in to styles folder

**Comment by NathanWalker** [comment]
@NTPLThavarajan see this: https://github.com/mgechev/angular-seed/issues/1412
