### ISSUE TITLE
Update ng2-translate to latest version to allow AoT compile to work

### ISSUE THREAD

**Issue by NathanWalker** [NathanWalker/angular-seed-advanced#282]
I had tried this last week and it presented some issues. Need to revisit when I have more time.
This is currently what is causing the travis ci to fail.

**Comment by sunjith** [comment]
FYI: ng2-translate@3.0.0 dropped support for commonjs module and only supports ES and UMD (Ref: [https://github.com/ocombe/ng2-translate/releases](url)). To fix it, had to specify it's bundle in SystemJS packages config.

```
    this.SYSTEM_CONFIG['packages']['ng2-translate'] = {
      main: 'bundles/ng2-translate.js',
      defaultExtension: 'js'
    };
```

Added the above in tools/config/seed-advanced.config.ts after line 62.

**Comment by m-abs** [comment]
@sunjith What about NativeScript? We tried updating and NativeScript couldn't launch our app because of it.

**Comment by NathanWalker** [comment]
@m-abs web **AND** NativeScript now works with latest ng2-translate version since the latest `nativescript-angular` build now supports TypeScript 2.0. master has the goods now 👍

**Comment by sunjith** [comment]
@NathanWalker Excellent! Thank you so much.

**Comment by m-abs** [comment]
Brilliant, thanks @NathanWalker

**Comment by NathanWalker** [comment]
Just keep this note in mind regarding AoT compilation:
https://github.com/NathanWalker/angular-seed-advanced#special-note-about-aot
