### ISSUE TITLE
Correct way to import and recognize modules

### ISSUE THREAD

**Issue by syrys** [NathanWalker/angular-seed-advanced#283]
Hey Guys,

I just have a quick question. This is not really an issue, just mainly a question as to what the best way to do this.

if i import a node module from within a ng2 component, lets say trying to get `ipcRenderer`, my IDE (WebStorm / PhpStorm) does not recognize it. Is there any reason why this happens?

For example, add the following to the top of about.component.ts:

```
import {ipcRenderer} from 'electron';
```

and add the following to index.html

```
  <script>
    System.set('electron', System.newModule(require('electron')));
  </script>
```

What you are doing is right and it should work just fine. But my IDE continues to say `ipcRenderer` is invalid, and highlights it bright red. Do i need to somehow let IDE/typescript/something-else know of the `electron` module?

**Comment by m-abs** [comment]
Have you installed `@types/electron` as a dev-dependency?

I also think you should modify `tools/config/seed-advanced.config.ts` rather than index.html to load electron with systemjs.

If you inject `ipcRenderer` in your app.component like that, can you still run web and {N}?

**Comment by NathanWalker** [comment]
n/a.
