### ISSUE TITLE
Want to implement a Mangoose Reporsitory pattern, some body help me

### ISSUE THREAD

**Issue by NTPLThavarajan** [NathanWalker/angular-seed-advanced#287]
Dear @NathanWalker ,

Thanks for such a wonder full startup project
i almost implement this project for the past last one month, 
Now one of my senior programmer suggest me to implement the mongodb Reporsitory pattern, with the current project
i try to implement the functionality using [angular 2 seed express](https://github.com/vyakymenko/angular2-seed-express)
but got stumped 

i am successfully change the dist structure to 
dist
|- client
|- server

but the problem is i am not able to make the express app serve for api and as well as website
also i got some typescript compilation error as follows

```
D:/angular2-seed-advanced/angular2-advanced/typings/globals/core-js/index.d.ts(2815,5): error TS2300: Duplicate identifier 'export='.
D:/angular2-seed-advanced/angular2-advanced/typings/globals/core-js/index.d.ts(2819,5): error TS2300: Duplicate identifier 'export='.
D:/angular2-seed-advanced/angular2-advanced/typings/globals/core-js/index.d.ts(2823,5): error TS2300: Duplicate identifier 'export='.
D:/angular2-seed-advanced/angular2-advanced/typings/globals/core-js/index.d.ts(2827,5): error TS2300: Duplicate identifier 'export='.
D:/angular2-seed-advanced/angular2-advanced/typings/globals/core-js/index.d.ts(2831,5): error TS2300: Duplicate identifier 'export='.
D:/angular2-seed-advanced/angular2-advanced/typings/globals/core-js/index.d.ts(2835,5): error TS2300: Duplicate identifier 'export='.
D:/angular2-seed-advanced/angular2-advanced/typings/globals/core-js/index.d.ts(2839,5): error TS2300: Duplicate identifier 'export='.
```
don't know how to remove this error 
and my build.server.dev.ts is much similar to  build.js.dev.ts
except the path almost every thing is same
my server ts files are copied from this [source folder
](https://github.com/ErickWendel/NodeJSWithTypescript/tree/master/src)

please suggest me a solution or link, i have spend almost four days for this thing
i am completely lost in this forest,
(sorry for my poor English too)

**Comment by NathanWalker** [comment]
Glad you find it useful @NTPLThavarajan 👍 
As to your issue, I'm not real sure. Things like that usually take a pretty thorough look at your setup to resolve. I also notice you are using Windows, which I am not as good at.
I'll leave this open to see if anyone else could help point you in the right direction.

**Comment by NTPLThavarajan** [comment]
Thanks  @NathanWalker 
currently now i just keep this as two separate projects and move on to develop other modules,

**Comment by Kaffiend** [comment]
Im currently working a companion seed which implements a similar structure. Mine is for asp.net core but it sounds to me like you need help with tasks getting files into the right places for your server. Is that right?

**Comment by NTPLThavarajan** [comment]
thanks @Kaffiend 
The thing is i am able to deploy the files in right place
but i am not able to serve the files for server part
i don't know how to make the express serve for my api, and also  there are errors nearly 1002  which all says some thing like the error i mentioned in the top

if you wish i will share the tools file that i chnage

**Comment by Kaffiend** [comment]
Sure ill take a look. If you can share a repo it would be easiest.

**Comment by Thavarajan** [comment]
@Kaffiend  
now i am able to remove the errors
but still not able to serve the api

https://github.com/Thavarajan/angular-seed-advanced/tree/MEAN

this is the repo can you please suggest, what should i do

**Comment by Kaffiend** [comment]
@Thavarajan Sorry for the delay, i've had some projects release and been consumed by getting everyone up and running. I'll be looking in to extending a branch or fork of this or the parent seed into incorporating a server side api. Im wanting to be able to be able to attach say a Docker image of postgres and a server api with Knex.js at the project level. If i figure it out ill keep you in mind as i think its similar to what you are trying to accomplish.

**Comment by Kaffiend** [comment]
@Thavarajan at a quick glance looking how the seed serves the client I'd say you will have to build your own project utility similar to how the client is served. a good example is the production server part of [server.ts](https://github.com/Thavarajan/angular-seed-advanced/blob/MEAN/tools/utils/seed/server.ts) until i can dig into it further thats the best suggestion i have so far. Sorry

**Comment by Kaffiend** [comment]
@Thavarajan take a look at this [repo](https://github.com/Kaffiend/angular-api-advanced-seed) i've built a simple api server and have the seed building it and hosting it when the serve.dev task is run. I just threw it together so it can be much more elegant but hopefully it gives you the idea on how to serve your api with the seed.

**Comment by Kaffiend** [comment]
@NTPLThavarajan @Thavarajan mentioning both as im not sure which is current.
i've updated my repo with a build and serving process thats more like you were looking for. drop your server in the api directory and give it a go.
[repo](https://github.com/Kaffiend/angular-api-advanced-seed)

NOTE: i've only wired up the build and serve dev processes, i've yet to build out the prod portions.

Im building this version of the seed as i wanted to be able to build and develop against a decoupled server side api along with my apps.

**Comment by Thavarajan** [comment]
Thanks for the info, i will test this weekend and update the results 
Thank you @Kaffiend

**Comment by Thavarajan** [comment]
seems lot of things changed here, i delete the existing repo and working on the newly forked source 
will update the details soon

**Comment by Thavarajan** [comment]
almost there, i am able to serve the api, but i am not able to restart it on code change 
any help?

**Comment by Kaffiend** [comment]
i didnt wire up everything, i only wired up enough to show how it can be served. Ill have to look at this again and see what else it would take.

**Comment by Thavarajan** [comment]
Thanks you @Kaffiend, 
after a lot of search, i am able achieve my need now everything works as expected 
i renamed the fork repo as follows
[angular-mongoose-seed-advanced](https://github.com/Thavarajan/angular-mongoose-seed-advanced)
any updates or suggesstions are welcome
still need to update the source to get data from db
finally this is a great repo thanks to @NathanWalker  for such a great one

**Comment by Kaffiend** [comment]
@Thavarajan Sorry i couldn't give a more in depth example, i'm a bit swamped of late. I'm glad you found your way. If i can help any other way please don't hesitate to ask, I try to contribute to the opensource community each weekend if time permits.

**Comment by NathanWalker** [comment]
Feel free to continue discussion. Great work @Thavarajan I have added a link to your Mongoose fork in the Wiki: https://github.com/NathanWalker/angular-seed-advanced/wiki

**Comment by Thavarajan** [comment]
Thanks @NathanWalker, 
still i have one issue pending, 
when i try to use npm install some how it start my mongoose server 
please provide some suggesstion on that
if i comment [this code](https://github.com/Thavarajan/angular-mongoose-seed-advanced/blob/master/tools/tasks/project/express-api.ts#L10) it will run as expected
