### ISSUE TITLE
Typos? (sccs? scss?)

### ISSUE THREAD

**Issue by Sn3b** [NathanWalker/angular-seed-advanced#292]
Are those typos?

https://github.com/NathanWalker/angular-seed-advanced/blob/master/tools/tasks/seed/build.html_css.ts#L79
https://github.com/NathanWalker/angular-seed-advanced/blob/master/tools/tasks/seed/build.html_css.ts#L102
https://github.com/NathanWalker/angular-seed-advanced/blob/master/tools/tasks/seed/build.html_css.ts#L129
https://github.com/NathanWalker/angular-seed-advanced/blob/master/tools/tasks/seed/build.html_css.ts#L182

**Comment by NathanWalker** [comment]
@Sn3b looks like a contributor mishap. Just pushed up fix alongside some nice package updates.
Thanks for heads up!
