### ISSUE TITLE
reuse offline storage capabilities throughout the different platforms electron/nativescript

### ISSUE THREAD

**Issue by divramod** [NathanWalker/angular-seed-advanced#295]
Hey,

i wrote a [Stackoverflow question](http://stackoverflow.com/questions/40472662/how-to-create-a-persistent-offline-database-with-electron-and-pouchdb) to find out, how to best reuse offline storage capabilities throughout the different platforms used in the advanced-seed here.

so i wanted to aks here too, if somebody knows how to reuse offline storage capabilities for electron/nativescript/web (write once, use everywhere).

currently i am thinking about using pouchdb. 

does anybody has a tipp on that?

**Comment by hatemhosny** [comment]
Have a look on LokiJs 
http://lokijs.org/

It is a fast light-weight javascript in-memory database, that has multiple adapters for data persistence including IndexedDb (for web apps) and nativescript (for mobile apps)
https://rawgit.com/techfort/LokiJS/master/jsdoc/tutorial-Persistence%20Adapters.html
https://rawgit.com/techfort/LokiJS/master/jsdoc/LokiIndexedAdapter.html
https://github.com/TobiasHennig/loki-nativescript-adapter

There is also an adapter for localForage, which you can use to save to sqlite

Cordova adapter : https://github.com/cosmith/loki-cordova-fs-adapter
localForage adapter : https://github.com/paulhovey/loki-localforage-adapter

**Comment by NathanWalker** [comment]
Feel free to continue discussion here, just closing to cleanup outstanding issues.
