### ISSUE TITLE
Firebase Guide Wiki and angular 2

### ISSUE THREAD

**Issue by govi2010** [NathanWalker/angular-seed-advanced#297]
Now that the project has been updated to Angular 2, is the guide 'How to integrate Firebase across all platforms' still valid or it needs to be updated?

Thanks in advanced.

**Comment by NathanWalker** [comment]
@govi2010 This wiki is now updated to reflect latest:
https://github.com/NathanWalker/angular-seed-advanced/wiki/How-to-integrate-Firebase-across-all-platforms-(web-nativescript-desktop)
