### ISSUE TITLE
How do you use vscode?

### ISSUE THREAD

**Issue by Sn3b** [NathanWalker/angular-seed-advanced#299]
Coming from Atom but originally a C# dev so I love Visual Studio, therefore I'd like to start using vscode instead, especially since I see this little .vscode folder on pretty much all the repos I clone.

I'm having difficulties understanding how to run it with the chrome debugger, what are the steps?

I've managed to run it from vscode using F1 => run task => Enter but that builds and runs the app without debugger so my breakpoints are never hit :(

**Comment by fourctv** [comment]
Yes you have to do that first, to get your app built and running.

Then, on VSCode, go to View->Debug. There you should see a green arrow and a launch drop down. Select "Launch localhost with sourcemaps", and hit the green arrow to start debugger...

hth
julio

**Comment by Sn3b** [comment]
Got it, I enabled a few lines of code and then modified them following this: https://github.com/mgechev/angular-seed/issues/1220

:)

**Comment by NathanWalker** [comment]
Awesome great to hear @Sn3b
