### ISSUE TITLE
@angular/core@2.1.2 requires a peer of zone.js@^0.6.21 but none was installed.

### ISSUE THREAD

**Issue by agrawal-mohit** [NathanWalker/angular-seed-advanced#300]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

`npm install -g nativescript`

> > nativescript-angular@1.2.0-2016-11-08-998 postinstall /usr/local/lib/node_modules/angular-seed-advanced/node_modules/nativescript-angular
> > node postinstall.js
> 
> 
> > nativescript-theme-core@0.1.5 postinstall /usr/local/lib/node_modules/angular-seed-advanced/node_modules/nativescript-theme-core
> > node scripts/postinstall.js
> 
> /usr/local/lib
> └─┬ angular-seed-advanced@0.0.0 
>   ├── @angular/common@2.1.2 
>   ├── @angular/compiler@2.1.2 
>   ├── @angular/core@2.1.2 
>   ├── @angular/forms@2.1.2 
>   ├── @angular/http@2.1.2 
>   ├── @angular/platform-browser@2.1.2 
>   ├── @angular/platform-browser-dynamic@2.1.2 
>   ├── @angular/router@3.1.2 
>   ├── @ngrx/core@1.2.0 
>   ├── @ngrx/effects@2.0.0 
>   ├── @ngrx/store@2.2.1 
>   ├── angulartics2@1.4.1 
>   ├── es6-promise@3.3.1 
>   ├── es6-shim@0.35.1 
>   ├── lodash@4.16.6 
>   ├─┬ nativescript-angular@1.2.0-2016-11-08-998 
>   │ ├── nativescript-intl@0.0.4 
>   │ └── UNMET PEER DEPENDENCY zone.js@^0.6.21
>   ├── nativescript-theme-core@0.1.5 
>   ├── ng2-translate@4.0.0 
>   ├── parse5@1.3.2 
>   ├── punycode@1.3.2 
>   ├── querystring@0.2.0 
>   ├── reflect-metadata@0.1.8 
>   ├─┬ rxjs@5.0.0-beta.12 
>   │ └── symbol-observable@1.0.4 
>   ├─┬ tns-core-modules@2.3.0 
>   │ └── tns-core-modules-widgets@2.3.0 
>   ├── url@0.10.3 
>   └── UNMET PEER DEPENDENCY zone.js@^0.6.21
> 
> npm WARN @angular/core@2.1.2 requires a peer of zone.js@^0.6.21 but none was installed.
> 
> 
> 
> npm WARN @angular/core@2.1.2 requires a peer of zone.js@^0.6.21 but none was installed.
> 

**Expected behavior**
Installs successfully.

**Minimal reproduction of the problem with instructions**
Cline the project, goto the project directory and issue at cli :
`npm install -g nativescript`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
OS X 10.10.5 Yosemite
Sublime3 
npm 3.10.9

* **Angular Seed Version:** 2.0.X

51638e0

* **Node:** `node --version` = v4.5.0

**Comment by NathanWalker** [comment]
Hi @agrawal-mohit you can ignore that, it's just a warning ;) It actually installed everything fine.
