### ISSUE TITLE
desktop app is not working

### ISSUE THREAD

**Issue by Thavarajan** [NathanWalker/angular-seed-advanced#308]
i don't know whether it's a issue or not

i am adding ng bootstrap  angular2 components in my  project
and in the project.config.ts constructor
```
    this.SYSTEM_CONFIG_DEV.paths['@ng-bootstrap/ng-bootstrap'] = `${this.APP_BASE}node_modules/@ng-bootstrap/ng-bootstrap`;
    this.SYSTEM_CONFIG_DEV.packageConfigPaths.push(`/node_modules/@ng-bootstrap/*/package.json`);
    this.SYSTEM_BUILDER_CONFIG.packages['@ng-bootstrap/ng-bootstrap'] = {
      main: 'ng-bootstrap/index.js',
      defaultExtension: 'js'
    };
```

**Current behavior**
it successfully build in web and produce the output when i use 
`npm start`
but while i try to do it in desktop using
`npm run start.desktop.windows`
the window is show the loading..  page only 
then in console 
it show me this error
```file:///D:/angular2-seed-advanced/angular2-advanced/dist/dev/node_modules/@ng-bootstrap/ng-bootstrap.js Failed to load resource: net::ERR_FILE_NOT_FOUND```

i feel that this is due to some path problem 
can anybody tell me what i did wrong here

**Comment by NathanWalker** [comment]
Hi @Thavarajan open `tools/tasks/project/desktop.libs.ts` and add this to the `src` collection:
```
'node_modules/@ng-bootstrap/**/*'
```

If that doesn't fix it for you, ping back and I'll reopen 👍

**Comment by Thavarajan** [comment]
Thanks @NathanWalker ,
I finally figure it out , actually that was a path problem
the libs are already added in my case
the solution is as follows
```
    this.SYSTEM_CONFIG_DEV.packageConfigPaths.push(`/node_modules/@ng-bootstrap/*/package.json`);
    this.SYSTEM_CONFIG_DEV.paths['@ng-bootstrap/ng-bootstrap'] = `${this.APP_BASE}node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js`;
    this.SYSTEM_BUILDER_CONFIG.packages['@ng-bootstrap/ng-bootstrap'] = {
      main: 'index.js',
      defaultExtension: 'js'
    };
```

also please remove the space in the package.json line no [48](https://github.com/NathanWalker/angular-seed-advanced/blob/master/package.json#L48) as follows
` "start.desktop.windows": "gulp desktop && SET NODE_ENV=development&& electron ./dist/dev"`
