### ISSUE TITLE
fix: Effects start up procedure

### ISSUE THREAD

**Issue by Sn3b** [NathanWalker/angular-seed-advanced#310]
Hi @NathanWalker,

I don't want to bother you with another PR, but you can review a minor change [here](https://github.com/Sn3b/angular-seed-advanced/commit/4ce2df46fb05af0b5db01c82837560ee5a6b9c4c) that has its importance. Indeed I realised if you had several services initialize their stores, only the last one was taken into account, with this fix and start up procedure all works well as expected.

Seb :)

**Comment by NathanWalker** [comment]
Go ahead and PR that @Sn3b 👍 I never mind a good PR and yours are great, thank you.

**Comment by Sn3b** [comment]
[Here](https://github.com/NathanWalker/angular-seed-advanced/pull/311) you go :)

**Comment by NathanWalker** [comment]
merged
