### ISSUE TITLE
livesync is not refreshing files

### ISSUE THREAD

**Issue by codeback** [NathanWalker/angular-seed-advanced#313]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
The app is not refreshing if I modify tns.html or tns.css files if the files are in nativescript/app/app/... link. If the files are in nativescript/app/pages/... folder, it works.

If I modify *.ts files, the app is refreshing but nothing changes.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

Run npm run.livesync.start

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

5532b17eefbbe8fc02c702ece0f2fd92c5ebc6cc

* **Node:** `node --version` =
6.4.0

**Comment by NathanWalker** [comment]
Hi @codeback thanks for the report. This is related to fact that livesync does not work with symlinks.

However, once [this PR](https://github.com/NathanWalker/angular-seed-advanced/pull/312) gets merged, livesync with {N} app will be like a dream 👍  It's very nice.

**Comment by codeback** [comment]
Ok, I'm eagerly waiting for the PR!

Thanks a lot Nathan.

**Comment by NathanWalker** [comment]
@codeback this PR has been merged. Livesync working great now 🎉
