### ISSUE TITLE
error in gulpfile.ts while install ng2-seed-advanced generator - "Unexpected Token import"

### ISSUE THREAD

**Issue by alokkulkarni** [NathanWalker/angular-seed-advanced#314]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
[11:04:42] Failed to load external module ts-node/register
[11:04:42] Failed to load external module typescript-node/register
[11:04:42] Failed to load external module typescript-register
[11:04:42] Failed to load external module typescript-require
/usr/local/lib/node_modules/generator-ng2-seed-advanced/node_modules/angular2-seed-advanced/gulpfile.ts:1
(function (exports, require, module, __filename, __dirname) { import * as gulp from 'gulp';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/usr/local/Cellar/node/6.4.0/libexec/npm/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/Cellar/node/6.4.0/libexec/npm/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
/usr/local/lib
└── (empty)

npm WARN @ngrx/core@1.2.0 requires a peer of rxjs@^5.0.0-beta.12 but none was installed.
npm WARN @ngrx/store@2.2.1 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN @ngrx/store@2.2.1 requires a peer of rxjs@^5.0.0-beta.12 but none was installed.
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "i" "generator-ng2-seed-advanced" "-g"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! angular2-seed-advanced@1.0.0 postinstall: `typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed-advanced@1.0.0 postinstall script 'typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed-advanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed-advanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed-advanced
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alokkulkarni/Documents/JavaSamples/angular/angularElectronTest/electronYo/npm-debug.log
npm ERR! code 1

**Expected behavior**
post install to complete for ng2-seed-advanced

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 7.2.0

[11:04:42] Failed to load external module ts-node/register
[11:04:42] Failed to load external module typescript-node/register
[11:04:42] Failed to load external module typescript-register
[11:04:42] Failed to load external module typescript-require
/usr/local/lib/node_modules/generator-ng2-seed-advanced/node_modules/angular2-seed-advanced/gulpfile.ts:1
(function (exports, require, module, __filename, __dirname) { import * as gulp from 'gulp';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/usr/local/Cellar/node/6.4.0/libexec/npm/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/Cellar/node/6.4.0/libexec/npm/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
/usr/local/lib
└── (empty)

npm WARN @ngrx/core@1.2.0 requires a peer of rxjs@^5.0.0-beta.12 but none was installed.
npm WARN @ngrx/store@2.2.1 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN @ngrx/store@2.2.1 requires a peer of rxjs@^5.0.0-beta.12 but none was installed.
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "i" "generator-ng2-seed-advanced" "-g"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! angular2-seed-advanced@1.0.0 postinstall: `typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed-advanced@1.0.0 postinstall script 'typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed-advanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed-advanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed-advanced
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alokkulkarni/Documents/JavaSamples/angular/angularElectronTest/electronYo/npm-debug.log
npm ERR! code 1

**Comment by NathanWalker** [comment]
Hi @alokkulkarni it appears you are using the generator `generator-ng2-seed-advanced`?
That is actually not supported however you may want to open your issue on this repo instead:
https://github.com/peoplewareDo/generator-ng2-seed-advanced
