### ISSUE TITLE
i got this error after npm start

### ISSUE THREAD

**Issue by tamohugues** [NathanWalker/angular-seed-advanced#316]
src\client\app\components\home\home.component.ts(21,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<string[]>'.
  Type '{}' is not assignable to type 'string[]'.
    Property 'length' is missing in type '{}'.

**Comment by NathanWalker** [comment]
Thank you for this report @tamohugues I just pushed the fix to master 👍
