### ISSUE TITLE
the projet not working in prod 

### ISSUE THREAD

**Issue by tamohugues** [NathanWalker/angular-seed-advanced#317]
dist\tmp\app\components\home\home.component.ts(21,5): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<string[]>'.
  Type '{}' is not assignable to type 'string[]'.
    Property 'length' is missing in type '{}'.
[13:55:20] TypeScript: 1 semantic error
[13:55:20] TypeScript: emit succeeded (with errors)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\httawac\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build.prod"
npm ERR! node v6.3.1
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! angular-seed-advanced@0.0.0 build.prod: `gulp build.prod --color --env-config prod --build-type prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed-advanced@0.0.0 build.prod script 'gulp build.prod --color --env-config prod --build-type prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-seed-advanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build.prod --color --env-config prod --build-type prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed-advanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-seed-advanced
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!

**Comment by NathanWalker** [comment]
Thank you for this report @tamohugues I just pushed the fix to master 👍
