### ISSUE TITLE
Build fails after merging from upstream

### ISSUE THREAD

**Issue by schaermu** [NathanWalker/angular-seed-advanced#319]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
The application builds, but crashes with a segfault on startup:

```
Successfully deployed on device with identifier 'AA4409B4-8F5C-4E1F-A991-59669D34BA6A'.
1   0x10848e5dc -[TNSRuntime executeModule:referredBy:]
2   0x104f36d02 main
3   0x1099a792d start
Dec 12 09:32:31 Smartfactorys-MacBook-Pro-2 nativescript[57775]: 4   0x1
Dec 12 09:32:31 Smartfactorys-MacBook-Pro-2 com.apple.CoreSimulator.SimDevice.AA4409B4-8F5C-4E1F-A991-59669D34BA6A.launchd_sim[57435] (UIKitApplication:ch.smartfactory.development.igoapp[0xe70f][57775]): Service exited due to signal: Segmentation fault: 11
file:///app/native.module.ts:50:0: JS ERROR SyntaxError: Importing binding name 'View' is not found.
```

The same issue occured when i upgraded to upstream last week with a similar error message (see https://github.com/NativeScript/nativescript-angular/issues/582).

**Expected behavior**
Well, it should run :)

**Minimal reproduction of the problem with instructions**
The steps i took to upgrade:

1. `npm run git.merge.preview`
2. fixed all merge conflicts (especially the yarn lockfile)
3. `rm -rf node_modules nativescript/node_modules nativescript/platforms`
4. `yarn`
5. `npm run start.ios`

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
macOS latest, typescript 2.1.4, nativescript 2.4.2

* **Angular Seed Version:** `626b42d05c9fe260899aa782215facd5b649b60b`

* **Node:** `node --version` = 6.9.2

**Comment by fourctv** [comment]
I got similar errors when merging recently and it was due to changes on {N}.

Imports from nativescript, which use to be something like `import {xx} from "nativescript/whatever"`, need to be modified to `import {xx} from "nativescript"`.

Same thing for "nativescript-angular".

See that the above as one of the changes in the seed code, which I simply mimic on my code.

That did it for me. So check your code and fix those imports, if that is your case

**Comment by NathanWalker** [comment]
That is true, thanks @fourctv 
@schaermu just update all `nativescript-angular` imports to all import directly from the barrel, for example:

before:
```
import { NativeScriptModule } from 'nativescript-angular/platform';
```
after:
```
import { NativeScriptModule } from 'nativescript-angular';
```
That goes for all imports from that plugin everywhere.
