### ISSUE TITLE
More Robust Logging Abstraction

### ISSUE THREAD

**Issue by VladimirMakaev** [NathanWalker/angular-seed-advanced#328]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Currently we have ```LogService``` that uses underlying ```ConsoleService``` implementation to send the log entry to console. The log entry is always a string which makes the abstraction limited in scenarios where we want some structural logging. (E.g. when using something like Logstash, Loggly or similar).

**Expected behavior**

Would be nice if the abstraction supported both strings and objects and there would be a better pluggable mechanims of logging targets. The target itself is better to be not dependent on the console but rather something abstract. The console implementation would deal with console concerns.

@NathanWalker let me know if that something you're interested  to have in this project. We might come up with design/PR for this. Cause at the moment we have to hack around it or use a different abstraction anyway.

**Comment by NathanWalker** [comment]
@VladimirMakaev sounds interesting. A PR would help illustrate the surface area change for something like you describe.

**Comment by VladimirMakaev** [comment]
@NathanWalker I've prepared a sketch of the idea here in my fork
https://github.com/NathanWalker/angular-seed-advanced/compare/master...VladimirMakaev:log-service-improvements?expand=1
Let me know if you think it's something you want in the seed and I'll polish it better.

Things to note:
- ```minLogLevel``` can be configured per each individual target. It could be tight to Config.Debug or not but it's the consumer host concern to decide so. The ```log.service``` additionally still uses ```Config.Debug``` as a global treshhold.
- I'm thinking of removing ```IConsole``` interface and have just ```ConsoleService``` as abstract class (or maybe just ```Console```). The good part about abstract classes in TypeScript that you automatically get a token for injection but you don't loose anything as you can just ```implement``` them. So for anything I inject I normally use them
- I can think about creating helpers (like ```provideConsoleLogging``` or something more powerfull) to configure the ```log.service```. Maybe as an extensible mechanism to ```CoreModule``` 
- Maybe Promise is too much for log.service. But it still could be a consumer concern whether to await it or not. It wouldn't hurt for the framework to provide it

**Comment by NathanWalker** [comment]
@VladimirMakaev I do really like this, nice work! I'm about 75% in on wanting this in the seed. The only downside is it introduces some complexity that could further deteriorate the approachability of the seed. Almost seems like an implementation detail left for users to explore. However this is extremely useful and offers a lot of power and flexbility.
How about merge up with latest master and post a PR and we can see if any big objections from others?

**Comment by VladimirMakaev** [comment]
I'll try to get the PR out soon. I'll specifically try to address the complexity concern you raised and put in place a reasonable convention but let allow more complex cases to be supported

**Comment by NathanWalker** [comment]
On master now - thanks for the excellent effort again @VladimirMakaev 💯
