### ISSUE TITLE
Where are the angular2-router implementation in this seed

### ISSUE THREAD

**Issue by st-clair-clarke** [NathanWalker/angular-seed-advanced#33]
I know you stated that questions should be asked at the angular2-seed repo, but angular2-seed-advanced has a different folder-structure and src than angular2-seed. I asked a question relevant to angular2-seed-advanced at [http://stackoverflow.com/questions/36346227/angular2-failing-to-load-component-although-webstorm-resolves-it-correctly](http://stackoverflow.com/questions/36346227/angular2-failing-to-load-component-although-webstorm-resolves-it-correctly).

This issue relates to that question. In summary, I created and router. The icon of the router is displayed, but clicking the icon always results in a failure to resolve the component for the router. I use Webstrom and the component url resolves normally, but at runtime it does not resolves. So I am stuck.

Requesting your help please. It seems as if something else is missing. Thanks.

**Comment by NathanWalker** [comment]
Please provide what your patient component looks like here. It's not in the SO post either.. I believe the issue may be coming from the way you have the view referenced there.

**Comment by st-clair-clarke** [comment]
## patient.comp.ts

import { ChangeDetectionStrategy } from 'angular2/core';
import { RouteConfig } from 'angular2/router';
import { NameListService } from '../../frameworks/app.framework/index';
import {
    RouteComponent, AnalyticsService
} from '../../frameworks/core.framework/index';
import { LangSwitcherComponent } from '../../frameworks/i18n.framework/index';
import { NavbarComponent } from './navbar.component';
import { ToolbarComponent } from './toolbar.component';
import { HomeComponent } from '../home/home.component';
import { AboutComponent } from '../about/about.component';
import { PatientComp } from '../../frameworks/epimss.framework/components/reg/patient/patient.comp';

@RouteComponent({
                  selector       : 'sd-app',
                  viewProviders  : [NameListService],
                  templateUrl    : './components/app/app.component.html',
                  directives     : [LangSwitcherComponent, NavbarComponent, ToolbarComponent],
                  // Everything else uses OnPush
                  changeDetection: ChangeDetectionStrategy.Default
                })
@RouteConfig([
               { path: '/', component: HomeComponent, as: 'Home' },
               {
                 path: '/newPatient', component: PatientComp, as: 'NewPatient'
               },
               { path: '/about', component: AboutComponent, as: 'About' }
             ])
export class AppComponent {
  constructor(public analytics: AnalyticsService) {
  }
}

As usual, thanks for your prompt reply.

**Comment by NathanWalker** [comment]
This is the AppComponent.
Need to see the PatientComp ;)
At least the @Component part of it anyway.

**Comment by st-clair-clarke** [comment]
A thousand apologies.

import { MATERIAL_DIRECTIVES } from 'ng2-material/all';
import { BaseComponent } from '../../../../../frameworks/core.framework/index';

//import { MdButton } from "ng2-material/components/button/button";

@BaseComponent({
                 selector   : 'epimss-patient',
                 templateUrl: './src/frameworks/epimss.framework/components/reg/patient/patient.comp.view.html',
                 directives : [MATERIAL_DIRECTIVES]
               })
export class PatientComp {
}

**Comment by st-clair-clarke** [comment]
### patient.comp.view.html

`
<div>
  This is my patient component!
</div>`

**Comment by NathanWalker** [comment]
Change:

```
templateUrl: './src/frameworks/epimss.framework/components/reg/patient/patient.comp.view.html',
```

To:

```
templateUrl: './frameworks/epimss.framework/components/reg/patient/patient.comp.view.html',
```

It must be relative to your server root, which in this case is `dist/dev`. If you look in there, you will see **no** `src` folder, just `frameworks` in the root.

Hope you're liking the seed.
Cheers! :+1:

**Comment by NathanWalker** [comment]
Btw, I'll comment on the SO post now with that as well.

**Comment by NathanWalker** [comment]
If you could upvote that SO answer when you get a chance would be appreciated!

**Comment by st-clair-clarke** [comment]
Your answer is 100% on the money Nathan. Thanks. To think I have spent the last three days trying to solve it! The seed is the best one yet. I have big plans for what I am doing and the seed is the perfect start. I am in the process of setting up a github account so I can synchronised my repo and yours. I like the translation and the ability to run the code on the differing OS's. Thanks again.

And remember, the things that I cannot post to angular2-seed that relates to your project, I will have to post here.

Great seed!
