### ISSUE TITLE
[bug]: language selector not working in web version

### ISSUE THREAD

**Issue by geminiyellow** [NathanWalker/angular-seed-advanced#330]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**

clone from `master` branch, and start it by `npm start`
right-top's **Change Language** select's options has nothing.

**Expected behavior**

see the `availableLanguages` list

**reasons**
- `multilinguage.service.ts` 

  `init` and `changeLang` use the `ChangeAction`, the action type is `ActionTypes.CHANGE`

- `multilinguage.reducer.ts`

  `reducer` change the language just in `ActionTypes.LANG_CHANGED`, so, `ChangeAction` will do nothing.

- `lang-switcher.component.ts`
  
  `ngOnInit` 's `this.store.select('i18n').subscribe` always got `{}` from store.

**fix**

i think just change the action Type will fix this bug.  @NathanWalker please help me.

**related**

`ng2-translate`'s  `setDefaultLang` not working.

**Comment by NathanWalker** [comment]
Hi @geminiyellow I just cloned fresh master, ran `npm i`, then `npm start` and do not see this issue.
I'm running:
node `6.9.1`, npm `3.10.9` and on a Mac (Sierra)

It could be your environment?

**Comment by geminiyellow** [comment]
@NathanWalker thanks for your reply

```
~> node -v
v7.4.0

~> npm -v
4.0.5

~> mac -v
10.12.3 Beta
```

**Comment by geminiyellow** [comment]
@NathanWalker ok,  11d641869052fcfedaa0af1316dc7b6dddef18da this merge do not see this issue. please close it.

**Comment by NathanWalker** [comment]
Awesome, thanks for update 👍
