### ISSUE TITLE
Android App crashes from fresh clone on Windows

### ISSUE THREAD

**Issue by ponty7** [NathanWalker/angular-seed-advanced#332]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
When running livesync, "npm run start.livesync.android", Android app fails to launch with following error:
![image](https://cloud.githubusercontent.com/assets/13456914/21827277/d46732d8-d73f-11e6-8226-775a7d5e7538.png)
'
When running without livesync, "npm run start.android":
![image](https://cloud.githubusercontent.com/assets/13456914/21827570/1c274a80-d741-11e6-8420-c8c68a2d1ef4.png)
 

**Expected behavior**
Android App launches correctly

**Minimal reproduction of the problem with instructions**
- Clone repository
- "npm i" from root
- "npm start.run.android" from root

**What is the motivation / use case for changing the behavior?**
 This seems to be a result of the resolution of this bug:
https://github.com/NathanWalker/angular-seed-advanced/issues/327

**Please tell us about your environment:**
 - Windows 10
 - tns - 2.4.2
 - npm - 3.10.9
 - node - v6.9.2

* **Angular Seed Version:** `aaaaf75`
11d6418

* **Node:** `node --version` = v6.9.2

**Comment by psmontte** [comment]
I am having the exact same error. My environment:

Windows 10
tns - 2.4.2
npm - 4.0.5
node - v6.9.4
[package.json.txt](https://github.com/NathanWalker/angular-seed-advanced/files/698211/package.json.txt)

**Comment by NathanWalker** [comment]
I'll take a look at this in morning; just curious I noticed you mentioned 'npm start.run.android', but the command is 'npm run start.android'?

Also as always just make sure you have cleared when pulling in upstream changes.

**Comment by psmontte** [comment]
In my case, I am running it on connected device using 'npm run start.livesync.android.device'.

**Comment by ponty7** [comment]
@NathanWalker , sorry that's a typo in repro steps, correct command is above second image of emulator. Again, this is from a fresh clone, and from #327, this was happening when all folders where wiped/cleaned.

**Comment by Dimanoid** [comment]
Same here. Compiled on Windows 10 and Linux Ubunto 14.04, ran on emulator and real device. Same error.
I posted logs and screenshot at [stackoverflow](http://stackoverflow.com/questions/41589299/angular2-seed-advanced-got-rangeerror-maximum-call-stack-size-exceeded)

**Comment by Dimanoid** [comment]
Same here.
Compiled on Windows 10 and Linux Ubuntu 14.04, ran on emulator and real device.
I posted logs and screenshot on [stackoverflow](http://stackoverflow.com/questions/41589299/angular2-seed-advanced-got-rangeerror-maximum-call-stack-size-exceeded)

**Comment by cjdreiss** [comment]
Same issue here as well, just tried this project out yesterday.  iOS simulator runs fine, as well as the web version. Android shows the same error "Maximum call stack size exceeded".

I've only changed the name in package json, other than that, this is a fresh clone.
macOS Sierra, 10.12.2 (16C67)
tns 2.4.2
npm 3.10.3
node 6.7.0

**Comment by marcoamtz** [comment]
I'm having the same issue. 

This is my environment:

macOS Sierra, 10.12.2
tns 2.4.2
npm 4.0.5
node 6.9.1

**Comment by Dimanoid** [comment]
I pulled the latest changes and now android app works ok. Thx!

**Comment by ponty7** [comment]
+1 Yes, it's working for me too now, I'll close this, thank you!

One thing I do see often is this error and have to rerun command. Seems to be a TCP connection issue, has anyone else run into this?

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)
