### ISSUE TITLE
Question: Route parameters across all platforms

### ISSUE THREAD

**Issue by sunjith** [NathanWalker/angular-seed-advanced#334]
First of all, this is just a question not an issue.

How can we implement route parameters across all platforms?
Web needs ActivatedRoute from '@angular/router' whereas Nativescript needs PageRoute from 'nativescript-angular/router'

**Comment by NathanWalker** [comment]
Hi @sunjith You can use `ActivatedRoute` with NativeScript just the same as web 😄 
See this for example (again, it's identical to web - it's quite nice):
https://github.com/NativeScript/nativescript-angular/blob/master/ng-sample/app/examples/router/router-outlet-test.ts#L33-L35

With route config example here:
https://github.com/NativeScript/nativescript-angular/blob/master/ng-sample/app/examples/router/router-outlet-test.ts#L62-L65

**Comment by sunjith** [comment]
@NathanWalker Great! Thanks a lot.
