### ISSUE TITLE
mkdir -p for windows users

### ISSUE THREAD

**Issue by Dutchboy** [NathanWalker/angular-seed-advanced#339]
[x] bug report

**Current behavior**
:-) The windows-mkdir is not the same as the unix (mac) cli... So, it does make a dir "-p"
I found this glitch out doing npm run nativescript-install

BTW - I love ALL your efforts! Today I've installed Gitlab and cloned your project - let's see how I can contribute.... Or better "if" (and "from when")

**Comment by Swiftwork** [comment]
This is also true for `rm -rf`. I suggest replacing these with node packages `mkdirp` and `rimraf`.

**Comment by ponty7** [comment]
+1 Window users won't be able to install/build/run android app with updated scripts in nativescript/package.json

**Comment by Dutchboy** [comment]
How wonderful to realize I've "caused" a positive change!! And how fast you all reacted! Perfect! Thanks!

**Comment by ponty7** [comment]
+1 Thanks guys!
