### ISSUE TITLE
404 on installing new npm packages

### ISSUE THREAD

**Issue by viktorstaikov** [NathanWalker/angular-seed-advanced#340]
Hi,

I'm trying to integrate Everlive SDK in the project, but after successful build I get 404 in the browser.

> Error loading http://localhost:5555/node_modules/everlive-sdk.js as "everlive-sdk"

Since this is the first package that I'm adding, is there anything else to be done in order to work?

P.S. This is not the appropriate path to the main file. It is _./node_modules/everlive-sdk/dist/everlive.all.min.js_

**Comment by NathanWalker** [comment]
Hi @viktorstaikov you will need to modify the systemjs config here, please see comment:
https://github.com/NathanWalker/angular-seed-advanced/blob/master/tools/config/project.config.ts#L33-L41

**Comment by viktorstaikov** [comment]
Hi @NathanWalker,
this worked for the everlive-sdk, but now the error is about http module. Shouldn't that be automatically added since it's nodejs module?

**Comment by lwouis** [comment]
I just picked up the project, and I have to agree with @viktorstaikov that it's not very intuitive to add immutable.js or some other common lib, and have a 404 at runtime. Looking at project.config.ts it seems from the commented lines that i'm supposed to manually add the paths to npm modules. This seems fragile and time-consuming.

What in the project is generating the need to manually do this? A simpler project sure doesn't require manual listing of npm dependency internals. Is it a constraint from Rollup?
