### ISSUE TITLE
Deep-freeze replaced with deep-freeze-strict, but not reflected in project.

### ISSUE THREAD

**Issue by Swiftwork** [NathanWalker/angular-seed-advanced#341]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

The web version won't load due to `node_modules/deep-freeze-strict.js` isn't found.

**Expected behavior**

Should be able to resolve dependency.

**Minimal reproduction of the problem with instructions**

The node module `ngrx-store-freeze` has changed dependency from `deep-freeze` to `deep-freeze-strict`, but angular-seed-advanced has not reflected this. See:
[desktop.libs.ts](https://github.com/NathanWalker/angular-seed-advanced/blob/11d641869052fcfedaa0af1316dc7b6dddef18da/tools/tasks/project/desktop.libs.ts#L15)
[seed-advanced.config.ts](https://github.com/NathanWalker/angular-seed-advanced/blob/dadb1052f74cb3114547de94d297cc591ed27ab1/tools/config/seed-advanced.config.ts#L130-L131)
[karma.conf.js](https://github.com/NathanWalker/angular-seed-advanced/blob/11d641869052fcfedaa0af1316dc7b6dddef18da/karma.conf.js#L56)

**What is the motivation / use case for changing the behavior?**

Breaks execution.

**Please tell us about your environment:**

Windows 64bit, fresh angular-seed-advanced setup.

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 7.40

**Comment by NathanWalker** [comment]
Hi @Swiftwork thanks for this - would you like to submit a PR for this?
