### ISSUE TITLE
Nativescript Build Bugs.

### ISSUE THREAD

**Issue by psmontte** [NathanWalker/angular-seed-advanced#343]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter]
```

**Current behavior**
npm run start.android, runs first time and launches the app. But not second time.
npm run start.livesync.android.device causes the following error (even on first run):
```
[01:26:09] Starting 'build.tns'...
[01:26:09] Starting 'build.assets.tns'...
[01:26:09] Finished 'build.assets.tns' after 221 ms
[01:26:09] Starting 'build.tns_html_css'...
[01:26:10] Finished 'build.tns_html_css' after 296 ms
[01:26:10] Starting 'build.js.tns'...
[01:26:13] Finished 'build.js.tns' after 3.46 s
[01:26:13] Finished 'build.tns' after 3.98 s
[0] 'gul' is not recognized as an internal or external command,
[0] operable program or batch file.
[1] 'build.tns.watch'' is not recognized as an internal or external command,
[1] operable program or batch file.
[2] 'c' is not recognized as an internal or external command,
[2] operable program or batch file.
```

**Expected behavior**
npm run start.livesync.android, should launch the app successfully.

**Minimal reproduction of the problem with instructions**
- Clone Repositary
- cd angular-seed-advanced
- npm install
- npm run start.android (npm run start.livesync.android.device)

**What is the motivation / use case for changing the behavior?**
To Remove any Build Bugs.

**Please tell us about your environment:**
- Windows 10
- npm 3.10.10
- tns 2.4.2

**Angular Seed Version:** 
0e7c923

**Node:** 
v6.9.4

**Comment by amirtoole** [comment]
Are you sure you have latest code and that you haven't made any changes locally?
```
[0] 'gul' is not recognized as an internal or external command,
```
Sounds like p from 'gulp' was removed.

**Comment by NathanWalker** [comment]
@psmontte looks like you may have a local typo - possible you may have pulled down the repo and accidentally hit a keystroke in the package file as master does not contain such typos:
https://github.com/NathanWalker/angular-seed-advanced/blob/master/package.json#L51-L52

**Comment by ghys** [comment]
It's actually a real bug - the Windows command interpreter doesn't like single quotes, replacing them with (escaped) double quotes in `package.json` solves the problem.
```
    "start.livesync.android": "npm run nativescript-install && gulp build.tns && concurrently --kill-others \"gulp build.tns.watch\" \"cd nativescript && tns livesync android --emulator --watch\"",
    "start.livesync.android.device": "npm run nativescript-install && gulp build.tns && concurrently --kill-others \"gulp build.tns.watch\" \"cd nativescript && tns livesync android --watch\"",
```

**Comment by NathanWalker** [comment]
oh interesting! thanks @ghys would you like to submit a PR for that?

**Comment by ghys** [comment]
@NathanWalker sure! Here you go - #345.
