### ISSUE TITLE
AoT build successfully but it doesn't work

### ISSUE THREAD

**Issue by massivex** [NathanWalker/angular-seed-advanced#346]
[X ] bug report => search github for a similar issue or PR before submitting

**Current behavior**
Website doesn't work in browser after AoT build. A JS exception occurs "DI Error"

> Error: DI Error
>     at e.v (http://localhost:8888/js/shims.js?1485643413974:5:670)
>     at e [as constructor] (http://localhost:8888/js/app.js?1485643413974:25:24830)
>     at e [as constructor] (http://localhost:8888/js/app.js?1485643413974:24:28661)
>     at new e (http://localhost:8888/js/app.js?1485643413974:24:29015)
>     at t._throwOrNull (http://localhost:8888/js/app.js?1485643413974:24:27298)
>     at t._getByKeyDefault (http://localhost:8888/js/app.js?1485643413974:24:27650)
>     at t._getByKey (http://localhost:8888/js/app.js?1485643413974:24:27210)
>     at t.get (http://localhost:8888/js/app.js?1485643413974:24:23586)
>     at e.o.get (http://localhost:8888/js/app.js?1485643413974:22:29454)
>     at Object.i [as _createReducerIfExtension] (http://localhost:8888/js/app.js?1485643413974:5:91)
>     at e.get [as _Reducer_72] (http://localhost:8888/js/app.js?1485643413974:28:12528)
>     at e.get [as _Store_74] (http://localhost:8888/js/app.js?1485643413974:28:13020)
>     at e.createInternal (http://localhost:8888/js/app.js?1485643413974:28:19245)
>     at e.o.create (http://localhost:8888/js/app.js?1485643413974:22:29267)
>     at t.create (http://localhost:8888/js/app.js?1485643413974:22:29003)
> 

**Expected behavior**
I expected that website works after I build it with AoT

**Minimal reproduction of the problem with instructions**
1. execute `npm run build.prod.aot`
2. open page `dist/prod/index.html` inside a browser or serve it with a local web server

**Please tell us about your environment:**
Windows 10, node 9.6.2, npm 3.10.9, Visual Studio Code

* **Angular Seed Version:** `a8b432c`
* **Node:** `node --version` = 9.6.2

**Comment by massivex** [comment]
After some research I found this error is generated when angular tries to resolve `ReflectiveInjector(providers: [ "t" ])`

So looking in internet I found that ReflectiveInjector is a class that works only in JIT mode  as discussed here
https://github.com/angular/angular/issues/12750

So it cannot be used in AoT mode :(

Now I' trying to find where ReflectiveInjector is used and if it can be safely removed when AoT build is selected. 

Any further investigation or suggestion to resolve this issue is very appreciated.

Thanks,
Emanuele

**Comment by NathanWalker** [comment]
Thanks for investigating @massivedynamicsrls, I'll also take a look to see if I can repro this hopefully tomorrow or by Wednesday.

**Comment by sanderbos1402** [comment]
any progress? This is also breaking me up.
will investigate if needed, but would be nice to know what has been done about this already

**Comment by massivex** [comment]
I tried to solve it but without success... this is what I did.
First of all I deactivated minify and mangle in (build.bundles.app.exp.ts and minify.bundles.ts)
So I got the real error message  
```
Message: "No provider for Dispatcher!"
Error: DI Error
    at NoProviderError.ZoneAwareError (http://localhost:5555/js/shims.js?1487666215001:824:33)
    at NoProviderError.BaseError [as constructor] (http://localhost:5555/js/app.js?1487666215004:51070:18)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:5555/js/app.js?1487666215004:50239:18)
    at new NoProviderError (http://localhost:5555/js/app.js?1487666215004:50256:18)
    at ReflectiveInjector_._throwOrNull (http://localhost:5555/js/app.js?1487666215004:50126:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:5555/js/app.js?1487666215004:50150:25)
    at ReflectiveInjector_._getByKey (http://localhost:5555/js/app.js?1487666215004:50108:25)
    at ReflectiveInjector_.get (http://localhost:5555/js/app.js?1487666215004:50026:23)
    at WebModuleInjector.NgModuleInjector.get (http://localhost:5555/js/app.js?1487666215004:45570:54)
    at Object._createReducerIfExtension (http://localhost:5555/js/app.js?1487666215004:7257:33)
    at WebModuleInjector.get [as _Reducer_72] (http://localhost:5555/js/app.js?1487666215004:55168:50)
    at WebModuleInjector.get [as _Store_74] (http://localhost:5555/js/app.js?1487666215004:55188:87)
    at WebModuleInjector.createInternal (http://localhost:5555/js/app.js?1487666215004:55398:81)
    at WebModuleInjector.NgModuleInjector.create (http://localhost:5555/js/app.js?1487666215004:45559:32)
    at NgModuleFactory.create (http://localhost:5555/js/app.js?1487666215004:45542:20)
```

Error throws when @ngrx/store/init requires Dispatcher... looking at google for "No provider for Dispatcher" there is an closed issue on @ngrx/store about https://github.com/ngrx/store/issues/295
They suggest to bump angular to 2.4.x

So I upgraded angular and all dependencies to use angular 2.4.x, but at the end I got the same error :/

I hope that this information is most useful to you than they have been to me,
Emanuele

**Comment by sanderbos1402** [comment]
@massivedynamicsrls
I think it in the stordevtools.
need to check with a clean start. I did so many changes that I cannot be sure yet that this was the only issue, but is seems this needs to be removed from the web module

    StoreModule.provideStore(AppReducer),
    //StoreDevtoolsModule.instrumentOnlyWithExtension(),  <-- this line
    EffectsModule.run(MultilingualEffects),

@NathanWalker  Should not be included in production version anyway I think, since this is a dev extension.

Will check later with a clean clone and update if this was the only change that fixes this issue or that some other changes I made also have an impact.

**Comment by massivex** [comment]
@sanderbos1402 **you're right!!!** 💯 👍  

I downloaded a clean clone 
I loaded StoreDevtoolModule only when `String('<%= BUILD_TYPE %>') === 'dev'`
and error goes away!

Now I can compile AoT and the page is loaded at lightning speed!

**Comment by sanderbos1402** [comment]
shouldn't this issue be closed now?

**Comment by NathanWalker** [comment]
Yes indeed AoT builds work well on master now 👍
