### ISSUE TITLE
Improve the code sharing best practices documentation around OpaqueToken usage.

### ISSUE THREAD

**Issue by derekdon** [NathanWalker/angular-seed-advanced#349]
**I'm submitting a ...**
```
[x] feature request
```
> Don’t import {N} modules into your components/services. {N} modules can only be used inside the {N} app therefore cannot be shared. To get around this, use OpaqueTokens...
[How-to-integrate-Firebase-across-all-platforms](https://github.com/NathanWalker/angular-seed-advanced/wiki/How-to-integrate-Firebase-across-all-platforms-(web-nativescript-desktop))

Perhaps I'm missing something obvious, but I'm not sure why the OpaqueToken strategy is used in the linked wiki example. Perhaps someone with more experience sharing code across platforms could advise?

From my understanding, NSDatabaseService (Native) and DatabaseService (Web) have to know the api of the firebase dep being injected anyway to operate on it, so can't each one simply import that directly? I believe these classes aren't shared so not sure what's being gained having the OpaqueToken in place ie. `@Inject(FIREBASE) firebase:any`. If they both implemented a common interface like IDatabaseService, would the same setup used for WindowService/WindowNative not work in this case? 

In the wiki post under "Using the DatabaseService", the home.component.ts imports the database service (from somewhere that I don't think exists if you follow along the steps), `import {DatabaseService} from '../../shared/core/services/database.service';`. I believe this is trying to import the web version of the database service? Couldn't the constructor here not simply have `private databaseService: IDatabaseService` and the our `@NgModule({...})` wiring take care of the rest?

For my particular use case I want to use [nativescript-couchbase](https://github.com/couchbaselabs/nativescript-couchbase) for the native side and [PouchDB](https://github.com/pouchdb/pouchdb) for the web side with a common interface, for example:
```
    getDatabase() {
    }
    startSync(continuous: boolean = true) {
    }
    stopSync() {
    }
```
I've used both of these successfully in isolation in the past, so this seems like a good opportunity to test drive an all platform setup. I just need to understand if I've missed something obvious here before I continue.

**What is the motivation / use case for changing the behavior?**
To make it clear what the difference is between this approach and the setup of the WindowService/WindowNative for example.

**Please tell us about your environment:**
Mac OSX, Webstorm

* **Angular Seed Version:** `74f7991`

* **Node:** `node --version` = 6.9.4

**Comment by psmontte** [comment]
I too have struggled with this.

It would be much appreciated, if various code sharing strategies, along with their suitability could be explained in the documentation itself.

**Comment by NathanWalker** [comment]
Thanks for the input, I too would like to expand that section in the Readme.

Briefly... @derekdon 

> From my understanding, NSDatabaseService (Native) and DatabaseService (Web) have to know the api of the firebase dep being injected anyway to operate on it, so can't each one simply import that directly? 

Yes with that general example that is true. However it's just an example. The `OpaqueToken` strategy is a solid way to solve use cases in general with code sharing, which is why it is used as an example. Consider a NativeScript lib like https://github.com/NathanaelA/nativescript-dom which provides a mirrored api to actual DOM methods. Using an `OpaqueToken` to represent the `document` global object on web and the plugin for the mobile app, you could seamlessly use that injected token across services and components without worrying that accessing some api's would break mobile and/or the other. Again just example of how to handle such cases.

> If they both implemented a common interface like IDatabaseService, would the same setup used for WindowService/WindowNative not work in this case?

It does work in that case currently (The approach is the same as DatabaseService minus the OpaqueToken, only because no 3rd party plugin is used for window since it's a global object):
https://github.com/NathanWalker/angular-seed-advanced/blob/master/src/client/app/shared/core/services/window.service.ts#L8
https://github.com/NathanWalker/angular-seed-advanced/blob/master/nativescript/src/mobile/core/services/window-native.service.ts#L8
Since these are injected services (using Angular DI), you can't simply inject an interface, but rather a token which may implement that common interface, which is done with `WindowService`.

> In the wiki post under "Using the DatabaseService", the home.component.ts imports the database service (from somewhere that I don't think exists if you follow along the steps)...

The location `core/services` is merely a suggestion, however where you create that service is really up to you. The wiki instructs to create the service in that location.

> I want to use nativescript-couchbase for the native side and PouchDB for the web side with a common interface

Excellent, that will work well with `OpaqueToken`'s or 2 angular services, one for the web, one for mobile (providing your `nativescript-couchbase` service wrapper for the web token in `nativescript/app/native.module` or your own module). Since it will be your web token (ie, `DatabaseService`) which is actually injected and used throughout your shared codebase. During mobile bootstrap, you would stub (*provide*) in your `NSDatabaseService` so **under the hood** it would use the right implementation for the right platform.

Hope that makes sense.

**Comment by derekdon** [comment]
@NathanWalker Thank you for your speedy response. The information you provided has been very helpful.

> Consider a NativeScript lib like https://github.com/NathanaelA/nativescript-dom which provides a mirrored api to actual DOM methods. Using an OpaqueToken to represent the document global object on web and the plugin for the mobile app, you could seamlessly use that injected token across services and components without worrying that accessing some api's would break mobile and/or the other.

Yes this makes perfect sense and is a great example, as the injected OpaqueToken object is presenting a consistent API to the services and components. I can see the value in such cases. This was the main cause of my confusion since NSDatabaseService and DatabaseService in the wiki have different apis to deal with so the OpaqueToken strategy seemed irrelevant to me as a result.

> Since these are injected services (using Angular DI), you can't simply inject an interface

Yep sure, my mistake here...

> Excellent, that will work well with OpaqueToken's or 2 angular services, one for the web, one for mobile

Yeah I'm going to go with the 2 angular services approach in this case. 

> Since it will be your web token (ie, DatabaseService) which is actually injected and used throughout your shared codebase. During mobile bootstrap, you would stub (provide) in your NSDatabaseService so under the hood it would use the right implementation for the right platform.

On this topic, do you know if the DatabaseService code is bundled in the native app as a side effect of this, even though we only care about the NSDatabaseService in a build targeting native? If so I can see potential bloat occurring should DatabaseService be a large file or if it imports PouchDB and other web only deps directly.

Thanks again for your insights.

**Comment by NathanWalker** [comment]
Excellent, glad that made sense.

Good point on `DatabaseService` being bundled in even if only the stub is used under the hood. My understanding is that it would be bundled which definitely would not be ideal. I believe some webpack loaders could be used to help make this better. Would be curious to hear other thoughts regarding this... @d3viant0ne always has clever ideas ... constantly on the hunt for the ideal here.

**Comment by derekdon** [comment]
@NathanWalker Yeah it's a tricky one. I've spent far too much time recently working on a webpack 2 config for a very large project, and although it's possible to configure it and the loaders to do pretty much anything, perhaps there's a simpler and more explicit way to achieve this. I'm thinking along the lines of providing a bare minimal base class ie. DatabaseService that implements IDatabaseService and require both the native.module and web.module to provide an actual complete implementation of it. ie. NSDatabaseService and WebDatabaseService. The issue with this is there's another actor/class involved but if it's a base class then perhaps it's not an issue, however the extra boilerplate in the web.module wouldn't be ideal (but I could live with that). I'm sure there are many other ways to do it... but personally I couldn't live with my native app containing web only code, so it would be great to find a best practice solution for this.

**Comment by famargon** [comment]
Hello everybody,

I'm sorry but i'm stuck with this, i'm unable to understand the part of "Using the database service" as i see it the thing is that in the home component the database.service imported doesn't exists. 
However we have two database.services and then we just can't import just one of these in the components, am i right? What i'm missing??
It's important to mention that i also don't understand the windowService that is part of the seed, the thing i dont understand if why you import o ley the web implementation of this WindowService in the components? 

Just one more question, if i implement 2 services based on an interface(IService) and set the providers in the modules with an OpaqueToken, then, can i just inject this in my components in this way...
@Inject(MY_TOKEN) myService: IService
Or this other way is needed
@Inject(MY_TOKEN) myService: any

Sorry for my poor English
Thanks in advance to all

**Comment by psmontte** [comment]
**Say you want different implementations of "alert" message for Web/NS, this is what you need to do:**


```TypeScript
//Define an Interface (will ensure web/ns classes implement similar behaviour), in angular-seed-advanced-master\src\client\app\shared\core\interfaces\iuiservice.ts
export interface IUIService {
  alert(message: string);

}



//Define shared class, in angular-seed-advanced-master\src\client\app\shared\core\services\uiservice.ts
export class UIService implements IUIService{
  alert(message: string) {};
}

//Define NativeScript Specific Implementation in, angular-seed-advanced-master\nativescript\src\mobile\core\services\native-uiservice.ts
import * as dialogsModule from "ui/dialogs";
export class NativeUIService implements IUIService {
  public alert(message: string) {
    //Using NS Dialogs. Or use any other NS plugin/library
    return dialogsModule.alert({
        title: "Message",
        okButtonText: "OK",
        message: message
    });
  }
}

//Set provider in,  angular-seed-advanced-master\nativescript\src\native.module.ts
import { NativeUIService } from './mobile/core/index';
import { UIService } from './app/shared/core/services/ui.service';

   providers: [
        { provide: UIService, useClass: NativeUIService },
	


//Define Web Specific Implementation in, angular-seed-advanced-master\src\client\web-uiservice.ts
export class WebUIService  implements IUIService  {
  //Or use any other plugin/library
  public alert(message: string) {
	 //Use
    alert(message);

  }		
}



//Set provider in,  angular-seed-advanced-master\src\client\web.module.ts
import { WebUIService} from './web-ui.service'
import { UIService } from './app/shared/core/services/ui.service';

  providers: [
    { provide: UIService, useClass: WebUIService },



//usage
import { UIService } from '../../shared/core/index';

constructor(private ui: UIService)
{
	
}
```

**Comment by NathanWalker** [comment]
Thank you @psmontte I have provided your clear example here:
https://github.com/NathanWalker/angular-seed-advanced/wiki/OpaqueToken-Example
