### ISSUE TITLE
docker compose prod query

### ISSUE THREAD

**Issue by sparachi** [NathanWalker/angular-seed-advanced#350]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

This is more of support question due to my ignorance on docker. I would like to build the docker image to be able to push to ECS and deploy into my EC2 instances. The part I am struggling with is, when I run the commands from readme file, I see 'nginx', 'angular-seed'  two images created. I tried to push angular-seed to AWS and nothing worked, as soon as ECS starts the container it would stop. When I investigated further, I observed when I did the prod build docker compose command, the code is being copied to container running based on nginx image. So I pushed the nginx image to AWS ECR, and spin up the instances. when I access I see only nginx welcome page, I SSHed into my instances and saw the nginx docker container does not have the code. 

so when I run the commands in readme file, what docker artifacts are produced, which will have the code to be able to push to any container services. 

Any help would be appreciated.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 7.4.0

**Comment by Kaffiend** [comment]
@sparachi 
My implementation doesn't use the docker functionality, but the production docker container should be serving the files from [here](https://github.com/NathanWalker/angular-seed-advanced/blob/30980bb6fbedd0f900a119a8c89cad74551159d0/.docker/nginx.conf#L31) with NGINX which all should be in your container. This is also where you configure your SSL etc. if needed. Though using AWS, SSL is probably handled with a proxy before your container like Azure does.

Disclaimer** my docker knowledge is limited. I've only started messing with it.

**Comment by sparachi** [comment]
@Kaffiend thanks for you inputs. I agree that the files needs to be available in /var/www/dist/prod and will be served by Nginx. But the docker compose file mounts volume for /dis/prod files from the host. so on my dev machine that works perfectly fine. 

But, after I follow the readme and after the three steps, the containers running on my dev machine will work well since the code is stilling locally on my dev machine. if I have to push this container to something like dockyard or AWS ECR, and run later the container generated out of the nginx simply would not run since it does not have any mount volumes of the EC2 host it runs.

I started digging little deep for answers, as far as I understand there seems to be some disconnect between the docker compose services.  I am appreciative of the fact that two separate services are being built one for seed and other for nginx-prod, to address separate of concerns but I don't see a dependency really between the services. as long as we push the dist/prod artifacts to nginx container it should work. 

so what I'm thinking is to modify the 'angular-seed-nginx' docker compose service to have CP/COPY (copy. don't know if compose syntax allows me to do that) command to take nginx.conf , dist/prod artifacts and push it to the image into respective locations. This should eliminate dependency of container on host volumes mounted, and be fine since I'm not running a database.

Let me know if someone has better ideas or i'm defeating the purpose of the compose file in the seed.

**Comment by Kaffiend** [comment]
@sparachi 
looking [here](https://github.com/NathanWalker/angular-seed-advanced/blob/master/docker-compose.production.yml#L30) i see what you mean, its mounting the `dist/prod/` as a volume to the nginx directory. beings that directory doesnt exist in your AWS instance that would create an issue. You would need some persistent storage for your instance.

**Comment by sparachi** [comment]
@Kaffiend yes exactly, thanks for looking into that.  But is that the intent? the prod code is supposedly either built inside the container or as we have compose services, it should be shared between the containers spun by services. I assume intent is to facilitate sharing. looking for advice from docker gurus on what is the right.

**Comment by NathanWalker** [comment]
Closing but feel free to continue discussion here!
