### ISSUE TITLE
Additional Packages Electron

### ISSUE THREAD

**Issue by Kaffiend** [NathanWalker/angular-seed-advanced#352]
[* ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter]
**Current behavior**
Added additional packages to the `project.config`, they get dumped out correctly with `serve.dev` but for electron only the `NPM_DEPENDENCIES` and additional packages declared in the `advanced-seed-config` get dumped out to the `dev` directory's `node_modules`

**Expected behavior**
Additional packages from `project.config.ts` to be correctly discovered and placed the build directory.

**Minimal reproduction of the problem with instructions**
install any of the `@progress/kendo-angular-**` packages and declare them in the additional packages section of the `project.config.ts` like so..
```
 {
        name: '@progress/kendo-angular-buttons',
        packageMeta: {
          main: './dist/npm/main.js',
          defaultExtension: 'js'
        },
      },
```

**Please tell us about your environment:**
Windows 10 Enterprise 64-bit.
VS Code/Vim

* **Angular Seed Version:** `10c72726`

* **Node:** `node --version` = 6.9.5

**Comment by Kaffiend** [comment]
[Here](https://github.com/NathanWalker/angular-seed-advanced/blob/master/tools/tasks/project/desktop.libs.ts#L7) is the issue. A static list of dependencies and only the [NPM_DEPENDENCIES](https://github.com/NathanWalker/angular-seed-advanced/blob/master/tools/tasks/project/desktop.libs.ts#L18) get pulled from the whats added by the `project.config.ts` at first i suspecting there was an issue with the `@progress` part of the packages i was adding, but it appears any packages that added via additionalPackages extension are not brought to the build directory for the `desktop.libs` task.

**Comment by Kaffiend** [comment]
PR #353 submitted for review as a possible solution.

**Comment by ghost** [comment]
I am trying to install new packages through package.json but they are not installed. additional packages are getting escaped while commanding npm install.

how i install all these packages?
