### ISSUE TITLE
Anyone using this seed to target android wear or watch os?

### ISSUE THREAD

**Issue by derekdon** [NathanWalker/angular-seed-advanced#355]
**I'm submitting a ...**
```
[x ] feature request
```

Is anyone using this seed as a basis to target android wear or watch os? If so are there any pitfalls or examples you could share?

**What is the motivation / use case for changing the behavior?**
I believe it would add a lot of value to start a discussion about targeting android wear or watch os within this seed.

**Please tell us about your environment:**
Mac OSX, Webstorm

* **Angular Seed Version:** `74f7991`

* **Node:** `node --version` = 6.9.4

**Comment by psmontte** [comment]
You would be only using this seed, if you plan to target multiple platforms with same code base.

**Comment by derekdon** [comment]
@psmontte yes I meant in addition to the others.

**Comment by NathanWalker** [comment]
Feel free to continue discussion here, just closing to cleanup outstanding issues.
