### ISSUE TITLE
How to catch up with the seed?

### ISSUE THREAD

**Issue by viktorstaikov** [NathanWalker/angular-seed-advanced#358]
Hi,

Is there a way to catch up with all the changes of the seed project if I didn't completed the initial setup as described?
For some reason it didn't worked for me so I just pushed it in my repo. I can see "upstream" in GitKraken, but I can't merge due to _fatal: refusing to merge unrelated histories_.

Will be very thankful.

Cheers

P.S. I've already did some development on the project, so starting all over again is not preferable.

**Comment by NathanWalker** [comment]
Hi @viktorstaikov the easiest way (if you are far behind latest master) is to just checkout a new clone and drop your code back in. Your customizations should primarily be isolated in the src/client folder, however if you had made many changes across the build, etc, could be trickier. Definitely depends.

If the only issue you see when trying to merge upstream is `unrelated histories`, try doing either of these:

Option A. Upgrade git to 2.9+
Option B. `git fetch upstream && git merge upstream/master --allow-unrelated-histories`

Either of those should work for ya 👍
