### ISSUE TITLE
ask a question. How to use html replace xml

### ISSUE THREAD

**Issue by mmoonn2** [NathanWalker/angular-seed-advanced#36]

**Comment by NathanWalker** [comment]
Hi @junjun16818 Thanks for the question. If I understand correctly, are you asking about how the NativeScript XML/HTML swap works and how to set it up?

If so, please read [this article first](http://angularjs.blogspot.com/2016/03/code-reuse-in-angular-2-native-mobile.html) to understand how it works and then lemme know if you are still needing clarification.

**Comment by NathanWalker** [comment]
@junjun16818 If that article helped to answer your question, please close this issue or let me know if you need further explanation, thanks!
