### ISSUE TITLE
How to generate Android apk?

### ISSUE THREAD

**Issue by wuardyn** [NathanWalker/angular-seed-advanced#360]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

[npm-debug.log.txt](https://github.com/NathanWalker/angular-seed-advanced/files/788993/npm-debug.log.txt)

**Current behavior**

When run "npm run buil.android", work until get this messange, the apk is not generated

Total time: 1 mins 3.788 secs
Successfully prepared plugin nativescript-angular for android.
Successfully prepared plugin nativescript-intl for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (android)
Executing after-prepare hook from C:\Desarrollo\Source\NASA3\nativescript\hooks\after-prepare\nativescript-dev-android-snapshot.js
Searching for devices...
Starting Android emulator with image Android_Accelerated_x86
Cannot run your app in the native emulator. Increase the timeout of the operation with the --timeout option or try to restart your adb server with 'adb kill-server' command. Alternatively, run the Android Virtual Device manager and increase the allocated RAM for the virtual device.
run android

**Expected behavior**

**Minimal reproduction of the problem with instructions**

"npm run buil.android"

**What is the motivation / use case for changing the behavior?**

I want generate apk without  run emulator

**Please tell us about your environment:**

Windows 10

* **Angular Seed Version:** `8d0eb877c4d2d700426bcb23734569fdab20f660`

* **Node:** `node --version` =v6.9.5

**Comment by NathanWalker** [comment]
Hi @wuardyn instead of using the npm script (which is used to create an AoT bundle of the build), just use things manually:
```
cd nativescript
```
Then follow these instructions to build a release APK:
https://docs.nativescript.org/publishing/publishing-android-apps
*Caution:* Take note of the keystore generation and do **not** lose that keystore so email yourself a copy.

**Comment by wuardyn** [comment]
great, thanks for your help
