### ISSUE TITLE
the feature branches still alive ?

### ISSUE THREAD

**Issue by geminiyellow** [NathanWalker/angular-seed-advanced#361]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

i want to check if i can add material/angularfire to the project. then i found the feature branch.
like this https://github.com/NathanWalker/angular-seed-advanced/tree/material2 and this https://github.com/NathanWalker/angular-seed-advanced/tree/angularfire2 , but , the branches are very old and not update at all. just a dummy branches. right?

**Expected behavior**

@NathanWalker please delete the dummy branches, keep the repo clean

**Minimal reproduction of the problem with instructions**

check the repo branch

**What is the motivation / use case for changing the behavior?**

no

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` = 7.5

**Comment by NathanWalker** [comment]
Hi @geminiyellow thanks for heads up - yes those feature branches are out of date - i will schedule to clean up a number of issues (a lot not relevant for stay open) and either remove the feature branches or contact latest commit authors on those to see if they'd like mention of those integration to their own fork. Thanks.

**Comment by geminiyellow** [comment]
@NathanWalker thank you~ a great job.

**Comment by NathanWalker** [comment]
Thanks @geminiyellow 👍

**Comment by geminiyellow** [comment]
hi @NathanWalker , two years later, i notice the latest commit is 2017, this project is still working?
