### ISSUE TITLE
 Error when using ngModel: "No value accessor for form control with name: 'name'"

### ISSUE THREAD

**Issue by michaelAntony** [NathanWalker/angular-seed-advanced#366]
I used ngModel inside sample->components->tns.html and its showing the error "No value accessor for form control with name: 'name' when using ngModel". I used ngModel like
<TextField name= "room" [(ngModel)]="room" [hint]="'Enter new room' | translate" class="input" ></TextField>
What could be the possible issue?

**Comment by psmontte** [comment]
Please submit issue in the prescribed format.

**Comment by sanderbos1402** [comment]
i have the same issue, it has something to do with the nativescript forms module that is missing.
of course you don't want to reference that directly, but it seems the way this has been setup it is not provided to this component.

got it working with some changes but then the web is not working anymore (at least it seems to work but the binding does not work). Probably needs a provider for the forms module somewhere, just like the router extensions.

If I find a working solution i will let you know.

**Comment by sanderbos1402** [comment]
it will work in the components, because the module that exposes the components imports the nativescript-angular-forms module. But not in another module that is also imported by the root module.

**Comment by sanderbos1402** [comment]
in my case it was not the sample module but an other.
It turned out I forgot to load the form module.
so something different.

**Comment by NathanWalker** [comment]
Ensure you have imported the `NativeScriptFormsModule` in whichever module is declaring your component.
For example:
https://github.com/NathanWalker/angular-seed-advanced/blob/master/nativescript/src/components.module.ts#L35
