### ISSUE TITLE
Build for mobile fails on web-only modules/classes, how can I exclude them

### ISSUE THREAD

**Issue by fourctv** [NathanWalker/angular-seed-advanced#369]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[x] feature request
```

**Current behavior**
In my app I have some classes/modules that are web only, not to be shared with mobile.

I can run the app on all platforms, web, ios, android, no problem.
But I cannot build for mobile. I get errors in the `webpack --config=webpack.ios.js --progress` step, like:
```
ERROR in Cannot determine the module for class _xxx_ in  _classpath_
```

The classes are indeed included in a web-only module, which is not added to my `native.module`.

**Expected behavior**
App would be built fine, and classes not referenced on `native.module` ignored in the process.

**What is the motivation / use case for changing the behavior?**
Large apps will definitely include classes, libraries, modules not fit for mobile and there should be a way to exclude those from a mobile build.

**Please tell us about your environment:**
OS X.10.11.6
VSCode 1.9.1
TSC 2.1.6
TNS 2.5.2

* **Angular Seed Version:** `efb2fce`

* **Node:** 
Node 7.4.0
NPM 4.0.5

**Comment by fourctv** [comment]
I downloaded the latest seed today (Mar 3, 2017) to try to track my error, but build fails on the untouched seed as well.

Funny that a brand new seed fails on a different place. Right on `build.prod.tns` I get this error:
```
Running webpack for ios...
/Users/jcarneiro/Downloads/angular-seed-advanced-master/nativescript/webpack.common.js:73
    new nsWebpack.ExcludeUnusedElementsPlugin(),
    ^

TypeError: nsWebpack.ExcludeUnusedElementsPlugin is not a constructor
```

I then commented out that line in `webpack.common.js` just to see if it got further, and then I had a similar error to what I saw in my project:
```
[0] ./app.aot.ts 359 bytes {1} [built] [failed] [1 error]
   [1] ./vendor.ts 359 bytes {2} [built] [failed] [1 error]
   [2] ./app.ios.css 359 bytes {0} [built] [failed] [1 error]

ERROR in Child compilation failed:
Entry module not found: Error: Can't resolve 'nativescript-dev-webpack/tns-xml-loader' in '/Users/jcarneiro/Downloads/angular-seed-advanced-master/nativescript/app':
Error: Can't resolve 'nativescript-dev-webpack/tns-xml-loader' in '/Users/jcarneiro/Downloads/angular-seed-advanced-master/nativescript/app'

ERROR in ./app.ios.css
Module build failed: TypeError: loaderUtils.parseQuery is not a function
    at injectTemplateVariables (/Users/jcarneiro/Downloads/angular-seed-advanced-master/nativescript/tools/webpack/tns-loader.js:34:29)
    at Object.tnsLoader (/Users/jcarneiro/Downloads/angular-seed-advanced-master/nativescript/tools/webpack/tns-loader.js:73:10)
......
```

Am I the only one seeing that? Could it be version related? Webpack version is the same in both projects here and is the same as indicated in seed's `package.json`.

Or tns version. I'm running 2.5.2.

**Comment by fourctv** [comment]
Now I know the reason for the difference in results from my project and a fresh seed: `nativescript-dev-webpack` version. My project was on 0.3.2, while a fresh seed installed 0.3.5.

I then erased nativescript/node_modules and reinstalled everything to be on a par with a fresh seed, and I now get the same `TypeError: nsWebpack.ExcludeUnusedElementsPlugin is not a constructor` as the seed.

I did the same trick of commenting out line 73 in `webpack.common.js`, and the error I see in my project now is:
```


> vakeano@0.1.0 ns-bundle /MovieGenome/Vakeano/nativescript
> ns-bundle

Running webpack for ios...
/MovieGenome/Vakeano/nativescript/node_modules/typescript/lib/typescript.js:14552
            var sourceFile = new SourceFileConstructor(261 /* SourceFile */, /*pos*/ 0, /* end */ sourceText.length);
                                                                                                            ^

TypeError: Cannot read property 'length' of undefined
```

Any suggestions?

**Comment by cmermingas** [comment]
I am having the same problem with a fresh, untouched clone from efb2fce:

When I run `npm run build.ios`, I get:

`TypeError: nsWebpack.ExcludeUnusedElementsPlugin is not a constructor`

I have:

- tns v2.5.2
- node v7.5.0
- tsc v2.2.1
- npm v4.1.2
- OSX 10.12.3

EDIT: Your changes on #372 fixed this for me.

**Comment by fourctv** [comment]
I was able to track down why build for mobile failed on my project.

Of course those changes I posted on #372 are needed, otw not even a fresh seed builds.

But in my case, the additional cause was that I have my own "app.ts" file, so I leave seed's file untouched. 

Previously I had `nativescript\src\package.json` modified so the main app pointed to my component. That works fine for `start` mobile, but is not enough anymore for webpack.

You have to also change `nativescript\package.json` to point to your main app component.

That did the trick and I can now build for mobile fine.

@NathanWalker not sure if that should be on the Read.me or on a wiki page.
