### ISSUE TITLE
Webpack loaderUtils.parseQuery() deprecated, need to replace it with loadUtils.getOptions()

### ISSUE THREAD

**Issue by fourctv** [NathanWalker/angular-seed-advanced#371]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Trying to build for mobile (`build.ios` or `build.android` fails because `loaderUtils.parseQuery()` has been deprecated in `webpack/loader-utils`, and one must use `loadUtils.getOptions()` instead. 

**Expected behavior**
Mobile build does not fail!

**Minimal reproduction of the problem with instructions**
Download a new seed clone and try:
```
npm install
npm run build.android
```

and you'll see that build fails.

**How I fixed that on my end**
There is a quick fix for that. Simply replace line 34 in `nativescript/tools/webpack/tns-loader.js` by:
```
  const query = loaderUtils.getOptions(loaderContext);
```

Doing that clears that build error.

**Please tell us about your environment:**
OS X.10.11.6
VSCode 1.9.1
TSC 2.1.6
TNS 2.5.2

* **Angular Seed Version:** `efb2fce`

* **Node:**
Node 7.4.0
NPM 4.0.5

**Comment by NathanWalker** [comment]
Thank you @fourctv !! Just pushed up the fix.
