### ISSUE TITLE
Can i use local storage of phone while using angular-seed-advance?

### ISSUE THREAD

**Issue by ghost** [NathanWalker/angular-seed-advanced#373]
In my app-program, i am using local-storage to store data temporarily, is it possible to do simply like using in nativescript?

**Comment by NathanWalker** [comment]
@SumanSingh4 absolutely. You would want to create something like `ns-local-storage.service.ts` as `NSLocalStorageService` perhaps, which would provide the same api as web's `localStorage` but under the hood you would `import * as appSettings from 'application-settings';` which taps into native iOS and Android key/value store. See here: https://docs.nativescript.org/cookbook/application-settings
You would then provide your `NSLocalStorageService` during runtime of your mobile app's bootstrap to ensure it taps into the native key/value store appropriately.
