### ISSUE TITLE
new packages(angular2/nativescript) are not installaing 

### ISSUE THREAD

**Issue by ghost** [NathanWalker/angular-seed-advanced#374]
can't install new packages which are needed i my project. While writing in package.json new dependencies, it just escape the new packages. how i can install that?

**Comment by harrisonccole** [comment]
@SumanSingh4 Which package.json are you editing?

**Comment by NathanWalker** [comment]
@SumanSingh4 ensure you only install NativeScript specific packages in the `nativescript` folder and web specific packages in the root of the project.
