### ISSUE TITLE
Docker prod mode

### ISSUE THREAD

**Issue by StessyMougeot** [NathanWalker/angular-seed-advanced#377]
**I'm submitting a
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)

I want to set up docker container to put my app in prod mod
and got error on : 
gulp build.prod --color --env-config prod --build-type prod

with this message:
Message:
EACCES: permission denied, mkdir '/home/app/angular-seed/dist/prod'
Details:
errno: -13
code: EACCES
syscall: mkdir
path: /home/app/angular-seed/dist/prod

**Minimal reproduction of the problem with instructions**

There is also some problems when I'm just trying to clone and build the app from scratch

**Please tell us about your environment:**

I'm using an OVH VPS with debian8

 **Angular Seed Version:** I used a version from like 18-19 December 2016

* **Node:** `node --version` = 6.6

**Comment by Kaffiend** [comment]
same with sudo? you might need to configure docker permissions to run without sudo, checkout the [docker](https://docs.docker.com/engine/installation/linux/linux-postinstall/) post install section.

**Comment by StessyMougeot** [comment]
Yep, docker is well configured. I ran another docker compose with nginx, postegres, and an api.

**Comment by NathanWalker** [comment]
@Dragonnblack I pushed up 1 small fix to syntax which might have been affecting docker builds - verified latest master has proper dockerized setup.

Unfortunately I can't provide help for Linux development environment's (just too much for me given other priorities) however the community could chime in on anything specific there. The docker setup is verifiable on Mac dev workstation at least. 

You mention of using a version of the seed from `I used a version from like 18-19 December 2016` which is old - please try with latest master.

**Comment by ArnaudPel** [comment]
Reproducing this issue with today's angular-seed (not advanced) master (#e5aacea), on Ubuntu 16.04

Dirty fix I used to circumvent it for now (disclaimer: I have no clue about what security breach this could create ! this question is not a priority for me ATM):
Appending the following line to **.docker/angular-seed.production.dockerfile**

```
USER root
```

My two cents on what this is doing:
This leaves the first build step (_1._) with a root user in the container. Which means the command run in the second step (_2._)  is run as root: npm run build.prod

_1. docker-compose -f docker-compose.production.yml build_
_2. docker-compose -f docker-compose.production.yml up angular-seed_
