### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by igneg** [NathanWalker/angular-seed-advanced#379]
<img width="805" alt="screen shot 2017-03-14 at 2 33 54 pm" src="https://cloud.githubusercontent.com/assets/3995258/23918239/92120ba0-08c8-11e7-93f0-3dbb60181ccd.png">

I get the following error message as soon as BrowserSync reloads the page after I make some changes in any file under `src`:

`Uncaught ReferenceError: exports is not defined`
`Failed to load resource: the server responded with a status of 404 (Not Found)`
 `(SystemJS) XHR error (404 Not Found) loading http://localhost:5555/main.web`

Does anybody have an idea on how to solve this? 

Thank you!

**Comment by NathanWalker** [comment]
This is likely related to your APP_BASE. See this: https://github.com/NathanWalker/angular-seed-advanced/issues/275
