### ISSUE TITLE
Testing Workflow

### ISSUE THREAD

**Issue by aaweb** [NathanWalker/angular-seed-advanced#38]
Hey Nathan

Just a quick question about what the intended workflow is for testing or test-driven development. Currently, I'm using the debug commands:

```
# Debug - In two different shell windows
npm run build.test.watch      # 1st window
npm run karma.start           # 2nd window
```

However, even when using `iit` or `ddescribe` to only run certain tests, the delay from save to the tests actually passing takes at least 30 seconds.

Is this workflow only meant for debugging or what is the intended usage here? Glad to hear your insight.

Andy

**Comment by NathanWalker** [comment]
Hi @aaweb, that is the current TDD workflow at the moment.
If you'd like to see improvements to that or have any suggestions, you might post an issue on the parent [angular2-seed here](https://github.com/mgechev/angular2-seed/issues). All build tooling at the moment derives directly from that parent seed for consistency.

This discussion brings up some related issues: https://github.com/mgechev/angular2-seed/issues/645

Once we can move to rxjs beta 3/4 and above, things should improve with regards to that.
Thanks for the question and feel free to post additional thoughts (just going to close this issue for now).
