### ISSUE TITLE
component sharing Web/NativeScript with specific NativeScript

### ISSUE THREAD

**Issue by stravassac** [NathanWalker/angular-seed-advanced#380]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```
When one want to share code between Web and NativeScript, what is the best practice for components code with specific NativeScript import and use? One component for Web, another for Native or is there any other method avoiding duplicate?Below is an example which can run on NativeScript but not Web (module not found)
Thanks for your help

```typescript
import { OnInit, Component, ViewChild, ChangeDetectorRef } from '@angular/core';
import { ActivatedRoute, Params, Router }   from '@angular/router';

//specific nativescript
import { Observable } from "data/observable";
import { Page } from "ui/page";
import { RadSideDrawer } from "nativescript-telerik-ui/sidedrawer";
import sideDrawerModule = require('nativescript-telerik-ui/sidedrawer');
import { RadSideDrawerComponent, SideDrawerType } from "nativescript-telerik-ui/sidedrawer/angular";



@Component({
  moduleId: module.id,
  selector: 'my-navbar',
  templateUrl: 'navbar.component.html',
  styleUrls: ['navbar.component.css']
  
})
export class NavbarComponent extends Observable implements OnInit{

  
  private drawer: SideDrawerType;
  @ViewChild(RadSideDrawerComponent) public drawerComponent: RadSideDrawerComponent;

  constructor(private router: Router, private page: Page, private _changeDetectionRef: ChangeDetectorRef){
    super();
  }
  ngOnInit():void{
    
  }

  ngAfterViewInit():void{
    
     this.drawer = this.drawerComponent.sideDrawer;
    this._changeDetectionRef.detectChanges();
  }

  public openDrawer() {
        this.drawer.showDrawer();
    }

}
```

**Comment by NathanWalker** [comment]
@stravassac the component above is best to develop in the `nativescript/src` folder only. I will often create `nativescript/src/mobile/components` folder and build out mobile specific components. What constitutes *mobile only components* vs. shared web components for me is whether or not they import NativeScript specific modules as you have above.

I will then create a custom mobile only routing module and use that instead of the shared routing module. That way, I can reuse any components from the web where applicable and mix with mobile specific components as needed. Hope that helps.

**Comment by stravassac** [comment]
Thanks for your help

**Comment by benediktdertinger** [comment]
@NathanWalker there are a few things I couldn't find in any of the given docs if I like to do specific mobile overwrites:
1. Do I define and install {N} dependencies in `root` or `nativescript` folder?
2. Do I set specific mobile overwrites by placing a folder in `nativescript/src/mobile/components/about` for the overwrite of `src/client/app/components/about` component? (and if so by just using the *.tns.* or all files?)
3. ... or do you recommend to set specific mobile features by simply adding a `about.component.tns.ts` file to the web dev folder following [this guide](https://www.nativescript.org/blog/code-sharing-between-web-and-mobile-with-angular-and-nativescript)?

I tried to add the side drawer component @stravassac suggested but none of the above routes worked for me. It would be really nice if you could provide additional details! Thanks
