### ISSUE TITLE
How to add fonts to production build?

### ISSUE THREAD

**Issue by viktorstaikov** [NathanWalker/angular-seed-advanced#383]
Hi there,

I'm trying to add FontAwesome to my web project and I've installed it from NPM.
The path is added in project.config.ts -> NPM_DEPENDENCIES as 
 ` { src: '../../node_modules/font-awesome/css/font-awesome.min.css', inject: true }`

The problem comes when building for production. The font files are not included in the build. The paths to them are 
```
/node_modules/font-awesome/fonts/fontawesome-webfont.ttf'
/node_modules/font-awesome/fonts/fontawesome-webfont.woff'
/node_modules/font-awesome/fonts/fontawesome-webfont.woff2'
```
The css file gets bundled, but they are not. I saw that there is task for handling font, but for TNS. 

Is there an easy way of achieving this or I have to copy them manually?

Thanks

**Comment by fourctv** [comment]
I have my font files, .ttf or others, installed into `/src/client/css/fonts`, and the new webpack build will also copy font files from `/src/client/fonts`.

So you may just copy your font files there, and reference them in your `.css`. No need to change project.config.ts.

For {N}, you can put your `.ttf` into `/nativescript/src/fonts`, and they will also be copied automatically from the build scripts.

No assets lying in `node_modules` are copied to prod build (except .js that are bundled).

**Comment by viktorstaikov** [comment]
What Webpack build?
I'm using __npm run build.prod__ for building.

Is there a way to explicitly say which assets from node_modules to be bundled?

**Comment by fourctv** [comment]
Viktor, sorry about webpack, that is only used to build for mobile. `build.prod` still uses systemjs to create bundles.

The only way I see that you can copy assets from node_modules to a prod build is by creating your own copy of `build.assets.prod.ts` in `/tools/tasks/project`. Then modify it to add a step to copy your extra stuff.

Remember that a prod build does not include a `node_modules` folder, so you'd have to either create one or copy your assets somewhere else and ensure those assets are properly referenced in the prod's `index.html`.

I still believe the best approach is to copy your font files to the `assets`, `fonts` or `css` folders. A `node_modules` folder really does not belong in a prod build.

**Comment by amirtoole** [comment]
Hey @viktorstaikov,
I have this working on a branch on my repo:
https://github.com/hellofornow/angular-seed-advanced/tree/fontawesome

I didn't need to modify any build tasks, but instead leveraged the existing scss infrastructure.
Steps I took:

1. Added angular2-fontawesome to package.json
2. Reference angular2-fontawesome in tools/config/project.config.ts
3. Add Angular2FontawesomeModule in web.module.ts
4. Download font-awesome and place the scss files in src/client/css/font-awesome/* and the fonts in src/client/assets/fonts/*
5. Update the path of the fonts in src/client/css/font-awesome/_variables.scss to 
```$fa-font-path:        "../../assets/fonts" !default;```
6. In src/client/css/main.scss I added ```@import 'font-awesome/font-awesome';```

That's it. All the fontawesome css is now bundled into main.css. 
You can check out home.component.html to see it in action. Works for dev and production.

Cheers

**Comment by NathanWalker** [comment]
Excellent @hellofornow thank you, I have added your instructions to the Wiki here:
https://github.com/NathanWalker/angular-seed-advanced/wiki/How-to-integrate-font-awesome-for-dev-and-production
👍
