### ISSUE TITLE
Compile error on ng2-jasmine

### ISSUE THREAD

**Issue by fourctv** [NathanWalker/angular-seed-advanced#385]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting

```

**Current behavior**
merge to latest seed and you get the following compile error:
```
src/client/app/shared/test/shorthand/ng2-jasmine.ts(20,19): error TS2315: Type 'Matchers' is not generic.
```

**Expected behavior**
error free compile

**Minimal reproduction of the problem with instructions**
grab a fresh clone and run `npm start`

* **Angular Seed Version:** ` 82efca9  `

**Comment by NathanWalker** [comment]
@fourctv I am not seeing this -- is it possible you are using an IDE configured with a different TypeScript version and not the one installed with the seed?

**Comment by fourctv** [comment]
@NathanWalker here are my versions:

using VS Code IDE, with typescript v2.2.1
@types/jasmine version: 2.5.43

I also see the error indicated in VSCode, when I open ng2-jasmine.ts.

also:
node: v7.4.0
npm: 4.0.5

OSX v10.11.6

**Comment by NathanWalker** [comment]
here's my stack:
```
NathanMac:angular-seed-advanced nathan$ node --version
v6.9.1
NathanMac:angular-seed-advanced nathan$ npm --version
3.10.9
NathanMac:angular-seed-advanced nathan$ tsc --version
Version 2.1.5
```

**Comment by NathanWalker** [comment]
However VS Code settings from the seed should be setting to locally installed ts 2.2.1 version from:
`"typescript.tsdk": "node_modules/typescript/lib"`

**Comment by fourctv** [comment]
yep, that's what I have in `.vsCode/settings.json`.

Looks like the difference is `tsc` version. Mine 2.2.1 (the latest), yours 2.1.5.

**Comment by NathanWalker** [comment]
I'm going to close this as I don't see it as an issue - shouldn't cause you problem at least - we'll see if others chime in.

**Comment by caolgood** [comment]
I was seeing the same error,  updating to the latest @types/jasmine fixed it for me. As the error message said, there was a definition for `Matchers` instead of the expected `Matchers<T>`
