### ISSUE TITLE
How to run dist/prod generated files on remote server

### ISSUE THREAD

**Issue by vladyhon** [NathanWalker/angular-seed-advanced#398]
Thank you for your really cool framework, which did my life easier.
I generated files by npm run build.prod
But i don't know how to run this file on my remote server on ubuntu
Sorry for that request, i know that really easy for you.

Thank you)

**Comment by oravecz** [comment]
Copy the `dist/prod` files to your remote web server

**Comment by NathanWalker** [comment]
Thanks @vhontar great to hear :)
@oravecz is correct, just upload output of dist/prod to server 👍

**Comment by dgt009** [comment]
after uploading the `dist/prod`
which file or command should I be running?
`node main.web.js` ?

**Comment by NathanWalker** [comment]
No command to run, it's just static files at that point so any standard web server will just serve those.
