### ISSUE TITLE
Electron / Nwjs support

### ISSUE THREAD

**Issue by realsaraf** [NathanWalker/angular-seed-advanced#4]
Hi @NathanWalker,

This a wonderful effort. I really like the organization of the project. Any ideas when you are planning for the electron support? some hints on how it can be done would be appreciated. At least a gulp task to launch the app as it is on electron would be helpful.

**Comment by NathanWalker** [comment]
@realsaraf Thank you for the kind words.
Here's a couple excellent resources on Electron + ng2:

https://github.com/angular/angular-electron

https://www.xplatform.rocks/2016/02/14/angular2-and-electron-the-definitive-guide/

https://auth0.com/blog/2015/12/15/create-a-desktop-app-with-angular-2-and-electron/

Good tips: http://blog.axosoft.com/2016/03/04/electron-things-to-know/

My hope is to bring that support within a month from now, however I'm always open to PR's. ;)
If you plan to contribute in anyway, just bear in mind the project organization and try to stay true to that.

There's 2 paths to take (not sure yet which one will make most sense and work out):
1. Keep everything together in `src` folder. Electron bootstrap and all. Concern here is the same as NativeScript. Doing so requires web builds to also depend on the electron libraries for the TS build to succeed unless you can come up with a clever way to exclude certain `frameworks` on TS build of web and then include them in the electron build.
2. Create an `electron` folder as I did with `nativescript`. Then add a `prepare` and `start` task similar to here: https://github.com/NathanWalker/angular2-seed-advanced/blob/master/nativescript/package.json#L11-L12  ... This is what brings the shared codebase into it's respective build. Then in the `electron` folder you only create the bare minimum on top of the shared codebase to make it work. You would still create `desktop.framework` in the main `src` directory which would contain any `shared` desktop setup similar to what I did with `nativescript.framework` here: https://github.com/NathanWalker/angular2-seed-advanced/tree/master/src/frameworks/nativescript.framework

**Comment by realsaraf** [comment]
Hi @NathanWalker ,

Thank you for your prompt response and the tips. I will try to follow what you said and if i come up with something good, i will try to submit a PR.

**Comment by NathanWalker** [comment]
As far as NW.js, there are these comparisons:
https://www.xplatform.rocks/2016/02/09/nw-js-vs-electron/

http://tangiblejs.com/posts/nw-js-electron-compared

**Comment by realsaraf** [comment]
Thanks

**Comment by NathanWalker** [comment]
Experimentation is being done here:
https://github.com/NathanWalker/angular2-seed-advanced/tree/4-electron-support

Blocked by `Router` trouble at moment.

Run by the following:

```
npm run start.desktop --desktop
```

**Comment by NathanWalker** [comment]
This is available on master now.
https://github.com/NathanWalker/angular2-seed-advanced#electron-app

![Desktop](https://d2wp4shknjcfjl.cloudfront.net/api/file/1O4FRGsSHS8g0Lz3EKNy)
