### ISSUE TITLE
Support for Cloud Foundry 

### ISSUE THREAD

**Issue by dgt009** [NathanWalker/angular-seed-advanced#402]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
In addition to this project, I added `.cfignore` and `manifest.yml` file to the project, which is used to push the project on Cloud Foundry Instance. But it is unable to start the project. and shows below error and won't start the project. I am pretty much sure that because it is unable to take the port number by itself, it shows the error. 
```
       ├─┬ ts-node@2.1.2
       │ ├── arrify@1.0.1
       │ ├── diff@3.2.0
       │ ├── make-error@1.2.3
       │ ├── pinkie@2.0.4
       │ ├─┬ source-map-support@0.4.14
       │ │ └── source-map@0.5.6
       │ ├─┬ tsconfig@6.0.0
       │ │ ├── strip-bom@3.0.0
       │ │ └── strip-json-comments@2.0.1
       │ ├── xtend@4.0.1
       ├── typescript@2.2.2
-----> Caching build
       Clearing previous node cache
       Saving 3 cacheDirectories (default):
       - .npm
       - .cache/yarn (nothing to cache)
       - bower_components (nothing to cache)
-----> Build succeeded!
-----> Uploading droplet (25M)

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
```

**Expected behavior**
Actually, it should automatically take the port number and start running. or maybe if anyone with cloud foundry experience would be able to upgrade the project with cloud foundry support also.

**Minimal reproduction of the problem with instructions**
.cfignore file
```
# compiled output
dist
tmp

# dependencies
node_modules
bower_components

#mobileapp
nativescript

# IDEs and editors
.idea
.vscode
.project
.classpath
*.launch
.settings/

# misc
.sass-cache
connect.lock
coverage/*
libpeerconnection.log
npm-debug.log
testem.log
typings

# e2e
e2e/*.js
e2e/*.map

#System Files
.DS_Store
Thumbs.db

```
manifest.yml
```
---
applications:
- name: project-name
  memory: 128M
  buildpack: https://github.com/cloudfoundry/nodejs-buildpack.git
  #command:  DEBUG=express:* node app.js
  command:   npm start
#services:

env:
    node_env: cloud
```

**What is the motivation / use case for changing the behavior?**
It will  have additional feature with cloud foundry support.

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =

**Comment by NathanWalker** [comment]
@dgt009 Change your start command to launch on a different port perhaps:
`npm start -- --port 8080`  <-- can be any port number

Cloud Foundry support will unfortunately not happen on master here however there may be forks you could look for.

**Comment by dgt009** [comment]
For those who are looking for this option can check my [stackoverflow](http://stackoverflow.com/a/43316141/2147560) answer.
