### ISSUE TITLE
This project is so big, How can I intergrate with my PHP API ? 

### ISSUE THREAD

**Issue by phuongphally** [NathanWalker/angular-seed-advanced#403]
I am doing music app with java android and Laravel 5.1 API It working well for android . 

But My goal is write one can apply all platforms .

How easy to start with this project ? 

Thanks for reply .

**Comment by NathanWalker** [comment]
Hi @phuongphally I can appreciate your request :)  
It's a large question and I would refer you to Angular's docs (https://angular.io/) as well as NativeScript's docs (http://docs.nativescript.org/angular/start/introduction.html) as a good start. A simpler project to start with might be @jlooper 's starter (https://github.com/jlooper/angular-starter) which is same as this but greatly simplified and definitely easier to start with.

Backend integrations come in all flavors so I can't provide any assistance there particularly however you might search around the open/closed issues here as well as look at forks which may integrate with PHP backends.

**Comment by phuongphally** [comment]
Hi @NathanWalker Thanks for your quick response!

So I need to replace android by NativeScript ?
