### ISSUE TITLE
Minor improvement to compile.ahead.prod.ts

### ISSUE THREAD

**Issue by fourctv** [NathanWalker/angular-seed-advanced#404]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
If your Bootstrap module is different from seed's default `main.web.ts`, and even if you change it in your `project.config`, `build.prod.aot `will still use the seed's default.

That is because `compile.ahead.prod.ts` uses a string constant to refer to the Bootstrap module, instead of using the Configuration value.

Line # 32 in `compile.ahead.prod.ts` reads:
```
    parsed.files.push(join(Config.BOOTSTRAP_DIR, 'main.web.ts'));
```

It should be replaced by:
```
    parsed.files.push(join(Config.BOOTSTRAP_DIR, Config.BOOTSTRAP_PROD_MODULE+'.ts'));
```

That allows one to configure a different bootstrap module in `project.config`.

* **Angular Seed Version:** `8c892c4 `

**Comment by NathanWalker** [comment]
Great suggestion @fourctv added it on master now thank you 👍
