### ISSUE TITLE
yarn install is slow and gets stuck after a while

### ISSUE THREAD

**Issue by ishandutta2007** [NathanWalker/angular-seed-advanced#407]
This is where its stuck for hours.
`MacBook-Pro:angular-seed-advanced ishandutta2007$ yarn install
`
> yarn install v0.20.3
> [1/4] 🔍  Resolving packages...
> warning electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
> warning gulp-atom-electron > github-releases > minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> warning gulp-atom-electron > github-releases > grunt > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> warning gulp-atom-electron > github-releases > request > node-uuid@1.4.8: Use uuid module instead
> warning electron-prebuilt > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0: 
> ⠂ object-keys@~0.4.0^C
>

**Comment by NathanWalker** [comment]
I won't be able to support yarn issues here however in meantime you might just use `npm i` instead.
