### ISSUE TITLE
Injecting external non npm js files

### ISSUE THREAD

**Issue by mrelics** [NathanWalker/angular-seed-advanced#408]
I want to inject external js files into the index.html file.

I tried putting it under APP_ASSETS(which only inject css file and ignores .js files)

NPM_Dependecies I think are only for node_modules.

I think we should have APP_ASSETS_CSS and APP_ASSETS_JS so that anybody want to inject anything will not get confused.

Kindly solve my issue ?
Tried to inject js files but in index.html it is not getting injected.

My files are present in assets/libs/ folder.

Thanks
Manish Pandit

**Comment by thomascayne** [comment]
I'm going bald facing this same issue for weeks now. #382. I tried everything, including renaming the non-npm *.js to *.ts, but that produced a lot of syntax errors in the console. I cannot rename the hundreds of javascript files I have and watch the errors float by not knowing if the errors are legit.

The build ignores all *.js in src. Uncommenting  `'src/**/*.js',` in [seed.config.ts](https://github.com/NathanWalker/angular-seed-advanced/blob/master/tools/config/seed.config.ts#L397) changed nothing.

**Comment by thomascayne** [comment]
By the way, all CSS files placed in the assets folder will be copied over during build. I import them by placing `@import '<path-to-css>/<css-file-name'>` in [main.scss](https://github.com/NathanWalker/angular-seed-advanced/blob/master/src/client/css/main.scss). That bundles into one main.css file and doesn't produce a separate `<link ...>` in index.html.

**Comment by mrelics** [comment]
Thanks a ton,  It really worked.

**Comment by thomascayne** [comment]
@mrelics Try this instead of changing all `*.js` to `*.ts`. Avoid all unnecessary syntax errors. What I ended up doing is the following:

First: Create `copy.js.files.ts` in `tools/tasks/seed/` with:

```
import * as gulp from 'gulp';
import Config from '../../config';

/**
 * Executes right after the build task, copying all JavaScript files over to the `dest` directory.
 */
export = () => {
 return gulp.src(Config.APP_SRC + "/**/*.js")
    .pipe(gulp.dest(Config.APP_DEST));
}

```

Then in `tools/config/seed.task.json` insert as follows:

```
  "build.dev": [
    "initialize",
    "clean.once",
    "copy.js.files",    // <-- copy files to dest directory
    "build.assets.dev",
    "build.html_css",
    "build.js.dev",
    "build.index.dev",
    "sw.manifest.static"
  ],

```

**Comment by rybaczewa** [comment]
@vanchisel With extra task, build now copies js files. I still have problem with `Cannot find module` (you mentioned it here https://github.com/NathanWalker/angular-seed-advanced/issues/382#issuecomment-293984766). Did extra task fix that for you?
