### ISSUE TITLE
Not recognizing types

### ISSUE THREAD

**Issue by ishandutta2007** [NathanWalker/angular-seed-advanced#410]
I have added the following types

package.json
```
    "@types/gapi": "0.0.31",
    "@types/gapi.auth2": "0.0.35",
    "@types/gapi.youtube": "^3.0.31",

```
updated types in tsconfig.json
```
    "types": [
      "node",
      "jasmine",
      "protractor",
      "systemjs",
      "gapi",
      "gapi.youtube",
      "gapi.auth2",
      "youtube"
    ]
```
Visual studo code recognises them, but when I run ```npm run start.android``` I get following errors

```
app/core/effects/player-search.effects.ts(43,21): error TS2304: Cannot find name 'GoogleApiYouTubeVideoResource'.
app/core/services/authorization.service.ts(20,24): error TS2503: Cannot find namespace 'gapi'.
```

Let me know if I am missing something, I am trying to setup by comparing with other types, I dont see anything updated for other types in ```tools/config/seed-advanced.config.ts```

**Comment by NathanWalker** [comment]
Hi @ishandutta2007 good question, you will need to also install those types in the `nativescript` directory, for example:
```
cd nativescript
npm i @types/gapi --save-dev
// etc.
```
Then modify the `nativescript/tsconfig.json` as well to contain those extra types. 👍

**Comment by ishandutta2007** [comment]
ok got it, but why is the directory structure like this ? Why two package.json , two tsconfig.json ?
