### ISSUE TITLE
npm test

### ISSUE THREAD

**Issue by dina1610** [NathanWalker/angular-seed-advanced#411]
Hi

While run npm test its makes an error

src\client\app\shared\core\directives\platform.directive.spec.ts(11,28): e
rror TS2307: Cannot find module '../../core/testing/index'.
src\client\app\shared\core\services\log.service.spec.ts(5,19): error TS230
7: Cannot find module '../../test/index'.
src\client\app\shared\core\utils\config.spec.ts(5,19): error TS2307: Canno
t find module '../../test/index'.
src\client\app\shared\core\utils\view-broker.spec.ts(2,19): error TS2307:
Cannot find module '../../test/index'.
src\client\app\shared\electron\utils\desktop-config.spec.ts(1,19): error T
S2307: Cannot find module '../../test/index'.

NPM test will also get failed.

Please help me out on this..

**Comment by NathanWalker** [comment]
This is not on `master` - did you perhaps pull in upstream changes into your project and are now seeing that? If so you may need to reconcile your changes against the latest.
