### ISSUE TITLE
Nativescript AoT - still a problem with ./native.module.ngfactory

### ISSUE THREAD

**Issue by Dutchboy** [NathanWalker/angular-seed-advanced#416]
I'm submitting a ...
[*] bug report

**Current behavior**
With a clean clone, on both Win and MacOS (and of course npm install)
npm run build.android
npm run build.ios
cause a crash... `./native.module.ngfactory not found`

```
ERROR in ./app.aot.ts
Module not found: Error: Can't resolve './native.module.ngfactory' in '/Users/krenning/dev/nathan/nativescript/app'
 @ ./app.aot.ts 4:32-68
child process exited with code 2
```

(with of course, a lot more ugly error messages after this first one :-) )

All env is up-to-date :-) 

Oh, btw, "tns livesync" is deprecated - as if that's news...

Thank you so much for ALL your efforts! Nathan, and Deviantone and all the others... Wwowww....

Meanwhile, I've gotten myself up to speed with Git, so I hope to be of some help with this project in the near future...

**Comment by NathanWalker** [comment]
Thanks @Dutchboy ! you can track this issue here:
https://github.com/NathanWalker/angular-seed-advanced/issues/406
