### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing t he function or lambda with a reference to an exported function, resolving symbol Injectable

### ISSUE THREAD

**Issue by vladyhon** [NathanWalker/angular-seed-advanced#417]
I run npm run build.android
```
ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing 
the function or lambda with a reference to an exported function, resolving symbol Injectable in /home/vlad/hontar/angular2-projects/geo/billion/client/
node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /home/vlad/hontar/angular2-projects/geo/billion/client/node_modules/@angular/core/core.d.t
s, resolving symbol ɵf in /home/vlad/hontar/angular2-projects/geo/billion/client/node_modules/@angular/core/core.d.ts                             
```
**Expected behavior**
success

**Minimal reproduction of the problem with instructions**
i merged latest upstream/merge to project, then npm run build.android

**What is the motivation / use case for changing the behavior?**
Make the world better

**Please tell us about your environment:**
node v6.10.2                                                                                                                                   
npm  v3.10.10  
Linux 4.4.0-43-generic

* **Angular Seed Version:** `f0e3bb4`

* **Node:** `node --version` = 6.10.2

**Comment by NathanWalker** [comment]
https://github.com/NathanWalker/angular-seed-advanced/issues/406
