### ISSUE TITLE
AOT build trying to import from @types instead of actual module

### ISSUE THREAD

**Issue by llwt** [NathanWalker/angular-seed-advanced#421]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

When trying to add a service from the [auth0-js](https://github.com/auth0/auth0.js) package to the DI container the build attempts to load the `index.js` file from the `node_modules/@types/auth0-js/index.js` directory instead of `node_modules/auth0-js/index.js`.

    [21:50:57] 'build.bundles.app.aot' errored after 784 ms
    [21:50:57] Error on fetch for @types/auth0-js/index.js at file:///Users/llwt/src/testing/angular-seed-advanced/node_modules/@types/auth0-js/index.js
    	Loading dist/tmp/web.module.ngfactory.js
    	Loading dist/tmp/main.web.prod.js
    	Error: ENOENT: no such file or directory, open '/Users/llwt/src/testing/angular-seed-advanced/node_modules/@types/auth0-js/index.js'
        at Error (native)
**Expected behavior**

It should load it from the actual node_module. 

**Minimal reproduction of the problem with instructions**

I've reproduced the issue in a fork which can be found [here](https://github.com/llwt/angular-seed-advanced/commit/c84612bf259f01e64c727c4133fd25da21efaaef).

The package is being imported like so:

    import { WebAuth } from 'auth0-js';
    // ...
    export function authHttp() {
      return new WebAuth({
        domain: 'foo',
        clientID: 'bar',
      });
    }
    // ...
    @NgModule({
    //...
      providers: [
        { provide: WebAuth, useFactory: (authHttp) },
        // ...

**What is the motivation / use case for changing the behavior?**

I feel like I must be missing something basic here but I can't figure out what's causing the issue. Part of me thinks this may be specific to the `auth0-js` module due to other packages I've added not having any problems but nothing stands out as different when looking at that package.

Is there a bug somewhere here or am I just missing some additional required configuration?

**Please tell us about your environment:**

N/A

* **Angular Seed Version:** `f0e3bb4`

* **Node:** `node --version` = v6.10.3

**Comment by NathanWalker** [comment]
Hi @llwt you might try uninstalling these:
https://github.com/llwt/angular-seed-advanced/blob/master/package.json#L75
...then just require it (I know it would not give you types but give it a shot to see if it helps):
`const auth0js = require('auth0-js');`

**Comment by llwt** [comment]
Hmm, swapping it out to that ends up with a different error:

```
[10:23:45] 'build.bundles.app.aot' errored after 2.04 s
[10:23:45] Error on fetch for auth0-js/src/authentication.js at file:///Users/m33684/src/llwt/angular-seed-advanced/node_modules/auth0-js/src/authentication.js
	Loading auth0-js/src/index.js
	Loading dist/tmp/web.module.ngfactory.js
	Loading dist/tmp/main.web.prod.js
	Error: ENOENT: no such file or directory, open '/Users/m33684/src/llwt/angular-seed-advanced/node_modules/auth0-js/src/authentication.js'
    at Error (native)
```

This makes me think I'm missing something about how AOT does package resolution. Guess I need to do a bit of research to fill the gap in my knowledge...

**Comment by llwt** [comment]
So this seems to be an issue with the type definitions for `auth0-js` ([ref](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11430)) rather than with the build. Sorry to burn time here, was just pulling my hair out on this forever by looking in the wrong places.
