### ISSUE TITLE
Toast message shared with web and native

### ISSUE THREAD

**Issue by TheMagnificent11** [NathanWalker/angular-seed-advanced#424]
This is not an issue but more a question.

I have "toast service" in a module that I added inside `src/client/app/shared`.

I can add I can add a plugin like **nativescript-toast** to `nativescript` directory, but this cannot be accessed in `src/client/app/shared` (at least I don't know how to write appropriate Typescript import statement).

Do I have to duplicate my "toast service" somewhere like `nativescript/app/shared` (web version) and `src/client/app/shared` (native version)?

**Comment by NathanWalker** [comment]
Hi @TheMagnificent11 a great practice for this sort of thing is to create an Angular service which would provide a web implementation using something like for example: https://github.com/akserg/ng2-toasty, then you would provide a NativeScript implementation in the {N} app.
Here's some pseudo code to give you an idea:
```
// this service would live in shared src 
@Injectable()
export class ToastMessageService {
  public info(options: ICommonToastOptions/* you would create an interface to help here  */) {
    this.toastyService.info(options); // web using ng2-toasty as an example
  }
  // more methods...
}
```
Then for {N} :
```
// this service would live only in `nativescript/src/mobile` directory (or other folder in {N} src)
import * as Toast from 'nativescript-toast';

@Injectable()
export class NSToastMessageService {
  public info(options: ICommonToastOptions) {
    Toast.makeText(options.msg).show();
  }
  // more methods...
}
```
Then in `nativescript/src/native.module.ts`:
```
@NgModule({
  ...
  providers: [
    ...
    // provide NativeScript implementation under the hood
    { provide: ToastMessageService, useClass: NSToastMessageService }
  ],
  ...
})
export class NativeModule { }
```

**Comment by NathanWalker** [comment]
@TheMagnificent11 if you still have questions just lemme know and I'll reopen but hopefully the above will get ya' going down the right path 👍

**Comment by satishblr** [comment]
@NathanWalker  Hi Nathan is there any examples code where i can take a look how i can implement this? 
please point me to the code. I really appreciate it
thanks
