### ISSUE TITLE
npm run start.android failed

### ISSUE THREAD

**Issue by KANekT** [NathanWalker/angular-seed-advanced#429]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
```

**Minimal reproduction of the problem with instructions**
i git clone https://github.com/NathanWalker/angular-seed-advanced
npm run start.android

[0] [09:58:27] Finished 'build.tns.watch' after 7.17 s
[1] Processing node_modules failed. TypeError: Path must be a string. Received undefined
[1] cd nativescript && tns run android --emulator exited with code 127
--> Sending SIGTERM to other processes..
[0] gulp build.tns.watch exited with code 1

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start.android" "--scripts-prepend-node-path"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-seed-advanced@0.0.0 start.android: `npm run nativescript-install && gulp build.tns && concurrently --kill-others "gulp build.tns.watch" "cd nativescript && tns run android --emulator"`
npm ERR! Exit status 1

**Comment by amirtoole** [comment]
I was getting a similar problem earlier as well.

Can you try cleaning (npm run clean) and then running start.android afterwards.

**Comment by KANekT** [comment]
npm run clean - I have error:
https://pastebin.com/Jh824biC
and then running start.android
https://pastebin.com/zj8KiwmA

**Comment by NathanWalker** [comment]
This might be Windows related - I'm a Mac user however perhaps someone in community could help here.

**Comment by KANekT** [comment]
in mac os for android:

Starting 'build.js.tns'...
[1] The ANDROID_HOME environment variable is not set or it points to a non-existent directory. You will not be able to perform any build-related operations for Android.
[1] cd nativescript && tns run android --emulator exited with code 127
--> Sending SIGTERM to other processes..
[0] gulp build.tns.watch exited with code null

**Comment by KANekT** [comment]
for start iOS:
[0] [09:48:58] Starting 'build.js.tns'...
[1] Version strings are not in the same format

**Comment by KANekT** [comment]
Can be there is an instruction how to set up the emulator?

**Comment by amirtoole** [comment]
Try:
npm install -g nativescript 
tns doctor
Follow the steps and say yes to every question.

If you're on windows then iOS will not work.
Alternatively if tns doctor doesn't work you can install the emulator for android by setting up android studio: https://developer.android.com/studio/index.html

**Comment by NathanWalker** [comment]
Thank you @hellofornow that is correct.
@KANekT I don't want to duplicate NativeScript setup instructions on this repo mainly because they could change over time, please refer to https://docs.nativescript.org/start/quick-setup
They have a Windows installer now - perhaps give that a shot?

**Comment by KANekT** [comment]
@NathanWalker Thx for https://docs.nativescript.org/start/quick-setup

i set: https://stackoverflow.com/questions/23042638/how-do-i-set-android-sdk-home-environment-variable

and in C:\Android\android-sdk\tools run android & install sdk 25

check "tns doctor"

https://github.com/NativeScript/NativeScript/issues/3825


but i now have error:

```
[13:17:40] Starting 'build.js.tns'...
components.module.ts(16,30): error TS2307: Cannot find module './app/components/app.component'.
components.module.ts(17,32): error TS2307: Cannot find module './app/components/about/about.component'.
components.module.ts(18,31): error TS2307: Cannot find module './app/components/home/home.component'.
components.module.ts(19,24): error TS2307: Cannot find module './app/components/app.routes'.
components.module.ts(22,28): error TS2307: Cannot find module './app/modules/core/core.module'.
components.module.ts(23,33): error TS2307: Cannot find module './app/modules/analytics/analytics.module'.
components.module.ts(24,60): error TS2307: Cannot find module './app/modules/i18n/multilingual.module'.
components.module.ts(25,30): error TS2307: Cannot find module './app/modules/sample/sample.module'.
components.module.ts(26,57): error TS2307: Cannot find module './app/modules/core/index'.
```

**Comment by guilhebl** [comment]
Try cleaning the nativescript/platforms folder and run the build again

**Comment by offroadkev** [comment]
I'm having a similar issue.  Fresh download of angular-seed-advanced.  No mods.  `npm install` + `npm start` was fine for web app, but when I try `npm run start.android` I get the following fail...

`" Creating file: /Users/deadpool/hood/playground/ng-seed-advanced/nativescript/app/vendor-platform.android.ts
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);"`

Any thoughts, direction, etc?  I'm happy to do whatever I can to help resolve this.

I'm running node v6.9.1 and npm v3.10.9

[Update/Edit] I want to note that I've also run npm run clean to clean my project and I've reinstalled packages via npm install a few times.

**Comment by SanthoshMR** [comment]
To the problem, @KANekT is facing, it is related to a symlink not being available in Windows between the /src/client/app folder to /nativescript/src/app. Create a symlink between those 2 folders using mklink (with /J for hard link) between those 2 folders and it should work.
