### ISSUE TITLE
Question: How to get platform type ?

### ISSUE THREAD

**Issue by balaphp** [NathanWalker/angular-seed-advanced#433]
I am basically running my app for web and mobile
and i want to do some platform specific code. 
How to know the platform is web or mobile or desktop ?

**Comment by shiamalon** [comment]
From the readme...

https://github.com/NathanWalker/angular-seed-advanced/blob/master/src/client/app/modules/i18n/components/lang-switcher.component.ts#L35-L41

**Comment by NathanWalker** [comment]
Thank you @shiamalon that is correct 👍
