### ISSUE TITLE
Solution for CORS ...

### ISSUE THREAD

**Issue by balaphp** [NathanWalker/angular-seed-advanced#434]
Hi,

The rest endpoint which i am calling for app is working fine in mobile but in web application its not working because of CORS. so i created proxy handler for that so i have changed few modification please correct me if i am wrong. 

angular-seed-advanced/tools/config/seed.config.ts

```
 Change 1: 
  Before:
   PROXY_MIDDLEWARE: any[] = []

  After: 
   PROXY_MIDDLEWARE: any[] = [{
        route: '/webproxy',
        handle: function (req: any, res: any, next: any) {
          var method, r;
          method = req.method.toLowerCase().replace(/delete/,"del");
          switch (method) {
            case "get":
            case "post":
            case "del":
            case "put":
              r = request[method]({
                uri: req.headers.corsurl,
                json: req.body
              });
              break;
            default:
              return res.send("invalid method");
          }
          return req.pipe(r).pipe(res);
        }
    }];

Change 2: 
Before: 
let defaults = {
      'browser-sync': {
        middleware: [require('connect-history-api-fallback')({
          index: `${this.APP_BASE}index.html`
        }),...this.PROXY_MIDDLEWARE],

After: 
let defaults = {
      'browser-sync': {
        middleware: [...this.PROXY_MIDDLEWARE, require('connect-history-api-fallback')({
          index: `${this.APP_BASE}index.html`
        })],


```
This peace of code will do the redirection but i want to this happen at the low level api. Because there are few services which i don't enabled 'Access-Control-Allow-Origin * ' so when the cors is enabled it should redirect to webproxy and then it will redirect to corsurl to get the response.
```  
let headers = new Headers({ 
      'Content-Type': 'application/json',
      'corsurl':'http://www.rest-api.com'
    });
    headers.append('Authorization', 'Auth ' + response.token);
    let options = new RequestOptions({ headers: headers, cors: true });
    return this.http.get(url, options)
```
Otherwise i have to detect the platform and write some if condition which i don't like. 

Thanks

**Comment by NathanWalker** [comment]
Hi @balaphp you might take a look at this:
https://github.com/mgechev/angular-seed/wiki/Add-a-Proxy-to-browsersync
Seems this would be a simpler way to get around a local development cors issue.
