### ISSUE TITLE
Unable to use Debugger for Chrome

### ISSUE THREAD

**Issue by lommez** [NathanWalker/angular-seed-advanced#435]
I'm trying to debug the application using the tasks:
Launch Chrome against localhost, with sourcemaps and
Attach to Chrome, with sourcemaps

But none of them are working and when in the second task i receive that message:
"Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222"

Anyone is having the same issue?

Debugger Chrome 3.1.1
Vs Code 1.12.2
Google Chrome 58.0.3029.110 (64-bit)

Thanks

**Comment by NathanWalker** [comment]
Please reopen if still having issue with more detail.
