### ISSUE TITLE
Standardize function name in log service

### ISSUE THREAD

**Issue by dskaggs** [NathanWalker/angular-seed-advanced#45]
I'd like to propose a name change for the public method `o()` in the log service. It's the only one that is not named with a full word (like error, warn and info).

The output from the method shows up in the "Log" tab in Chrome developer tools. To keep things consistent, I'd recommend renaming the method to log().

If that's something you're interested in, I'd be happy to do a PR updating the service and the usages of it in the seed project.

**Comment by NathanWalker** [comment]
Using `log.log` would be pretty odd, so maybe we can change the name of the variable for `LogService` wherever it is injected to `logger`, so:
https://github.com/NathanWalker/angular2-seed-advanced/blob/6622727af4ae3bf5c2f988dd123bd5afce8d2d78/src/client/app/components/app/toolbar.component.ts#L14-L17

```
constructor(private log: LogService) {}

  public openLanguages(e: any): void {
    this.log.o('openLanguages');
  }
```

would become:

```
constructor(private logger: LogService) {}

  public openLanguages(e: any): void {
    this.logger.log('openLanguages');
  }
```

Which I still don't love actually. I agree it could and should be better. Let me know if you have any other suggestions?

**Comment by dskaggs** [comment]
The other thought I had was just change `log.o()` to `log.out()` (like in the comment above it). At least that gives a little more indication than a single letter.

One final thought would be to add a `log.debug()` call to replace `log.o()` completely. Of the "standard" logging levels that people think about, debug is the only one that is absent from the list of methods in the logging service. However, that may be different than what you'd intended for that method.

**Comment by NathanWalker** [comment]
Hmm I like `debug`... it will either be that or `out` (which was my first thought initially), thanks for the suggestions! I'll make a change on that soon.

**Comment by dskaggs** [comment]
I think `debug` is more descriptive. This app that we're starting will need the environment bits wired into the log service at some point so we can turn debug logging on and off on demand in production. So `debug` would make it clearer what you're enabling/disabling too I think. Of the 2 options, `debug` would be my choice.

**Comment by NathanWalker** [comment]
@dskaggs Thanks again for bringing this up. Went with `debug` as you suggested. I like it.

**Comment by dskaggs** [comment]
Thanks @NathanWalker. I'm not sure this doesn't make things a bit more confusing though. What I'd had in mind (and I realize now I didn't articulate well), was to have the LogService debug() method utilize `console.debug()` so that the debug statements would show up correctly in dev tools (like using `$log` in Angular 1.x does). Currently `LogSerivce.debug()` still outputs to the "Log" tab whereas `console.debug()` shows up on the "Debug" tab (see attached screenshot). All the other LogService methods show up on the correct dev tools section but `LogService.debug()` is still output to the "Log" panel instead.

Thoughts? Feel free to tell me to go pound sand if I'm making an issue where one really shouldn't exist :)

![log-service-output](https://cloud.githubusercontent.com/assets/432500/14566741/c884be42-02fe-11e6-8d9a-e1ca17d0c878.png)

**Comment by NathanWalker** [comment]
@dskaggs Been very busy day... n/p at all! I'll adjust that after awhile....

**Comment by NathanWalker** [comment]
Ok @dskaggs Just pushed that adjustment up there, much better, thanks again!

**Comment by dskaggs** [comment]
Thanks a bunch. Just pulled your changed into our repo. Thanks again for you work on this!
