### ISSUE TITLE
TS compile error in sample component

### ISSUE THREAD

**Issue by pavlovich** [NathanWalker/angular-seed-advanced#452]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

On a clean clone of the project, during the app startup (executing 'npm run start.deving'), the following Typescript compilation errors are displayed in the console:

/Users/pavlovich/projects/udc/registry/src/client/app/modules/sample/effects/sample.effect.ts(20,41): error TS2684: The 'this' context of type 'Actions' is not assignable to method's 'this' of type 'Observable<any>'.
  Types of property 'lift' are incompatible.
    Type '(operator: Operator<any, Action>) => Observable<Action>' is not assignable to type '<R>(operator: Operator<any, R>) => Observable<R>'.
      Types of parameters 'operator' and 'operator' are incompatible.
        Type 'Operator<any, R>' is not assignable to type 'Operator<any, Action>'.
          Type 'R' is not assignable to type 'Action'.
/Users/pavlovich/projects/udc/registry/src/client/app/modules/sample/effects/sample.effect.ts(31,40): error TS2684: The 'this' context of type 'Actions' is not assignable to method's 'this' of type 'Observable<any>'.

**Expected behavior**

The errors reported above would not be present in the console.

**Minimal reproduction of the problem with instructions**

1. Clone a fresh copy of the repo.
2. npm install
3. npm run start.deving
4. Observe the errors in the console.

**What is the motivation / use case for changing the behavior?**

Provide a clean sample app to be used as a reference for further development

**Please tell us about your environment:**

Mac OSX Sierra
Node 6.11.0
NPM 3.10.10

* **Angular Seed Version:** `aaaaf75`

[486dc0c]

* **Node:** `node --version` =
6.11.0

**Comment by renestalder** [comment]
See #450
