### ISSUE TITLE
Issue in isActive

### ISSUE THREAD

**Issue by deepakgd** [NathanWalker/angular-seed-advanced#46]
PFA i am facing this issue whenever i am trying to search isActive as true

![image](https://cloud.githubusercontent.com/assets/8350548/14553147/dcf15f86-0301-11e6-8f2e-fe1090cc6bdd.png)

**Comment by NathanWalker** [comment]
Hi @deepakgd , it appears you may have posted on the wrong repo. Your issue looks to be related to https://github.com/ssuperczynski/ng2-easy-table following your stack trace there. You might try posting an issue there, best of luck!
