### ISSUE TITLE
build.prod error cannot find or directory @angular/material

### ISSUE THREAD

**Issue by arlamaeen** [NathanWalker/angular-seed-advanced#461]
Hi! I'm trying to run build.prod but I'm getting this error 
![image](https://user-images.githubusercontent.com/28226846/30046916-b7f789e2-9240-11e7-9a91-0990d99cbb9a.png)

Do you have an idea on how to solve this? Is it the material's issue?

Thanks in advance

**Comment by megetron** [comment]
@arlamaeen , I am getting the exact error, did you find a solution to it?
