### ISSUE TITLE
Images folder for mobile applications

### ISSUE THREAD

**Issue by ragul-gnts** [NathanWalker/angular-seed-advanced#467]
Can you please tell me the "images" folder path for mobile application and how to load the background image from images folder in tns.scss file?

**Comment by NathanWalker** [comment]
You can use the `~/images/anything.png` to reference an image in (for example) and `images` folder within the `nativescript/src` directory.

```
.coverImage {
    background-image: ~/images/anything.jpg;
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
}
```
https://stackoverflow.com/questions/43333238/nativescript-how-to-set-a-background-image
