### ISSUE TITLE
require node module in renderer process

### ISSUE THREAD

**Issue by scayssials** [NathanWalker/angular-seed-advanced#47]
What configuration we need to change to be able to use file system for example on ipcRenderer in a component?

I have tried to use 

```
 require('electron').ipcRenderer
```

but I have an error that say (launch with npm start)

```
 "XHR error (404 Not Found) loading http://localhost:5555/node_modules/electron.js"
```

**Comment by NathanWalker** [comment]
It appears you may be trying to load `electron` from within the web build?  Given the `localhost:5555` error there. 
To run the electron app, follow these instructions: https://github.com/NathanWalker/angular2-seed-advanced#electron-app

Then you should be able to load `electron`, lemme know!

**Comment by fredericlefeurmou** [comment]
How is it possible to access electron from within main.web.ts?

`import * from 'electron'` doesn't seem to work. I tried to add the electron path in the system config but it didn't work.

Edit: My app is running locally

**Comment by NathanWalker** [comment]
You can access it `main.desktop.ts` since that is the main file electron uses.
