### ISSUE TITLE
Upgrade to @ngrx v4

### ISSUE THREAD

**Issue by Lonli-Lokli** [NathanWalker/angular-seed-advanced#473]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

Seed use ngrx v2

**Expected behavior**

Is it possible to update seed to use the latest ngrx/platform v4?

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular Seed Version:** `aaaaf75`

* **Node:** `node --version` =

**Comment by NathanWalker** [comment]
Hi @Lonli-Lokli thanks for the interest. I would recommend doing multi-platform integrations using [Nx](https://nrwl.io/nx) from Nrwl. You can use this as a guide (it uses ngrx 4 out of the box):
https://egghead.io/playlists/use-nativescript-with-nx-from-nrwl-161bd3e2
