### ISSUE TITLE
css precompile not work  while run android

### ISSUE THREAD

**Issue by shanxj** [NathanWalker/angular-seed-advanced#482]
now  I hava a problem ,  i donot know why .   when i  run "npm run start.android.device" ,  scss file  cannot compile to  css file.     
someone can  help me ?

**Comment by cesarvega** [comment]
hey @shanxj run it  like this '**npm run demo.android** 'if you want a sample project I can give you the one I have just let me know

**Comment by shanxj** [comment]
it is not project problem,   first time i git pull  project,    everything is ok .   but once i have delete the 'app/platform'  folder,   and  restart project,      css file can not  be compiled .

**Comment by shanxj** [comment]
ok , finally  i  use npm clean the project, and then , it is ok
