### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by roshinisesh** [NathanWalker/angular-seed-advanced#490]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
When I try to run the application using tns run ios , it gives me the following error.

<img width="1011" alt="screen shot 2018-07-26 at 10 42 51 am" src="https://user-images.githubusercontent.com/31548962/43331534-c0774cce-918b-11e8-945d-89ae07a94da0.png">

**Expected behavior**
The app should boot up without the JS error just like the web application.

**Minimal reproduction of the problem with instructions**
1) git clone "name of the repository"
2) npm i
3) cd nativescript 
4) npm i
4) tns run ios

It installs the app successfully , however, the app doesn't open. On manually opening the app, it gives a JS error.

**What is the motivation / use case for changing the behavior?**

To get the web and mobile running at the same time.

**Please tell us about your environment:**

Operating system : MAC OS (Tried it on windows too)  16GB RAM
package manager : npm, tns 

* **Angular Seed Version: 8aae926

* **Node:** `node --version` = v8.11.3

**Comment by milindmathur04** [comment]
Hey @roshinisesh , i have the same issue, have the web app working but cant get either of the mobile apps to work.
