### ISSUE TITLE
Error on npm install "cb() never called"

### ISSUE THREAD

**Issue by Jonatthu** [NathanWalker/angular-seed-advanced#50]
Node version: 5.9.1
Npm version: 3.8.6

I get an error when I want to install
"npm ERR! cb() never called! "
This only happened with Angular2-seed-advanced, my other projects don't have this issue.
I followed this post to try fix this issue https://www.bountysource.com/issues/974628-install-fails-with-cb-never-called

But it couldn't resolve anything the same message after that tutorial.

Any solution?

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/8053 , you have to upgrade to node 5.10.1

**Comment by Jonatthu** [comment]
Thanks a lot
