### ISSUE TITLE
Possible problem with Android builds

### ISSUE THREAD

**Issue by murth** [NathanWalker/angular-seed-advanced#52]
I'm just starting out with this stuff, so it's possible I made a mistake, however by following the guide in the readme of this seed, electron and most else of it works, but if I build an apk I get the following, whether I put it on my Nexus 5 running CM12 directly, or using android-sdk with nexus 5 and android 6.0 intel_x64 (I haven't tested others).

Just follow the instructions in the readme from a fresh git clone. I'm on arch linux 64, running testing repos and kernel 4.6rc3/4, but I think it's a code error. Typescript 1.8 from system, everything else latest.
Please let me know if you need anything else, but I've cloned the repo twice with the same results.
(for quick testing you can skip the npm install and go straight to "tns install".
I also noticed there was a recent commit affecting code with these lines.

![screenshot_20160419-175354](https://cloud.githubusercontent.com/assets/101689/14631641/bf73bc2a-0657-11e6-9646-cc29100adf56.png)
![screenshot_20160419-175405](https://cloud.githubusercontent.com/assets/101689/14631644/c268524c-0657-11e6-90f3-a05c933f6cb5.png)
![screenshot_20160419-175409](https://cloud.githubusercontent.com/assets/101689/14631647/c4c6a8e0-0657-11e6-91e3-c6f963cdb4b6.png)

**Comment by NathanWalker** [comment]
@murth Thank you so much for reporting this. Indeed, console.debug (a recent change) was not supported with Android (worth noting iOS **does** support it). At any rate, I just pushed up the fix for all platforms. Thanks again!
