### ISSUE TITLE
Webpacks support for web production deployment

### ISSUE THREAD

**Issue by dvulanov** [NathanWalker/angular-seed-advanced#57]
This looks like a really great scaffold, but I don't see anything for web deployment, like webpacks or jpsm.

Are there any plans to implement this, or am I missing something?

Thanks for the great work!

**Comment by NathanWalker** [comment]
Hi @dvulanov thanks for your kind words and question.

You can run:

```
npm run serve.prod
```

To view the production build in the browser. It builds out to `dist/prod` and runs from there.

You can also run:

```
npm run build.prod
```

To simply build production to `dist/prod`. Then you can drop the contents of `dist/prod` on any web server host.
