### ISSUE TITLE
angular2-seed update to rc.1

### ISSUE THREAD

**Issue by Jimmysh** [NathanWalker/angular-seed-advanced#62]

**Comment by NathanWalker** [comment]
👍 I just merged that PR on the parent seed. You're making me chuckle over here :) I'll get this updated with the parent tonight.

**Comment by NathanWalker** [comment]
I have everything updated on a branch but 1 last 3rd party lib will need to update to rc.1, ng2-translate to finish. @ocombe looks like theres a PR for ya https://github.com/ocombe/ng2-translate/pull/115 👍

**Comment by rodolfocop** [comment]
I saw that they are committed also to update to version 2.0.0 RC.1
I am awaiting for this update.

**Comment by ocombe** [comment]
You can use v2.1 of ng2-translate, I just merged the PR updating to RC1

**Comment by NathanWalker** [comment]
Master is now updated to rc.1 👍
