### ISSUE TITLE
Organising template files in the same folder for all platforms

### ISSUE THREAD

**Issue by chriswep** [NathanWalker/angular-seed-advanced#64]
I did some code changes [here](https://github.com/metzc/angular2-seed-advanced/commit/2f4082cde30b5b53d2fee3ce8af298d918d254e2) to show the idea of the (feature?) request.

Having all the template files side by side for one component would feel way more natural for me (and also more in the spirit of this seed, as far as i understand it).

This currently fails on runtime (iOS) with:
`Error: File app/components/app/app.component.xml does not exist.`
(However, the file does exist at this location in the nativescript folder.)

**Comment by NathanWalker** [comment]
Hi @metzc thanks, I will be bringing this change in soon however it will be based on this:  https://github.com/NathanWalker/nativescript-ng2-magic which uses `.tns.html` suffix to handle it and it works with the Parse5DomAdaptor issue where `.html` is required with views but you can still use {N} xml just fine in the `.tns.html` files.
https://github.com/NathanWalker/nativescript-ng2-magic#how-to-create-nativescript-views

I'll commit this change once the rc.1 update is complete. Just waiting on @ocombe to update ng2-translate :)

**Comment by chriswep** [comment]
nativescript-ng2-magic looks great! is the plan to fully merge it into the seed?

**Comment by NathanWalker** [comment]
I believe I will. I've been debating on whether I want to combine the decorator from magic with the one here. At any rate, this integration will be in by the end of the week.

**Comment by NathanWalker** [comment]
@metzc This is available on master now, see the new commands as well:
https://github.com/NathanWalker/angular2-seed-advanced#nativescript-app

This also creates a symbolic link between web src and {N} app so you can now make changes in either folder and they will be the same. Lastly, this makes `livesync` work with {N} dev workflow.
You will want to pull and run `npm install` again as the symbolic links are created as a `postinstall` step.
