### ISSUE TITLE
Integrate ng-bootstrap

### ISSUE THREAD

**Issue by dskaggs** [NathanWalker/angular-seed-advanced#7]
As requested, creating a separate ticket to track getting ng-bootstrap implemented in the seed project.

**Comment by NathanWalker** [comment]
Curious to swing @d3viant0ne in here. Josh, you are working on a Material Design integration correct?

I've been trying to make a decision as to whether to integrate MD or Bootstrap into master.
Whichever one did not go to master, I was thinking of having a branch with the other or if someone wanted to keep up with a forked integration into the other. Thinking aloud here.

**Comment by x4080** [comment]
MD is nicer for Android similarities and I want to shout out to @NathanWalker great job man :)

I think I use your card view plugin (pod)

**Comment by joshwiens** [comment]
@dskaggs - https://github.com/DeviantJS

I'll be done with an integration example/guide for Material2 shortly & ng2-bootstrap by the end of the day.

Given the advanced seed is based off the original, you should have a clean map to adding the same to the advanced seed.

**Comment by dskaggs** [comment]
@d3viant0ne Many thanks. I'm traveling at the moment but will definitely take a look early next week.

**Comment by NathanWalker** [comment]
@x4080 Thanks, hopefully the card view plugin is working alright for ya'. There's still some things to fix with it I believe. 

@d3viant0ne Thank you for all your efforts on the parent seed!

**Comment by joshwiens** [comment]
@dskaggs - For reference, ng2-bootstrap isn't in very good shape as a package. More than a few console errors, broken references / components. I'll keep the example repo up to day as they release new packages, hopefully it stabilizes.

I'm going to take a crack at using vanilla bootstrap4 to see if I can get better results.

**Comment by st-clair-clarke** [comment]
I would vote for support of ng2-material. So  when the official angular2-mateirial is released the application will not look very much different.

**Comment by CharlBest1** [comment]
+1 for ng2-material integration into seed project. This is an awesome project guys!! Thanks a lot :)

**Comment by joshwiens** [comment]
ng2-material will eventually be deprecated in favor of angular2-material which means adding it now, just means we have to rip it out later.

The answer here is to simply let the visual component frameworks mature and then run simple guides / example branches on how to integrate them into the advanced seed. Adding one just means that someone else has to rip it out in order to user his or her preferred framework.

**Comment by NathanWalker** [comment]
closing this in favor of this: https://github.com/NathanWalker/angular2-seed-advanced/issues/37
