### ISSUE TITLE
Electron build (windows) not working

### ISSUE THREAD

**Issue by s-f-a-g** [NathanWalker/angular-seed-advanced#70]
**Steps to reproduce and a minimal demo of the problem**

npm run build.desktop.windows or start.desktop.windows. The app seems to build, executable is in the folder, everything seems fine

_What steps should we try in your demo to see the problem?_
Launch the executable.

**Current behavior**
The app is stuck on "Loading..." and doesn't load at all.

**Expected/desired behavior**
Having angular components loading. Empty page for now.

**Comment by nlmueng** [comment]
Fails on mac also, here is the errors in the console

`zone.js?1462934431716:101 GET file:///node_modules/@angular/core/package.json net::ERR_FILE_NOT_FOUND

index.html:98 Error: Error: XHR error loading file:///node_modules/@angular/core/package.json(…) "Report this error at https://github.com/NathanWalker/angular2-seed-advanced/issues"`

**Comment by NathanWalker** [comment]
Hi @sebfag @nlmueng thanks for pointing this out.
Just pushed up the fix, please pull latest and all will be working for you now.
