### ISSUE TITLE
JSPM Support?

### ISSUE THREAD

**Issue by cthrax** [NathanWalker/angular-seed-advanced#71]
First off, thanks for the great seed and for staying on top of the moving target that is angular2.

This is really a question more than a feature request. I've been working on integrating this to my existing angular (and large) 1.x app, by adding in angular-upgrade, and switching from bower to jspm for package management. I'm just curious why you opted for the manual configuration of npm dependencies versus using JSPM or other.

The auto-config of systemjs that jspm generates has been really nice, but it's been a bit painful to get the bundling working due to the tmp folder used by the systemjs-builder and how to extricate just those files for jspm's use.

This is really for my own edification, so a satisfactory answer is "because it was easier", but I thought I would get any insights you have.

**Comment by NathanWalker** [comment]
Hi @cthrax thanks for the question. I actually rely on the underpinnings from the parent seed  https://github.com/mgechev/angular2-seed So if jspm were implemented there, it would be here as well.

I can't speak for Minko, but I believe the goal was to maintain the lowest overhead and stay true to just plain `systemjs`. 

Personally, I have actually grown found of plain SystemJS (initially did not like it though) and find the extensibility of the build configuration here to make working with SystemJS even better.

**Comment by cthrax** [comment]
That makes sense. One other quick question, since you seem to have used systemjs more than me, how do you handle dependencies that are a little more freeform than one might hope? I've been relying on the overrides that jspm offers, but I assume you're relying on custom shims for each of these? Or is there a better method?

Thanks for the quick reply!
