### ISSUE TITLE
[Feature Request] Integrate rlite/rlite-js as a provider for LocalStorage

### ISSUE THREAD

**Issue by flavius-popan** [NathanWalker/angular-seed-advanced#72]
It would be great to use a client side implementation of redis for LocalStorage. The [rlite](https://github.com/seppo0010/rlite) and [rlite-js](https://github.com/seppo0010/rlite-js) node.js bindings could make life a lot easier!

**Comment by NathanWalker** [comment]
Hi @fzsix Thanks for this idea :) Because things like this tend to be very opinionated from one project to another, I couldn't implement this on master, but feel free to fork and integrate and I would highlight in the README here 👍

**Comment by flavius-popan** [comment]
In the [Additional Features coming soon](https://github.com/NathanWalker/angular2-seed-advanced#additional-features-coming-soon) section you listed 

> provider for LocalStorage (abstraction for IndexedDB, WebSQL, localStorage, perhaps a port of localForage)

Have you already picked one out? I'm not exactly sure what you mean by 

> I couldn't implement this on master

since you did select other projects to integrate for other features. I guess I'm a little confused as to why this seems too opinionated if the provider is still in the tbd stage. Either way, I'm likely to do so and thank you for your time :)

**Comment by NathanWalker** [comment]
I've been thinking more an Angular2 service layer for that with no dependency on other languages. Correct me if I'm wrong but rlite depends on Ruby and Redis?

The other integrations are either (#trending) or becoming a preferred _way_ to do things in modern development. There may be things that sway from this but trying to keep that at a minimum.

But yeah, just trying to keep things within Angular2/TypeScript/JavaScript.

**Comment by flavius-popan** [comment]
@NathanWalker Nope! No ruby at all, it's written in C (rlite) and I also linked the JS Bindings. This is a well supported version of Redis that is intended to run on the client side with first class support for javascript. Which is why I thought it would be a great fit for this project.
