### ISSUE TITLE
livereload possible with Electron?

### ISSUE THREAD

**Issue by divramod** [NathanWalker/angular-seed-advanced#78]
hey, 

wow, thx for this awesome boilterplate!!!

i saw that livereloading is commented out.

how can i get it running?

**Comment by NathanWalker** [comment]
Livereload should work? Where do you see it commented out and what system are you running where it is not working for you? node, windows/mac, etc.

**Comment by divramod** [comment]
i am running electron on ubuntu with `npm start`
is it possible to have livereloading for electron?

**Comment by NathanWalker** [comment]
Ah there we go, that's a little more specific :)  I'm not 100% certain on livereloading with electron. I'll modify title and see if anyone is able to help here?

**Comment by JakePartusch** [comment]
Maybe this? https://github.com/Quramy/electron-connect

**Comment by NathanWalker** [comment]
@JakePartusch looks like that would work, thanks!! Ok this is on TODO list :) Unless community gets it before I which I would never mind 👍  Will be several days before I can get here.

**Comment by divramod** [comment]
hey, i created a running pull request. 

i am not that deep into electron. but it is basically running.

on the first change it is running slow. but the following changes are reflected faster.

**Comment by NathanWalker** [comment]
Thanks again for the PR @divramod It's on master and we all have a livereload setup for Desktop/Electron because of you. Awesome.

**Comment by divramod** [comment]
juhu :-)
