### ISSUE TITLE
Suggestions to improve workflow

### ISSUE THREAD

**Issue by fourctv** [NathanWalker/angular-seed-advanced#84]
Here is one suggestion to improve Read.me's "How to use..." workflow:
- add a note that user must do a 'git fetch upstream' & 'get merge upstream/master' before anything else, to ensure local/origin repo is up to date with seed's repo
- maybe also add a 'merge' script to package.json that does both steps. I have something like that in my copy:

`"merge": "git fetch upstream && git merge --no-commit upstream/master"`

(in my case I like to first look at the incoming changes before committing, hence the `--no-commit` option

**Comment by NathanJGaul** [comment]
Added this to my own workflow. Thank you!

**Comment by NathanWalker** [comment]
@fourctv Awesome suggestion. This will be going into master soon!
Should we have 2 commands? 1 for `--no-commit` and the other that would finish?
`npm run merge.preview`
`npm run merge`
?

I could also add a `npm run setup` which would auto setup the `upstream` to further simplify things.

**Comment by NathanWalker** [comment]
Both `npm run merge.preview` and `npm run merge` are available now.
There is also `npm run setup`. Instructions have been modified in readme: https://github.com/NathanWalker/angular2-seed-advanced#how-best-to-use-for-your-project

**Comment by fourctv** [comment]
That was just perfect. Nice improvement to my suggestion. Glad to be of help.
