### ISSUE TITLE
[Nativescript] Android Router Problem

### ISSUE THREAD

**Issue by divramod** [NathanWalker/angular-seed-advanced#88]
hey, 

i am just testing the nativescript app on an android device.

if i tab the About Button, the About Page is opened in a Modal.

when i hit the android back button, it flickers shortly, and then the About Page is opened again in the Modal and the console logs: `JS: Language change: en`.

So, no way of coming back home.

Besides that, the "About Page Modal" does not show the navigation directive nor the language chooser.

I tested it on two different devices.

any hint on that?

**Comment by NathanWalker** [comment]
On things like this, I would recommend checking posted issues [here](https://github.com/NativeScript/nativescript-angular/issues) as well as [here](https://github.com/NativeScript/nativescript/issues). First see if it has been reported and then you may post an issue if you don't find one.

**Comment by divramod** [comment]
ok
