### ISSUE TITLE
[Nativescript] generated js and js.map clutter directories

### ISSUE THREAD

**Issue by divramod** [NathanWalker/angular-seed-advanced#89]
hey,

when using 

```
tns livesync android --watch
```

typescript generates all the js and js.map files inside the src/ directory.

these files clutter the directories and force the other livescyncs (electron, browser) with change-events for their respective watchers.

is it somehow possible to have a own dist/natviescript/ directory from where the nativescript files could be served, so that the src/ directory will be kept clean?

thx again for the great starter ;-)

**Comment by NathanWalker** [comment]
1. I would not recommend running multiple watches for `electron`, `browser`, and `nativescript` at the same time. Not only would it be resource intensive but not a recommended workflow.
2. The `.js` and `.js.map` files generated by the {N} runtime should not interfere with anything and they are ignored by `git` so I don't see any pressing issue to resolve.
3. I would set your IDE to ignore those `.js` and `.js.map` files in `src` directory to hide them so they are not in your way when navigating through your project.

Thanks again for your contributions to make it better!

If you have further concerns here, please reopen. 👍
