### ISSUE TITLE
i18n: evaluate Angular core framework i18n support

### ISSUE THREAD

**Issue by NathanWalker** [NathanWalker/angular-seed-advanced#94]
Some background:
https://github.com/angular/angular/issues/7480

@ocombe If you have any relevant links here would be great. Just curious to begin evaluating the core i18n support the framework is starting to provide.

**Comment by NathanWalker** [comment]
For NativeScript use the new native i18n plugin: https://github.com/rborn/nativescript-i18n

**Comment by ocombe** [comment]
Well there is no documentation for the core i18n support yet, so I have no idea how it works and I don't really want to dig into the source code :P

**Comment by NathanWalker** [comment]
Agreed @ocombe I was curious if you knew something that I didn't :-0 I went searching for docs last week and wasn't sure if my googling skills had weakened or if I was truly searching for a unicorn.

**Comment by NathanWalker** [comment]
Closing to investigate at a later time after final release.
