### ISSUE TITLE
 libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wangfaxi1985** [NathanWalker/angular-seed-advanced#95]
**IMPORTANT**: in deepin linux os ,when this shell: npm run build.desktop.linux  done,run  ./angular2-seed-advanced 
 display error like this:
./angular2-seed-advanced: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

when i run Electron API Demos-linux-x64
does not have this problem

**Comment by joshwiens** [comment]
For reference this doesn't have anything to do with the Seed nor {N} directly.

The package you are missing is part of `libgtk2.0-0` which is included in most Linux distros evidently just not in yours.

IIRC Deepin in a Debian variant ( don't remember off the top of my head who is doing it ) but I do know it's not on the officially supported list for {N} / Android which means you are on your own getting it to work and will probably run into more missing dependencies at some point.

`sudo apt-get install libgtk2.0-0` should resolve the issue assuming the package is available for Deepin, given it's a Debian derivative I can't see why it wouldn't be.

**Comment by wangfaxi1985** [comment]
my deepin version is: 15.1.1 64 bit
when i run sudo apt-get install libgtk2.0-0  done ,
still display :
./angular2-seed-advanced: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by joshwiens** [comment]
Try the opposite architecture or what you installed i.e. i686 or i386 and then validate the version and see if they changed the binary install path.

Outside of that, lord only knows. Not to sound like a smart ass but as someone who started working on *Nix back when they called Solaris, SunOS their is a reason why technologies have a "supported" list.

Save yourself and **others** the pain of trolling dependencies, dependencies of dependencies, dependency versions & architectures and just use a linux distro that is supported for what you are trying to do.
