### ISSUE TITLE
i18n support without showing lang-switcher

### ISSUE THREAD

**Issue by friksa** [NathanWalker/angular-seed-advanced#96]
Using the web client, language translations work great as long as you show the language selector with <lang-switcher></lang-switcher>

The issue is that if you want to build a preference page that is not always visible, then language translations do not work.

Great project btw!!  Thanks so much!

**Comment by NathanWalker** [comment]
As long as you:

```
this.store.dispatch({ type: MULTILINGUAL_ACTIONS.LANG_CHANGE, payload: { lang: 'fr' } });
```

It will work from anywhere.
Give it a shot and lemme know.

**Comment by friksa** [comment]
That did not work for me, but this did:

```
constructor(private multilang: MultilingualService) {
  this.multilang.changeLang('en');
}
```

That works!  Thanks so much!

**Comment by NathanWalker** [comment]
Either will work 👍  For the other to work you would need:

```
constructor(private store: Store<any>) {
  this.store.dispatch({ type: MULTILINGUAL_ACTIONS.LANG_CHANGE, payload: { lang: 'en' } });
}
```

And of course would need to import `Store` and `MULTILINGUAL_ACTIONS`.

**Comment by friksa** [comment]
If I make this change to your code, it works too:

```
constructor(private store: Store<GwAppStore>, private multilang: MultilingualService) {
  this.store.dispatch({ type: MULTILINGUAL_ACTIONS.LANG_CHANGE, payload: { lang: 'en' } });
}
```

Without "private multilang: MultilingualService", it does not work for me.  Thanks again for the quick response!

**Comment by NathanWalker** [comment]
Yes thanks for pointing that out. It more has to do with fact that at least one `service` or `component` must inject `MultilingualService` somewhere. So `MultilingualService` could be injected in bootstrap or root component because the subscription that gets wired when that service is constructed will only happen if it's injected somewhere 👍  Good to clarify that, thanks again @friksa.
