### ISSUE TITLE
Adding jquery dependency to distribution

### ISSUE THREAD

**Issue by friksa** [NathanWalker/angular-seed-advanced#97]
I followed the steps at https://github.com/mgechev/angular2-seed/wiki/Add-external-scripts-and-styles for jquery. Did a npm --save install jquery and I can see it installed under node_modules.

The issue is that list/dev/node_modules does not have a copy of jquery. I even tried npm run build.dev

What else do I need to configure to get jquery into the distribution?

Thanks for a great project!!

**Comment by NathanWalker** [comment]
Please provide your setup and how you are adding `jquery`....

**Comment by friksa** [comment]
Used these instructions:
https://github.com/NathanWalker/angular2-seed-advanced#how-best-to-use-for-your-project

Then
npm --save install jquery

Add jquery dependency
./tools/config/project.config.ts

```
import { join } from 'path';
import { SeedAdvancedConfig } from './seed-advanced.config';
import { InjectableDependency } from './seed.config.interfaces';

/**
 * This class extends the basic seed configuration, allowing for project
 * specific overrides. A few examples can be found below.
 */
export class ProjectConfig extends SeedAdvancedConfig {

  PROJECT_TASKS_DIR = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');

  constructor() {
    super();
    this.APP_TITLE = 'GP6';
    let additional_deps: InjectableDependency[] = [
      {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
    ];

    const seedDependencies = this.NPM_DEPENDENCIES;

    this.NPM_DEPENDENCIES = seedDependencies.concat(additional_deps);
  }
}
```

./node_modules/jquery exists...

but ./dist/dev/node_modules/jquery does not

npm run build.dev does not copy jquery to dist folder either.  My assumption is that it should be copied to that folder since other dependencies are there and the client fails with jquery not found.  "browser_adapter.ts:78 ReferenceError: $ is not defined"

If I add this to index.html, jquery is found and everything works as expected:

```
<script src="../../node_modules/jquery/dist/jquery.min.js"></script>
```

**Comment by NathanWalker** [comment]
@friksa I just downloaded a fresh zip of the seed, did the following:

```
npm i
npm i jquery --save
```

Then modified `./tools/config/project.config.ts` to look like this (what you have above):

```
import { join } from 'path';
import { SeedAdvancedConfig } from './seed-advanced.config';
import { InjectableDependency } from './seed.config.interfaces';

/**
 * This class extends the basic seed configuration, allowing for project specific overrides. A few examples can be found
 * below.
 */
export class ProjectConfig extends SeedAdvancedConfig {

  PROJECT_TASKS_DIR = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');

  constructor() {
    super();
    // this.APP_TITLE = 'Put name of your app here';
    let additional_deps: InjectableDependency[] = [
      {src: 'jquery/dist/jquery.min.js', inject: 'libs'}
    ];

    const seedDependencies = this.NPM_DEPENDENCIES;

    this.NPM_DEPENDENCIES = seedDependencies.concat(additional_deps);
  }
}
```

Then ran:

```
npm start
```

And jquery loaded just fine. 
Where are you trying to use `jquery`? It's possible you are trying to use it somewhere before it is loaded.

**Comment by friksa** [comment]
Totally my fault.  I added my script tag after your script tags, but before 

```
  <!-- libs:js -->
  <!-- endinject -->
```

Sorry for wasting your time on this one.  I am still learning the whole build process and how things fit together.

It may help others like me if your index.html has a comment to make it clear where to add user scripts if needed.  I know most of the time this is not the way to go, but I have some javascript libraries that are not in npm.

```
<!----------------------- YOUR SCRIPT TAGS HERE --------------------->
```

**Comment by friksa** [comment]
Is there a better way to include non-npm js libs?

I have tried this, but this for project.config.ts, but not sure if I am on the right track to integrate https://github.com/RubaXa/Sortable - it is trying to load it from the wrong folder though: 
zone.js?1464355013322:101 GET http://localhost:5555/node_modules/Sortable/package.json 404 (Not Found)

```
import { join } from 'path';
import { SeedAdvancedConfig } from './seed-advanced.config';
import { InjectableDependency } from './seed.config.interfaces';

/**
 * This class extends the basic seed configuration, allowing for project specific overrides. A few examples can be found
 * below.
 */
export class ProjectConfig extends SeedAdvancedConfig {

  PROJECT_TASKS_DIR = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');

  constructor() {
    super();
    this.APP_TITLE = 'GP6';
    let additional_deps: InjectableDependency[] = [
      {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      {src: 'spectrum-colorpicker/spectrum.js', inject: 'libs'},
      {src: 'spectrum-colorpicker/spectrum.css', inject: true},
      {src: 'spectrum-colorpicker/spectrum.css', inject: true},
    ];

    let additional_assets: InjectableDependency[] = [
      { src: `${this.APP_SRC}/js/sortable.min.js`, inject: true, vendor: true }
    ];

    const seedAssets = this.APP_ASSETS;

    this.APP_ASSETS = seedAssets.concat(additional_assets);

    const seedDependencies = this.NPM_DEPENDENCIES;

    this.NPM_DEPENDENCIES = seedDependencies.concat(additional_deps);
  }
}
```

**Comment by friksa** [comment]
Also, when running the electron version with "npm run start.desktop", jquery does not load even though it loads fine in the web version.

```
file:///Users/friksa/dev-sp/gp6/dist/dev/node_modules/jquery/dist/jquery.min.js?1464449837787 Failed to load resource: net::ERR_FILE_NOT_FOUND
```

if I "cd src/client" and do "npm --save install jquery", then things work for the electron version too.

So, I assume that the correct process is to install jquery at both the top level as well as src/client?

I will do w tutorial / writeup on all this once I have figured it out myself, as I am sure others will have the same questions.
