### ISSUE TITLE
import 'rxjs/add/operator/max' fails

### ISSUE THREAD

**Issue by friksa** [NathanWalker/angular-seed-advanced#98]
I am able to import 'rxjs/add/operator/map', but not 'rxjs/add/operator/max'.

I am using the standard project and importing as follows:

```
import {Observable} from "rxjs/Rx";
import {Store} from '@ngrx/store';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/max';
```

I see the file in dist/dev/node_modules/rxjs/add/operator/max.js, but get this error on loading the page:

```
(index):139 Error: Error: XHR error (404 Not Found) loading http://localhost:5555/rxjs/add/operator/max.js(…) "Report this error at https://github.com/NathanWalker/angular2-seed-advanced/issues"
```

**Comment by joshwiens** [comment]
@friksa Not that this will resolve the issue but as an FYI you can do one or the other iirc. What you posted up there is pulling in all of the operators on line one ( a.k.a. kitchen sink ) and then trying to import them individually on lines 3 & 4.

Granular ( Observable class plus desired operators )

```
import {Observable} from 'rxjs/Observable';
import {Store} from '@ngrx/store';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/max';
```

Or (to include all operators):

```
import {Observable} from 'rxjs/Rx';
```

My RX experience isn't super strong yet but i'm pretty sure I'm correct
//cc @NathanWalker

**Comment by NathanWalker** [comment]
Yes that is correct @d3viant0ne  thanks. @friksa please try that ^

**Comment by NathanWalker** [comment]
@friksa Also merge in latest master from upstream here as I just pushed some updates, some of which may help you here.

**Comment by friksa** [comment]
After updating from the seed project and fixing the breaking changes, the import is working now.  I definitely still need this include or else it fails:

```
import 'rxjs/add/operator/max';
```

Thanks!

**Comment by joshwiens** [comment]
@friksa - Sorry I wasn't very clean with the kitchen sink thing.

My point was not that `import {Observable} from 'rxjs/Rx';` will import max & map, only that you can import max and map from the target ( that's the kitchen sink )

```
import {Observable, Map, Max} from 'rxjs/Rx';
```
