### ISSUE TITLE
Disabling browsersync

### ISSUE THREAD

**Issue by friksa** [NathanWalker/angular-seed-advanced#99]
We need a way to prevent two browsers from being synchronized while developing.   We are building software that synchronizes youtube videos on playback between different browsers.  The issue is that browsersync gets in the way when we load the video.

We have two browsers pointed to the same url.  One browser loads a youtube video and then our code tells the other browser to load the same video.  All user interactions are synchronized.  So it is important that browsersync does not change the url in other browsers while developing this part of our software.

Thanks!

**Comment by joshwiens** [comment]
@friksa - So what exactly are you looking for here? Completely disabling browser-sync or just keeping a single browser in sync? The solution depends entirely on your exact requirement.

**Comment by friksa** [comment]
Keeping a single browser in sync would be ideal so that development changes are reflected in the browser... maybe using live reload instead of browsersync since it requires a browser plugin??

**Comment by joshwiens** [comment]
@friksa - iirc you can just disable "ghost mode" to stop the multiple browser functionality. For reference, ghost mode can also be partially disabled to limit some but not all of the cross-browser functionality

Something like ...
`ghostMode: false,`

This is off the top of my head, I'll have to play around with it later to give you a real solution and not a maybe.

**Comment by friksa** [comment]
Thanks so much!! That works perfectly.  Just in case others have the same question, this is how it is set up.

Edit tools/config/project.config.ts and add this to the constructor

```
this.BROWSER_SYNC_CONFIG.ghostMode  = false;
```
